#version 460
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_long_vector : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, scalar) buffer SSBO
{
    vector<uint, 5> _m0[];
} _10;

layout(set = 0, binding = 0, scalar) buffer _13_15
{
    vector<uint, 6> _m0[];
} _15;

layout(set = 0, binding = 0, scalar) buffer _18_20
{
    vector<uint, 7> _m0[];
} _20;

layout(set = 0, binding = 0, std430) buffer _23_25
{
    vector<uint, 8> _m0[];
} _25;

void main()
{
    _10._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x]) + (vector<float, 5>(2.0, 2.0, 2.0, 2.0, 2.0)));
    _15._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_15._m0[gl_GlobalInvocationID.x]) + (vector<float, 6>(3.0, 3.0, 3.0, 3.0, 3.0, 3.0)));
    _20._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_20._m0[gl_GlobalInvocationID.x]) + (vector<float, 7>(4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0)));
    _25._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_25._m0[gl_GlobalInvocationID.x]) + (vector<float, 8>(5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0)));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 84
; Schema: 0
OpCapability Shader
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %15 %20 %25 %28
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %13 "SSBO"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpDecorate %7 ArrayStride 20
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %12 ArrayStride 24
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %17 ArrayStride 28
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %22 ArrayStride 32
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 Aliased
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 0
OpDecorate %15 Aliased
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 0
OpDecorate %20 Aliased
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 0
OpDecorate %25 Aliased
OpDecorate %28 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 5
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeVector %5 6
%12 = OpTypeRuntimeArray %11
%13 = OpTypeStruct %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%16 = OpTypeVector %5 7
%17 = OpTypeRuntimeArray %16
%18 = OpTypeStruct %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeVector %5 8
%22 = OpTypeRuntimeArray %21
%23 = OpTypeStruct %22
%24 = OpTypePointer StorageBuffer %23
%25 = OpVariable %24 StorageBuffer
%26 = OpTypeVector %5 3
%27 = OpTypePointer Input %26
%28 = OpVariable %27 Input
%29 = OpTypePointer Input %5
%31 = OpConstant %5 0
%34 = OpConstant %5 20
%35 = OpTypePointer StorageBuffer %6
%38 = OpTypeFloat 32
%39 = OpTypeVector %38 5
%42 = OpConstant %38 2
%43 = OpConstantComposite %39 %42 %42 %42 %42 %42
%47 = OpConstant %5 24
%48 = OpTypePointer StorageBuffer %11
%51 = OpTypeVector %38 6
%54 = OpConstant %38 3
%55 = OpConstantComposite %51 %54 %54 %54 %54 %54 %54
%59 = OpConstant %5 28
%60 = OpTypePointer StorageBuffer %16
%63 = OpTypeVector %38 7
%66 = OpConstant %38 4
%67 = OpConstantComposite %63 %66 %66 %66 %66 %66 %66 %66
%71 = OpConstant %5 5
%72 = OpTypePointer StorageBuffer %21
%75 = OpTypeVector %38 8
%78 = OpConstant %38 5
%79 = OpConstantComposite %75 %78 %78 %78 %78 %78 %78 %78 %78
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %82
%82 = OpLabel
%30 = OpAccessChain %29 %28 %31
%32 = OpLoad %5 %30
%33 = OpIMul %5 %32 %34
%36 = OpAccessChain %35 %10 %31 %32
%37 = OpLoad %6 %36
%40 = OpBitcast %39 %37
%41 = OpFAdd %39 %40 %43
%44 = OpBitcast %6 %41
%45 = OpAccessChain %35 %10 %31 %32
OpStore %45 %44
%46 = OpIMul %5 %32 %47
%49 = OpAccessChain %48 %15 %31 %32
%50 = OpLoad %11 %49
%52 = OpBitcast %51 %50
%53 = OpFAdd %51 %52 %55
%56 = OpBitcast %11 %53
%57 = OpAccessChain %48 %15 %31 %32
OpStore %57 %56
%58 = OpIMul %5 %32 %59
%61 = OpAccessChain %60 %20 %31 %32
%62 = OpLoad %16 %61
%64 = OpBitcast %63 %62
%65 = OpFAdd %63 %64 %67
%68 = OpBitcast %16 %65
%69 = OpAccessChain %60 %20 %31 %32
OpStore %69 %68
%70 = OpShiftLeftLogical %5 %32 %71
%73 = OpAccessChain %72 %25 %31 %32
%74 = OpLoad %21 %73
%76 = OpBitcast %75 %74
%77 = OpFAdd %75 %76 %79
%80 = OpBitcast %21 %77
%81 = OpAccessChain %72 %25 %31 %32
OpStore %81 %80
OpReturn
OpFunctionEnd
#endif
