#version 460
#extension GL_EXT_long_vector : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 18, local_size_y = 1, local_size_z = 1) in;

uint _247;
uint _248;
uint _249;
vector<uint, 8> _131;
vector<uint, 8> _152;
vector<uint, 8> _172;
vector<uint, 8> _192;
vector<uint, 8> _212;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    vector<uint, 8> _m0[];
} _10;

layout(set = 0, binding = 0, std430) writeonly buffer _12_14
{
    vector<uint, 8> _m0[];
} _14;

uvec4 WaveMatch(vector<uint, 8> _107)
{
    uvec4 _116;
    for (;;)
    {
        bool _115 = all(equal(_107, subgroupBroadcastFirst(_107)));
        _116 = subgroupBallot(_115);
        if (_115)
        {
            break;
        }
        else
        {
            continue;
        }
    }
    return _116;
}

vector<uint, 8> WaveMultiPrefixBitAnd(vector<uint, 8> _127, uvec4 _128)
{
    uvec4 _137 = subgroupBallot(true);
    uvec4 _139 = _137 & _128;
    bool _142;
    vector<uint, 8> _144;
    for (;;)
    {
        _142 = all(equal(_139, subgroupBroadcastFirst(_139)));
        if (_142)
        {
            _144 = subgroupExclusiveAnd(_127);
        }
        else
        {
            _144 = _131;
        }
        if (_142)
        {
            break;
        }
        else
        {
            continue;
        }
    }
    return _144;
}

vector<uint, 8> WaveMultiPrefixBitOr(vector<uint, 8> _148, uvec4 _149)
{
    uvec4 _158 = subgroupBallot(true);
    uvec4 _159 = _158 & _149;
    bool _162;
    vector<uint, 8> _164;
    for (;;)
    {
        _162 = all(equal(_159, subgroupBroadcastFirst(_159)));
        if (_162)
        {
            _164 = subgroupExclusiveOr(_148);
        }
        else
        {
            _164 = _152;
        }
        if (_162)
        {
            break;
        }
        else
        {
            continue;
        }
    }
    return _164;
}

vector<uint, 8> WaveMultiPrefixBitXor(vector<uint, 8> _168, uvec4 _169)
{
    uvec4 _178 = subgroupBallot(true);
    uvec4 _179 = _178 & _169;
    bool _182;
    vector<uint, 8> _184;
    for (;;)
    {
        _182 = all(equal(_179, subgroupBroadcastFirst(_179)));
        if (_182)
        {
            _184 = subgroupExclusiveXor(_168);
        }
        else
        {
            _184 = _172;
        }
        if (_182)
        {
            break;
        }
        else
        {
            continue;
        }
    }
    return _184;
}

vector<uint, 8> WaveMultiPrefixProduct(vector<uint, 8> _188, uvec4 _189)
{
    uvec4 _198 = subgroupBallot(true);
    uvec4 _199 = _198 & _189;
    bool _202;
    vector<uint, 8> _204;
    for (;;)
    {
        _202 = all(equal(_199, subgroupBroadcastFirst(_199)));
        if (_202)
        {
            _204 = subgroupExclusiveMul(_188);
        }
        else
        {
            _204 = _192;
        }
        if (_202)
        {
            break;
        }
        else
        {
            continue;
        }
    }
    return _204;
}

vector<uint, 8> WaveMultiPrefixSum(vector<uint, 8> _208, uvec4 _209)
{
    uvec4 _218 = subgroupBallot(true);
    uvec4 _219 = _218 & _209;
    bool _222;
    vector<uint, 8> _224;
    for (;;)
    {
        _222 = all(equal(_219, subgroupBroadcastFirst(_219)));
        if (_222)
        {
            _224 = subgroupExclusiveAdd(_208);
        }
        else
        {
            _224 = _212;
        }
        if (_222)
        {
            break;
        }
        else
        {
            continue;
        }
    }
    return _224;
}

void main()
{
    uint _22 = gl_GlobalInvocationID.x * 3u;
    uint _24 = gl_GlobalInvocationID.x * 3u;
    uint _31 = (gl_GlobalInvocationID.x * 3u) + 1u;
    uint _37 = (gl_GlobalInvocationID.x * 3u) + 2u;
    vector<uint, 8> _40 = subgroupAnd(_10._m0[_24]);
    vector<uint, 8> _41 = subgroupOr(_10._m0[_24]);
    vector<uint, 8> _42 = subgroupXor(_10._m0[_24]);
    vector<uint, 8> _43 = subgroupMul(_10._m0[_24]);
    vector<uint, 8> _44 = subgroupAdd(_10._m0[_24]);
    vector<uint, 8> _45 = subgroupMin(_10._m0[_24]);
    vector<uint, 8> _46 = subgroupMax(_10._m0[_24]);
    vector<uint, 8> _47 = subgroupExclusiveAdd(_10._m0[_24]);
    vector<uint, 8> _48 = subgroupExclusiveMul(_10._m0[_24]);
    vector<uint, 8> _49 = subgroupBroadcast(_10._m0[_31], 9u);
    vector<uint, 8> _51 = subgroupBroadcastFirst(_10._m0[_31]);
    bool _56 = subgroupAllEqual(_10._m0[_24][0]);
    bool _58 = subgroupAllEqual(_10._m0[_24][1]);
    bool _60 = subgroupAllEqual(_10._m0[_24][2]);
    bool _62 = subgroupAllEqual(_10._m0[_24][3]);
    bool _64 = subgroupAllEqual(_10._m0[_24][4]);
    bool _66 = subgroupAllEqual(_10._m0[_24][5]);
    bool _68 = subgroupAllEqual(_10._m0[_24][6]);
    bool _70 = subgroupAllEqual(_10._m0[_24][7]);
    bool _73 = subgroupAllEqual(_10._m0[_31][0]);
    bool _75 = subgroupAllEqual(_10._m0[_31][1]);
    bool _77 = subgroupAllEqual(_10._m0[_31][2]);
    bool _79 = subgroupAllEqual(_10._m0[_31][3]);
    bool _81 = subgroupAllEqual(_10._m0[_31][4]);
    bool _83 = subgroupAllEqual(_10._m0[_31][5]);
    bool _85 = subgroupAllEqual(_10._m0[_31][6]);
    bool _87 = subgroupAllEqual(_10._m0[_31][7]);
    bool _90 = subgroupAllEqual(_10._m0[_37][0]);
    bool _92 = subgroupAllEqual(_10._m0[_37][1]);
    bool _94 = subgroupAllEqual(_10._m0[_37][2]);
    bool _96 = subgroupAllEqual(_10._m0[_37][3]);
    bool _98 = subgroupAllEqual(_10._m0[_37][4]);
    bool _100 = subgroupAllEqual(_10._m0[_37][5]);
    bool _102 = subgroupAllEqual(_10._m0[_37][6]);
    bool _104 = subgroupAllEqual(_10._m0[_37][7]);
    uvec4 _118 = WaveMatch(_10._m0[_24]);
    uvec4 _119 = WaveMatch(_10._m0[_31]);
    uvec4 _120 = WaveMatch(_10._m0[_37]);
    vector<uint, 8> _146 = WaveMultiPrefixBitAnd(_10._m0[_24], uvec4(_10._m0[_31][0], _10._m0[_31][1], _10._m0[_31][2], _10._m0[_31][3]));
    vector<uint, 8> _166 = WaveMultiPrefixBitOr(_10._m0[_24], uvec4(_10._m0[_31][0], _10._m0[_31][1], _10._m0[_31][2], _10._m0[_31][3]));
    vector<uint, 8> _186 = WaveMultiPrefixBitXor(_10._m0[_24], uvec4(_10._m0[_31][0], _10._m0[_31][1], _10._m0[_31][2], _10._m0[_31][3]));
    vector<uint, 8> _206 = WaveMultiPrefixProduct(_10._m0[_24], uvec4(_10._m0[_31][0], _10._m0[_31][1], _10._m0[_31][2], _10._m0[_31][3]));
    vector<uint, 8> _226 = WaveMultiPrefixSum(_10._m0[_24], uvec4(_10._m0[_31][0], _10._m0[_31][1], _10._m0[_31][2], _10._m0[_31][3]));
    vector<uint, 8> _228;
    switch (gl_GlobalInvocationID.x)
    {
        case 0u:
        {
            _228 = _40;
            break;
        }
        case 1u:
        {
            _228 = _41;
            break;
        }
        case 2u:
        {
            _228 = _42;
            break;
        }
        case 3u:
        {
            _228 = _43;
            break;
        }
        case 4u:
        {
            _228 = _44;
            break;
        }
        case 5u:
        {
            _228 = _45;
            break;
        }
        case 6u:
        {
            _228 = _46;
            break;
        }
        case 7u:
        {
            _228 = _47;
            break;
        }
        case 8u:
        {
            _228 = _48;
            break;
        }
        case 9u:
        {
            _228 = _49;
            break;
        }
        case 10u:
        {
            _228 = _51;
            break;
        }
        case 11u:
        {
            _228 = ((mix(vector<uint, 8>(0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u), vector<uint, 8>(1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u), vector<bool, 8>(_73, _75, _77, _79, _81, _83, _85, _87)) << (vector<uint, 8>(8u, 8u, 8u, 8u, 8u, 8u, 8u, 8u))) | mix(vector<uint, 8>(0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u), vector<uint, 8>(1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u), vector<bool, 8>(_56, _58, _60, _62, _64, _66, _68, _70))) | (mix(vector<uint, 8>(0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u), vector<uint, 8>(1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u), vector<bool, 8>(_90, _92, _94, _96, _98, _100, _102, _104)) << (vector<uint, 8>(16u, 16u, 16u, 16u, 16u, 16u, 16u, 16u)));
            break;
        }
        case 12u:
        {
            vector<uint, 8> _246 = vector<uint, 8>(_247, _248, _249, 0u, 0u, 0u, 0u, 0u);
            _246[0] = _118.x;
            _246[1] = _119.x;
            _246[2] = _120.x;
            _228 = _246;
            break;
        }
        case 13u:
        {
            _228 = _146;
            break;
        }
        case 14u:
        {
            _228 = _166;
            break;
        }
        case 15u:
        {
            _228 = _186;
            break;
        }
        case 16u:
        {
            _228 = _206;
            break;
        }
        case 17u:
        {
            _228 = _226;
            break;
        }
        default:
        {
            _228 = vector<uint, 8>(0);
            break;
        }
    }
    _14._m0[gl_GlobalInvocationID.x] = _228;
}


#if 0
// SPIR-V disassembly
// WaveSize(32,128,32)
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 275
; Schema: 0
OpCapability Shader
OpCapability GroupNonUniform
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 18 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpName %108 "WaveMatch"
OpName %129 "WaveMultiPrefixBitAnd"
OpName %150 "WaveMultiPrefixBitOr"
OpName %170 "WaveMultiPrefixBitXor"
OpName %190 "WaveMultiPrefixProduct"
OpName %210 "WaveMultiPrefixSum"
OpDecorate %7 ArrayStride 32
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 32
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 8
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%23 = OpConstant %5 3
%25 = OpTypePointer StorageBuffer %6
%29 = OpConstant %5 1
%35 = OpConstant %5 2
%50 = OpConstant %5 9
%52 = OpTypeBool
%53 = OpTypeVector %52 8
%105 = OpTypeVector %5 4
%106 = OpTypeFunction %105 %6
%125 = OpTypeVector %52 4
%126 = OpTypeFunction %6 %6 %105
%138 = OpConstantTrue %52
%229 = OpConstantNull %6
%233 = OpConstantComposite %6 %20 %20 %20 %20 %20 %20 %20 %20
%234 = OpConstantComposite %6 %29 %29 %29 %29 %29 %29 %29 %29
%238 = OpConstant %5 8
%239 = OpConstantComposite %6 %238 %238 %238 %238 %238 %238 %238 %238
%243 = OpConstant %5 16
%244 = OpConstantComposite %6 %243 %243 %243 %243 %243 %243 %243 %243
%247 = OpUndef %5
%248 = OpUndef %5
%249 = OpUndef %5
%250 = OpConstantComposite %6 %247 %248 %249 %20 %20 %20 %20 %20
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %254
%254 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%22 = OpIMul %5 %21 %23
%24 = OpIMul %5 %21 %23
%26 = OpAccessChain %25 %10 %20 %24
%27 = OpLoad %6 %26
%28 = OpIAdd %5 %22 %29
%30 = OpIMul %5 %21 %23
%31 = OpIAdd %5 %30 %29
%32 = OpAccessChain %25 %10 %20 %31
%33 = OpLoad %6 %32
%34 = OpIAdd %5 %22 %35
%36 = OpIMul %5 %21 %23
%37 = OpIAdd %5 %36 %35
%38 = OpAccessChain %25 %10 %20 %37
%39 = OpLoad %6 %38
%40 = OpGroupNonUniformBitwiseAnd %6 %23 Reduce %27
%41 = OpGroupNonUniformBitwiseOr %6 %23 Reduce %27
%42 = OpGroupNonUniformBitwiseXor %6 %23 Reduce %27
%43 = OpGroupNonUniformIMul %6 %23 Reduce %27
%44 = OpGroupNonUniformIAdd %6 %23 Reduce %27
%45 = OpGroupNonUniformUMin %6 %23 Reduce %27
%46 = OpGroupNonUniformUMax %6 %23 Reduce %27
%47 = OpGroupNonUniformIAdd %6 %23 ExclusiveScan %27
%48 = OpGroupNonUniformIMul %6 %23 ExclusiveScan %27
%49 = OpGroupNonUniformBroadcast %6 %23 %33 %50
%51 = OpGroupNonUniformBroadcastFirst %6 %23 %33
%55 = OpCompositeExtract %5 %27 0
%56 = OpGroupNonUniformAllEqual %52 %23 %55
%57 = OpCompositeExtract %5 %27 1
%58 = OpGroupNonUniformAllEqual %52 %23 %57
%59 = OpCompositeExtract %5 %27 2
%60 = OpGroupNonUniformAllEqual %52 %23 %59
%61 = OpCompositeExtract %5 %27 3
%62 = OpGroupNonUniformAllEqual %52 %23 %61
%63 = OpCompositeExtract %5 %27 4
%64 = OpGroupNonUniformAllEqual %52 %23 %63
%65 = OpCompositeExtract %5 %27 5
%66 = OpGroupNonUniformAllEqual %52 %23 %65
%67 = OpCompositeExtract %5 %27 6
%68 = OpGroupNonUniformAllEqual %52 %23 %67
%69 = OpCompositeExtract %5 %27 7
%70 = OpGroupNonUniformAllEqual %52 %23 %69
%54 = OpCompositeConstruct %53 %56 %58 %60 %62 %64 %66 %68 %70
%72 = OpCompositeExtract %5 %33 0
%73 = OpGroupNonUniformAllEqual %52 %23 %72
%74 = OpCompositeExtract %5 %33 1
%75 = OpGroupNonUniformAllEqual %52 %23 %74
%76 = OpCompositeExtract %5 %33 2
%77 = OpGroupNonUniformAllEqual %52 %23 %76
%78 = OpCompositeExtract %5 %33 3
%79 = OpGroupNonUniformAllEqual %52 %23 %78
%80 = OpCompositeExtract %5 %33 4
%81 = OpGroupNonUniformAllEqual %52 %23 %80
%82 = OpCompositeExtract %5 %33 5
%83 = OpGroupNonUniformAllEqual %52 %23 %82
%84 = OpCompositeExtract %5 %33 6
%85 = OpGroupNonUniformAllEqual %52 %23 %84
%86 = OpCompositeExtract %5 %33 7
%87 = OpGroupNonUniformAllEqual %52 %23 %86
%71 = OpCompositeConstruct %53 %73 %75 %77 %79 %81 %83 %85 %87
%89 = OpCompositeExtract %5 %39 0
%90 = OpGroupNonUniformAllEqual %52 %23 %89
%91 = OpCompositeExtract %5 %39 1
%92 = OpGroupNonUniformAllEqual %52 %23 %91
%93 = OpCompositeExtract %5 %39 2
%94 = OpGroupNonUniformAllEqual %52 %23 %93
%95 = OpCompositeExtract %5 %39 3
%96 = OpGroupNonUniformAllEqual %52 %23 %95
%97 = OpCompositeExtract %5 %39 4
%98 = OpGroupNonUniformAllEqual %52 %23 %97
%99 = OpCompositeExtract %5 %39 5
%100 = OpGroupNonUniformAllEqual %52 %23 %99
%101 = OpCompositeExtract %5 %39 6
%102 = OpGroupNonUniformAllEqual %52 %23 %101
%103 = OpCompositeExtract %5 %39 7
%104 = OpGroupNonUniformAllEqual %52 %23 %103
%88 = OpCompositeConstruct %53 %90 %92 %94 %96 %98 %100 %102 %104
%118 = OpFunctionCall %105 %108 %27
%119 = OpFunctionCall %105 %108 %33
%120 = OpFunctionCall %105 %108 %39
%121 = OpCompositeExtract %5 %33 0
%122 = OpCompositeExtract %5 %33 1
%123 = OpCompositeExtract %5 %33 2
%124 = OpCompositeExtract %5 %33 3
%147 = OpCompositeConstruct %105 %121 %122 %123 %124
%146 = OpFunctionCall %6 %129 %27 %147
%167 = OpCompositeConstruct %105 %121 %122 %123 %124
%166 = OpFunctionCall %6 %150 %27 %167
%187 = OpCompositeConstruct %105 %121 %122 %123 %124
%186 = OpFunctionCall %6 %170 %27 %187
%207 = OpCompositeConstruct %105 %121 %122 %123 %124
%206 = OpFunctionCall %6 %190 %27 %207
%227 = OpCompositeConstruct %105 %121 %122 %123 %124
%226 = OpFunctionCall %6 %210 %27 %227
OpSelectionMerge %273 None
OpSwitch %21 %273 0 %272 1 %271 2 %270 3 %269 4 %268 5 %267 6 %266 7 %265 8 %264 9 %263 10 %262 11 %261 12 %260 13 %259 14 %258 15 %257 16 %256 17 %255
%272 = OpLabel
OpBranch %273
%271 = OpLabel
OpBranch %273
%270 = OpLabel
OpBranch %273
%269 = OpLabel
OpBranch %273
%268 = OpLabel
OpBranch %273
%267 = OpLabel
OpBranch %273
%266 = OpLabel
OpBranch %273
%265 = OpLabel
OpBranch %273
%264 = OpLabel
OpBranch %273
%263 = OpLabel
OpBranch %273
%262 = OpLabel
OpBranch %273
%261 = OpLabel
%235 = OpSelect %6 %54 %234 %233
%236 = OpSelect %6 %71 %234 %233
%237 = OpShiftLeftLogical %6 %236 %239
%240 = OpBitwiseOr %6 %237 %235
%241 = OpSelect %6 %88 %234 %233
%242 = OpShiftLeftLogical %6 %241 %244
%231 = OpBitwiseOr %6 %240 %242
OpBranch %273
%260 = OpLabel
%245 = OpCompositeExtract %5 %118 0
%246 = OpCompositeInsert %6 %245 %250 0
%251 = OpCompositeExtract %5 %119 0
%252 = OpCompositeInsert %6 %251 %246 1
%253 = OpCompositeExtract %5 %120 0
%230 = OpCompositeInsert %6 %253 %252 2
OpBranch %273
%259 = OpLabel
OpBranch %273
%258 = OpLabel
OpBranch %273
%257 = OpLabel
OpBranch %273
%256 = OpLabel
OpBranch %273
%255 = OpLabel
OpBranch %273
%273 = OpLabel
%228 = OpPhi %6 %229 %254 %40 %272 %41 %271 %42 %270 %43 %269 %44 %268 %45 %267 %46 %266 %47 %265 %48 %264 %49 %263 %51 %262 %231 %261 %230 %260 %146 %259 %166 %258 %186 %257 %206 %256 %226 %255
%232 = OpAccessChain %25 %14 %20 %21
OpStore %232 %228
OpReturn
OpFunctionEnd
%108 = OpFunction %105 None %106
%107 = OpFunctionParameter %6
%109 = OpLabel
OpBranch %110
%110 = OpLabel
OpLoopMerge %112 %111 None
OpBranch %111
%111 = OpLabel
%113 = OpGroupNonUniformBroadcastFirst %6 %23 %107
%114 = OpIEqual %53 %107 %113
%115 = OpAll %52 %114
%116 = OpGroupNonUniformBallot %105 %23 %115
OpBranchConditional %115 %112 %110
%112 = OpLabel
OpReturnValue %116
OpFunctionEnd
%129 = OpFunction %6 None %126
%127 = OpFunctionParameter %6
%128 = OpFunctionParameter %105
%130 = OpLabel
%131 = OpUndef %6
%137 = OpGroupNonUniformBallot %105 %23 %138
%139 = OpBitwiseAnd %105 %137 %128
OpBranch %132
%132 = OpLabel
OpLoopMerge %134 %133 None
OpBranch %133
%133 = OpLabel
%140 = OpGroupNonUniformBroadcastFirst %105 %23 %139
%141 = OpIEqual %125 %139 %140
%142 = OpAll %52 %141
OpSelectionMerge %136 None
OpBranchConditional %142 %135 %136
%135 = OpLabel
%143 = OpGroupNonUniformBitwiseAnd %6 %23 ExclusiveScan %127
OpBranch %136
%136 = OpLabel
%144 = OpPhi %6 %143 %135 %131 %133
OpBranchConditional %142 %134 %132
%134 = OpLabel
OpReturnValue %144
OpFunctionEnd
%150 = OpFunction %6 None %126
%148 = OpFunctionParameter %6
%149 = OpFunctionParameter %105
%151 = OpLabel
%152 = OpUndef %6
%158 = OpGroupNonUniformBallot %105 %23 %138
%159 = OpBitwiseAnd %105 %158 %149
OpBranch %153
%153 = OpLabel
OpLoopMerge %155 %154 None
OpBranch %154
%154 = OpLabel
%160 = OpGroupNonUniformBroadcastFirst %105 %23 %159
%161 = OpIEqual %125 %159 %160
%162 = OpAll %52 %161
OpSelectionMerge %157 None
OpBranchConditional %162 %156 %157
%156 = OpLabel
%163 = OpGroupNonUniformBitwiseOr %6 %23 ExclusiveScan %148
OpBranch %157
%157 = OpLabel
%164 = OpPhi %6 %163 %156 %152 %154
OpBranchConditional %162 %155 %153
%155 = OpLabel
OpReturnValue %164
OpFunctionEnd
%170 = OpFunction %6 None %126
%168 = OpFunctionParameter %6
%169 = OpFunctionParameter %105
%171 = OpLabel
%172 = OpUndef %6
%178 = OpGroupNonUniformBallot %105 %23 %138
%179 = OpBitwiseAnd %105 %178 %169
OpBranch %173
%173 = OpLabel
OpLoopMerge %175 %174 None
OpBranch %174
%174 = OpLabel
%180 = OpGroupNonUniformBroadcastFirst %105 %23 %179
%181 = OpIEqual %125 %179 %180
%182 = OpAll %52 %181
OpSelectionMerge %177 None
OpBranchConditional %182 %176 %177
%176 = OpLabel
%183 = OpGroupNonUniformBitwiseXor %6 %23 ExclusiveScan %168
OpBranch %177
%177 = OpLabel
%184 = OpPhi %6 %183 %176 %172 %174
OpBranchConditional %182 %175 %173
%175 = OpLabel
OpReturnValue %184
OpFunctionEnd
%190 = OpFunction %6 None %126
%188 = OpFunctionParameter %6
%189 = OpFunctionParameter %105
%191 = OpLabel
%192 = OpUndef %6
%198 = OpGroupNonUniformBallot %105 %23 %138
%199 = OpBitwiseAnd %105 %198 %189
OpBranch %193
%193 = OpLabel
OpLoopMerge %195 %194 None
OpBranch %194
%194 = OpLabel
%200 = OpGroupNonUniformBroadcastFirst %105 %23 %199
%201 = OpIEqual %125 %199 %200
%202 = OpAll %52 %201
OpSelectionMerge %197 None
OpBranchConditional %202 %196 %197
%196 = OpLabel
%203 = OpGroupNonUniformIMul %6 %23 ExclusiveScan %188
OpBranch %197
%197 = OpLabel
%204 = OpPhi %6 %203 %196 %192 %194
OpBranchConditional %202 %195 %193
%195 = OpLabel
OpReturnValue %204
OpFunctionEnd
%210 = OpFunction %6 None %126
%208 = OpFunctionParameter %6
%209 = OpFunctionParameter %105
%211 = OpLabel
%212 = OpUndef %6
%218 = OpGroupNonUniformBallot %105 %23 %138
%219 = OpBitwiseAnd %105 %218 %209
OpBranch %213
%213 = OpLabel
OpLoopMerge %215 %214 None
OpBranch %214
%214 = OpLabel
%220 = OpGroupNonUniformBroadcastFirst %105 %23 %219
%221 = OpIEqual %125 %219 %220
%222 = OpAll %52 %221
OpSelectionMerge %217 None
OpBranchConditional %222 %216 %217
%216 = OpLabel
%223 = OpGroupNonUniformIAdd %6 %23 ExclusiveScan %208
OpBranch %217
%217 = OpLabel
%224 = OpPhi %6 %223 %216 %212 %214
OpBranchConditional %222 %215 %213
%215 = OpLabel
OpReturnValue %224
OpFunctionEnd
#endif
