#version 460
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_long_vector : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, scalar) buffer SSBO
{
    vector<uint, 5> _m0[];
} _10;

layout(set = 0, binding = 1, scalar) buffer _13_15
{
    vector<uint, 6> _m0[];
} _15;

layout(set = 0, binding = 2, scalar) buffer _18_20
{
    vector<uint, 7> _m0[];
} _20;

layout(set = 0, binding = 3, std430) buffer _23_25
{
    vector<uint, 8> _m0[];
} _25;

void main()
{
    _10._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x]) + (vector<float, 5>(2.0, 2.0, 2.0, 2.0, 2.0)));
    _15._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_15._m0[gl_GlobalInvocationID.x]) + (vector<float, 6>(3.0, 3.0, 3.0, 3.0, 3.0, 3.0)));
    _20._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_20._m0[gl_GlobalInvocationID.x]) + (vector<float, 7>(4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0)));
    _25._m0[gl_GlobalInvocationID.x] = floatBitsToUint(uintBitsToFloat(_25._m0[gl_GlobalInvocationID.x]) + (vector<float, 8>(5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0)));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 76
; Schema: 0
OpCapability Shader
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %15 %20 %25 %28
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %13 "SSBO"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpDecorate %7 ArrayStride 20
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %12 ArrayStride 24
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 1
OpDecorate %17 ArrayStride 28
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 2
OpDecorate %22 ArrayStride 32
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 3
OpDecorate %28 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 5
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeVector %5 6
%12 = OpTypeRuntimeArray %11
%13 = OpTypeStruct %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%16 = OpTypeVector %5 7
%17 = OpTypeRuntimeArray %16
%18 = OpTypeStruct %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeVector %5 8
%22 = OpTypeRuntimeArray %21
%23 = OpTypeStruct %22
%24 = OpTypePointer StorageBuffer %23
%25 = OpVariable %24 StorageBuffer
%26 = OpTypeVector %5 3
%27 = OpTypePointer Input %26
%28 = OpVariable %27 Input
%29 = OpTypePointer Input %5
%31 = OpConstant %5 0
%33 = OpTypePointer StorageBuffer %6
%36 = OpTypeFloat 32
%37 = OpTypeVector %36 5
%40 = OpConstant %36 2
%41 = OpConstantComposite %37 %40 %40 %40 %40 %40
%44 = OpTypePointer StorageBuffer %11
%47 = OpTypeVector %36 6
%50 = OpConstant %36 3
%51 = OpConstantComposite %47 %50 %50 %50 %50 %50 %50
%54 = OpTypePointer StorageBuffer %16
%57 = OpTypeVector %36 7
%60 = OpConstant %36 4
%61 = OpConstantComposite %57 %60 %60 %60 %60 %60 %60 %60
%64 = OpTypePointer StorageBuffer %21
%67 = OpTypeVector %36 8
%70 = OpConstant %36 5
%71 = OpConstantComposite %67 %70 %70 %70 %70 %70 %70 %70 %70
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %74
%74 = OpLabel
%30 = OpAccessChain %29 %28 %31
%32 = OpLoad %5 %30
%34 = OpAccessChain %33 %10 %31 %32
%35 = OpLoad %6 %34
%38 = OpBitcast %37 %35
%39 = OpFAdd %37 %38 %41
%42 = OpBitcast %6 %39
%43 = OpAccessChain %33 %10 %31 %32
OpStore %43 %42
%45 = OpAccessChain %44 %15 %31 %32
%46 = OpLoad %11 %45
%48 = OpBitcast %47 %46
%49 = OpFAdd %47 %48 %51
%52 = OpBitcast %11 %49
%53 = OpAccessChain %44 %15 %31 %32
OpStore %53 %52
%55 = OpAccessChain %54 %20 %31 %32
%56 = OpLoad %16 %55
%58 = OpBitcast %57 %56
%59 = OpFAdd %57 %58 %61
%62 = OpBitcast %16 %59
%63 = OpAccessChain %54 %20 %31 %32
OpStore %63 %62
%65 = OpAccessChain %64 %25 %31 %32
%66 = OpLoad %21 %65
%68 = OpBitcast %67 %66
%69 = OpFAdd %67 %68 %71
%72 = OpBitcast %21 %69
%73 = OpAccessChain %64 %25 %31 %32
OpStore %73 %72
OpReturn
OpFunctionEnd
#endif
