#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 1, std430) buffer _14_16
{
    u16vec2 _m0[];
} _16;

layout(set = 0, binding = 2, std430) buffer _20_22
{
    u64vec2 _m0[];
} _22;

void main()
{
    _10._m0[0u] = uvec4(bitfieldReverse(_10._m0[0u]));
    _16._m0[0u] = u16vec2((bitfieldReverse(uvec2(_16._m0[0u]))).yw);
    _22._m0[0u] = u64vec2(bitfieldReverse((_22._m0[0u])).yxwz);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 60
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability Int16
OpCapability StorageBuffer16BitAccess
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %16 %22
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %14 "SSBO"
OpName %20 "SSBO"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %13 ArrayStride 4
OpMemberDecorate %14 0 Offset 0
OpDecorate %14 Block
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 1
OpDecorate %19 ArrayStride 16
OpMemberDecorate %20 0 Offset 0
OpDecorate %20 Block
OpDecorate %22 DescriptorSet 0
OpDecorate %22 Binding 2
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeInt 16 0
%12 = OpTypeVector %11 2
%13 = OpTypeRuntimeArray %12
%14 = OpTypeStruct %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeInt 64 0
%18 = OpTypeVector %17 2
%19 = OpTypeRuntimeArray %18
%20 = OpTypeStruct %19
%21 = OpTypePointer StorageBuffer %20
%22 = OpVariable %21 StorageBuffer
%23 = OpConstant %5 0
%24 = OpTypePointer StorageBuffer %6
%34 = OpTypePointer StorageBuffer %12
%37 = OpTypeVector %11 4
%38 = OpTypeVector %5 2
%47 = OpTypePointer StorageBuffer %18
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %58
%58 = OpLabel
%25 = OpAccessChain %24 %10 %23 %23
%26 = OpLoad %6 %25
%27 = OpBitReverse %6 %26
%28 = OpCompositeExtract %5 %27 0
%29 = OpCompositeExtract %5 %27 1
%30 = OpCompositeExtract %5 %27 2
%31 = OpCompositeExtract %5 %27 3
%32 = OpCompositeConstruct %6 %28 %29 %30 %31
%33 = OpAccessChain %24 %10 %23 %23
OpStore %33 %32
%35 = OpAccessChain %34 %16 %23 %23
%36 = OpLoad %12 %35
%39 = OpUConvert %38 %36
%40 = OpBitReverse %38 %39
%41 = OpBitcast %37 %40
%42 = OpVectorShuffle %12 %41 %41 1 3
%43 = OpCompositeExtract %11 %42 0
%44 = OpCompositeExtract %11 %42 1
%45 = OpCompositeConstruct %12 %43 %44
%46 = OpAccessChain %34 %16 %23 %23
OpStore %46 %45
%48 = OpAccessChain %47 %22 %23 %23
%49 = OpLoad %18 %48
%50 = OpBitcast %6 %49
%51 = OpBitReverse %6 %50
%52 = OpVectorShuffle %6 %51 %51 1 0 3 2
%53 = OpBitcast %18 %52
%54 = OpCompositeExtract %17 %53 0
%55 = OpCompositeExtract %17 %53 1
%56 = OpCompositeConstruct %18 %54 %55
%57 = OpAccessChain %47 %22 %23 %23
OpStore %57 %56
OpReturn
OpFunctionEnd
#endif
