#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uvec4 _34;

layout(set = 0, binding = 0, std430) readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 1, std430) readonly buffer _14_16
{
    u16vec2 _m0[];
} _16;

layout(set = 0, binding = 2, std430) readonly buffer _20_22
{
    u64vec2 _m0[];
} _22;

layout(set = 0, binding = 3, std430) writeonly buffer _25_27
{
    uvec2 _m0[];
} _27;

void main()
{
    _27._m0[0u] = uvec4(bitCount(_10._m0[0u])).xy;
    _27._m0[1u] = uvec2(bitCount(_16._m0[0u]));
    _27._m0[2u] = uvec2(bitCount(_22._m0[0u]));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 51
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability Int16
OpCapability StorageBuffer16BitAccess
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %16 %22 %27
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %14 "SSBO"
OpName %20 "SSBO"
OpName %25 "SSBO"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %13 ArrayStride 4
OpMemberDecorate %14 0 Offset 0
OpDecorate %14 Block
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 1
OpDecorate %16 NonWritable
OpDecorate %19 ArrayStride 16
OpMemberDecorate %20 0 Offset 0
OpDecorate %20 Block
OpDecorate %22 DescriptorSet 0
OpDecorate %22 Binding 2
OpDecorate %22 NonWritable
OpDecorate %24 ArrayStride 8
OpMemberDecorate %25 0 Offset 0
OpDecorate %25 Block
OpDecorate %27 DescriptorSet 0
OpDecorate %27 Binding 3
OpDecorate %27 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeInt 16 0
%12 = OpTypeVector %11 2
%13 = OpTypeRuntimeArray %12
%14 = OpTypeStruct %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeInt 64 0
%18 = OpTypeVector %17 2
%19 = OpTypeRuntimeArray %18
%20 = OpTypeStruct %19
%21 = OpTypePointer StorageBuffer %20
%22 = OpVariable %21 StorageBuffer
%23 = OpTypeVector %5 2
%24 = OpTypeRuntimeArray %23
%25 = OpTypeStruct %24
%26 = OpTypePointer StorageBuffer %25
%27 = OpVariable %26 StorageBuffer
%28 = OpConstant %5 0
%29 = OpTypePointer StorageBuffer %6
%35 = OpTypePointer StorageBuffer %23
%37 = OpTypePointer StorageBuffer %12
%41 = OpConstant %5 1
%43 = OpTypePointer StorageBuffer %18
%47 = OpConstant %5 2
%3 = OpFunction %1 None %2
%4 = OpLabel
%34 = OpUndef %6
OpBranch %49
%49 = OpLabel
%30 = OpAccessChain %29 %10 %28 %28
%31 = OpLoad %6 %30
%32 = OpBitCount %6 %31
%33 = OpVectorShuffle %23 %32 %34 0 1
%36 = OpAccessChain %35 %27 %28 %28
OpStore %36 %33
%38 = OpAccessChain %37 %16 %28 %28
%39 = OpLoad %12 %38
%40 = OpBitCount %23 %39
%42 = OpAccessChain %35 %27 %28 %41
OpStore %42 %40
%44 = OpAccessChain %43 %22 %28 %28
%45 = OpLoad %18 %44
%46 = OpBitCount %23 %45
%48 = OpAccessChain %35 %27 %28 %47
OpStore %48 %46
OpReturn
OpFunctionEnd
#endif
