#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uint _44;
uint _45;
uint _49;
uint _50;
uvec4 _53;

layout(set = 0, binding = 0, std430) readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 1, std430) readonly buffer _14_16
{
    u16vec2 _m0[];
} _16;

layout(set = 0, binding = 2, std430) readonly buffer _20_22
{
    u64vec2 _m0[];
} _22;

layout(set = 0, binding = 3, std430) writeonly buffer _25_27
{
    uvec2 _m0[];
} _27;

void main()
{
    uvec4 _33 = uvec4(findMSB(ivec4(_10._m0[0u])));
    uvec4 _42 = mix(uvec4(31u) - _33, uvec4(4294967295u), equal(_33, uvec4(4294967295u)));
    _27._m0[0u] = uvec2(mix(uvec4(31u, 31u, 0u, 0u) - _42, uvec4(4294967295u, 4294967295u, 0u, 0u), equal(_42, uvec4(4294967295u))).xy);
    uvec2 _63 = uvec2(findMSB(ivec2(uvec2(i16vec2(_16._m0[0u])))));
    uvec2 _70 = mix(uvec2(15u) - _63, uvec2(4294967295u), equal(_63, uvec2(4294967295u)));
    _27._m0[1u] = uvec2(mix(uvec2(15u) - _70, uvec2(4294967295u), equal(_70, uvec2(4294967295u))));
    uvec4 _82 = (_22._m0[0u]);
    uvec4 _92 = uvec4(findMSB(_82 ^ uvec4((ivec2(_82.yw) >> ivec2(31)).xxyy)));
    uvec2 _98 = uvec2(max(ivec2(_92.xz), ivec2(_92.yw | uvec2(32u))));
    uvec2 _103 = mix(uvec2(63u) - _98, uvec2(4294967295u), equal(_98, uvec2(4294967295u)));
    _27._m0[2u] = uvec2(mix(uvec2(63u) - _103, uvec2(4294967295u), equal(_103, uvec2(4294967295u))));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 114
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability Int16
OpCapability StorageBuffer16BitAccess
%32 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %16 %22 %27
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %14 "SSBO"
OpName %20 "SSBO"
OpName %25 "SSBO"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %13 ArrayStride 4
OpMemberDecorate %14 0 Offset 0
OpDecorate %14 Block
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 1
OpDecorate %16 NonWritable
OpDecorate %19 ArrayStride 16
OpMemberDecorate %20 0 Offset 0
OpDecorate %20 Block
OpDecorate %22 DescriptorSet 0
OpDecorate %22 Binding 2
OpDecorate %22 NonWritable
OpDecorate %24 ArrayStride 8
OpMemberDecorate %25 0 Offset 0
OpDecorate %25 Block
OpDecorate %27 DescriptorSet 0
OpDecorate %27 Binding 3
OpDecorate %27 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeInt 16 0
%12 = OpTypeVector %11 2
%13 = OpTypeRuntimeArray %12
%14 = OpTypeStruct %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeInt 64 0
%18 = OpTypeVector %17 2
%19 = OpTypeRuntimeArray %18
%20 = OpTypeStruct %19
%21 = OpTypePointer StorageBuffer %20
%22 = OpVariable %21 StorageBuffer
%23 = OpTypeVector %5 2
%24 = OpTypeRuntimeArray %23
%25 = OpTypeStruct %24
%26 = OpTypePointer StorageBuffer %25
%27 = OpVariable %26 StorageBuffer
%28 = OpConstant %5 0
%29 = OpTypePointer StorageBuffer %6
%34 = OpTypeBool
%35 = OpTypeVector %34 4
%37 = OpConstant %5 4294967295
%38 = OpConstantComposite %6 %37 %37 %37 %37
%40 = OpConstant %5 31
%41 = OpConstantComposite %6 %40 %40 %40 %40
%44 = OpUndef %5
%45 = OpUndef %5
%46 = OpConstantComposite %6 %40 %40 %44 %45
%49 = OpUndef %5
%50 = OpUndef %5
%51 = OpConstantComposite %6 %37 %37 %49 %50
%57 = OpTypePointer StorageBuffer %23
%59 = OpTypePointer StorageBuffer %12
%64 = OpTypeVector %34 2
%66 = OpConstantComposite %23 %37 %37
%68 = OpConstant %5 15
%69 = OpConstantComposite %23 %68 %68
%74 = OpConstant %5 1
%79 = OpTypePointer StorageBuffer %18
%84 = OpTypeInt 32 1
%85 = OpTypeVector %84 2
%87 = OpConstant %84 31
%88 = OpConstantComposite %85 %87 %87
%89 = OpTypeVector %84 4
%96 = OpConstant %5 32
%97 = OpConstantComposite %23 %96 %96
%101 = OpConstant %5 63
%102 = OpConstantComposite %23 %101 %101
%107 = OpConstant %5 2
%3 = OpFunction %1 None %2
%4 = OpLabel
%53 = OpUndef %6
OpBranch %112
%112 = OpLabel
%30 = OpAccessChain %29 %10 %28 %28
%31 = OpLoad %6 %30
%33 = OpExtInst %6 %32 FindSMsb %31
%36 = OpIEqual %35 %33 %38
%39 = OpISub %6 %41 %33
%42 = OpSelect %6 %36 %38 %39
%43 = OpISub %6 %46 %42
%47 = OpIEqual %35 %42 %38
%48 = OpSelect %6 %47 %51 %43
%52 = OpVectorShuffle %23 %48 %53 0 1
%54 = OpCompositeExtract %5 %52 0
%55 = OpCompositeExtract %5 %52 1
%56 = OpCompositeConstruct %23 %54 %55
%58 = OpAccessChain %57 %27 %28 %28
OpStore %58 %56
%60 = OpAccessChain %59 %16 %28 %28
%61 = OpLoad %12 %60
%62 = OpSConvert %23 %61
%63 = OpExtInst %23 %32 FindSMsb %62
%65 = OpIEqual %64 %63 %66
%67 = OpISub %23 %69 %63
%70 = OpSelect %23 %65 %66 %67
%71 = OpISub %23 %69 %70
%72 = OpIEqual %64 %70 %66
%73 = OpSelect %23 %72 %66 %71
%75 = OpCompositeExtract %5 %73 0
%76 = OpCompositeExtract %5 %73 1
%77 = OpCompositeConstruct %23 %75 %76
%78 = OpAccessChain %57 %27 %28 %74
OpStore %78 %77
%80 = OpAccessChain %79 %22 %28 %28
%81 = OpLoad %18 %80
%82 = OpBitcast %6 %81
%83 = OpVectorShuffle %23 %82 %82 1 3
%86 = OpShiftRightArithmetic %85 %83 %88
%90 = OpVectorShuffle %89 %86 %86 0 0 1 1
%91 = OpBitwiseXor %6 %82 %90
%92 = OpExtInst %6 %32 FindUMsb %91
%93 = OpVectorShuffle %23 %92 %92 0 2
%94 = OpVectorShuffle %23 %92 %92 1 3
%95 = OpBitwiseOr %23 %94 %97
%98 = OpExtInst %23 %32 SMax %93 %95
%99 = OpIEqual %64 %98 %66
%100 = OpISub %23 %102 %98
%103 = OpSelect %23 %99 %66 %100
%104 = OpISub %23 %102 %103
%105 = OpIEqual %64 %103 %66
%106 = OpSelect %23 %105 %66 %104
%108 = OpCompositeExtract %5 %106 0
%109 = OpCompositeExtract %5 %106 1
%110 = OpCompositeConstruct %23 %108 %109
%111 = OpAccessChain %57 %27 %28 %107
OpStore %111 %110
OpReturn
OpFunctionEnd
#endif
