; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 88
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Float64
OpCapability Int64
OpCapability Int16
OpCapability DenormPreserve
OpCapability RawAccessChainsNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_NV_raw_access_chains"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %9 %13 %16
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpExecutionMode %3 DenormPreserve 64
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %30 "ByteAddressMask"
OpName %28 "index"
OpName %29 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 0
OpDecorate %13 NonReadable
OpDecorate %16 BuiltIn GlobalInvocationId
OpDecorate %26 NonWritable
OpDecorate %45 NonWritable
OpDecorate %54 NonWritable
OpDecorate %67 NonWritable
OpDecorate %76 NonWritable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeVector %5 3
%15 = OpTypePointer Input %14
%16 = OpVariable %15 Input
%17 = OpTypePointer Input %5
%19 = OpConstant %5 0
%22 = OpConstant %5 2
%23 = OpTypeInt 16 0
%24 = OpTypeVector %23 2
%25 = OpTypePointer StorageBuffer %24
%27 = OpTypeFunction %5 %5 %5
%33 = OpConstant %5 4294967295
%37 = OpConstant %5 4
%40 = OpConstant %5 6
%42 = OpConstant %5 256
%43 = OpTypeVector %23 3
%44 = OpTypePointer StorageBuffer %43
%48 = OpConstant %5 3
%50 = OpConstant %5 640
%51 = OpTypeFloat 16
%52 = OpTypeVector %51 4
%53 = OpTypePointer StorageBuffer %52
%56 = OpConstant %5 80
%58 = OpConstant %5 8
%61 = OpConstant %5 24
%63 = OpConstant %5 1152
%64 = OpTypeInt 64 0
%65 = OpTypeVector %64 2
%66 = OpTypePointer StorageBuffer %65
%70 = OpConstant %5 5
%72 = OpConstant %5 2688
%73 = OpTypeFloat 64
%74 = OpTypeVector %73 4
%75 = OpTypePointer StorageBuffer %74
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %86
%86 = OpLabel
%18 = OpAccessChain %17 %16 %19
%20 = OpLoad %5 %18
%21 = OpShiftLeftLogical %5 %20 %22
%36 = OpFunctionCall %5 %30 %20 %37
%26 = OpRawAccessChainNV %25 %9 %37 %36 %19 RobustnessPerElementNV
%38 = OpLoad %24 %26 Aligned 4
%39 = OpIMul %5 %20 %40
%41 = OpIAdd %5 %39 %42
%45 = OpRawAccessChainNV %44 %9 %19 %19 %41 RobustnessPerComponentNV
%46 = OpLoad %43 %45 Aligned 2
%47 = OpShiftLeftLogical %5 %20 %48
%49 = OpIAdd %5 %47 %50
%55 = OpIAdd %5 %20 %56
%57 = OpFunctionCall %5 %30 %55 %58
%54 = OpRawAccessChainNV %53 %9 %58 %57 %19 RobustnessPerElementNV
%59 = OpLoad %52 %54 Aligned 8
%60 = OpIMul %5 %20 %61
%62 = OpIAdd %5 %60 %63
%67 = OpRawAccessChainNV %66 %9 %19 %19 %62 RobustnessPerComponentNV
%68 = OpLoad %65 %67 Aligned 8
%69 = OpShiftLeftLogical %5 %20 %70
%71 = OpIAdd %5 %69 %72
%76 = OpRawAccessChainNV %75 %9 %19 %19 %71 RobustnessPerComponentNV
%77 = OpLoad %74 %76 Aligned 32
%79 = OpFunctionCall %5 %30 %20 %37
%78 = OpRawAccessChainNV %25 %13 %37 %79 %19 RobustnessPerElementNV
OpStore %78 %38 Aligned 4
%80 = OpRawAccessChainNV %44 %13 %19 %19 %41 RobustnessPerComponentNV
OpStore %80 %46 Aligned 2
%82 = OpIAdd %5 %20 %56
%83 = OpFunctionCall %5 %30 %82 %58
%81 = OpRawAccessChainNV %53 %13 %58 %83 %19 RobustnessPerElementNV
OpStore %81 %59 Aligned 8
%84 = OpRawAccessChainNV %66 %13 %19 %19 %62 RobustnessPerComponentNV
OpStore %84 %68 Aligned 8
%85 = OpRawAccessChainNV %75 %13 %19 %19 %71 RobustnessPerComponentNV
OpStore %85 %77 Aligned 32
OpReturn
OpFunctionEnd
%30 = OpFunction %5 None %27
%28 = OpFunctionParameter %5
%29 = OpFunctionParameter %5
%31 = OpLabel
%32 = OpUDiv %5 %33 %29
%34 = OpBitwiseAnd %5 %28 %32
OpReturnValue %34
OpFunctionEnd

