; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 95
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Float64
OpCapability Int64
OpCapability Int16
OpCapability DenormPreserve
OpCapability RawAccessChainsNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_NV_raw_access_chains"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %16
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpExecutionMode %3 DenormPreserve 64
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %30 "ByteAddressMask"
OpName %28 "index"
OpName %29 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 0
OpDecorate %13 NonReadable
OpDecorate %16 BuiltIn GlobalInvocationId
OpDecorate %26 NonWritable
OpDecorate %46 NonWritable
OpDecorate %59 NonWritable
OpDecorate %68 NonWritable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeVector %5 3
%15 = OpTypePointer Input %14
%16 = OpVariable %15 Input
%17 = OpTypePointer Input %5
%19 = OpConstant %5 0
%22 = OpConstant %5 2
%23 = OpTypeInt 16 0
%24 = OpTypeVector %23 2
%25 = OpTypePointer StorageBuffer %24
%27 = OpTypeFunction %5 %5 %5
%33 = OpConstant %5 4294967295
%37 = OpConstant %5 4
%40 = OpConstant %5 3
%42 = OpConstant %5 256
%43 = OpTypeFloat 16
%44 = OpTypeVector %43 4
%45 = OpTypePointer StorageBuffer %44
%48 = OpConstant %5 32
%50 = OpConstant %5 8
%53 = OpConstant %5 24
%55 = OpConstant %5 512
%56 = OpTypeInt 64 0
%57 = OpTypeVector %56 2
%58 = OpTypePointer StorageBuffer %57
%62 = OpConstant %5 5
%64 = OpConstant %5 1024
%65 = OpTypeFloat 64
%66 = OpTypeVector %65 4
%67 = OpTypePointer StorageBuffer %66
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %93
%93 = OpLabel
%18 = OpAccessChain %17 %16 %19
%20 = OpLoad %5 %18
%21 = OpShiftLeftLogical %5 %20 %22
%36 = OpFunctionCall %5 %30 %20 %37
%26 = OpRawAccessChainNV %25 %9 %37 %36 %19 RobustnessPerElementNV
%38 = OpLoad %24 %26 Aligned 4
%39 = OpShiftLeftLogical %5 %20 %40
%41 = OpIAdd %5 %39 %42
%47 = OpIAdd %5 %20 %48
%49 = OpFunctionCall %5 %30 %47 %50
%46 = OpRawAccessChainNV %45 %9 %50 %49 %19 RobustnessPerElementNV
%51 = OpLoad %44 %46 Aligned 8
%52 = OpIMul %5 %20 %53
%54 = OpIAdd %5 %52 %55
%59 = OpRawAccessChainNV %58 %9 %19 %19 %54 RobustnessPerComponentNV
%60 = OpLoad %57 %59 Aligned 8
%61 = OpShiftLeftLogical %5 %20 %62
%63 = OpIAdd %5 %61 %64
%68 = OpRawAccessChainNV %67 %9 %19 %19 %63 RobustnessPerComponentNV
%69 = OpLoad %66 %68 Aligned 32
%70 = OpCompositeExtract %23 %38 0
%71 = OpCompositeExtract %23 %38 1
%73 = OpFunctionCall %5 %30 %20 %37
%72 = OpRawAccessChainNV %25 %13 %37 %73 %19 RobustnessPerElementNV
%74 = OpCompositeConstruct %24 %70 %71
OpStore %72 %74 Aligned 4
%75 = OpCompositeExtract %43 %51 0
%76 = OpCompositeExtract %43 %51 1
%77 = OpCompositeExtract %43 %51 2
%78 = OpCompositeExtract %43 %51 3
%80 = OpIAdd %5 %20 %48
%81 = OpFunctionCall %5 %30 %80 %50
%79 = OpRawAccessChainNV %45 %13 %50 %81 %19 RobustnessPerElementNV
%82 = OpCompositeConstruct %44 %75 %76 %77 %78
OpStore %79 %82 Aligned 8
%83 = OpCompositeExtract %56 %60 0
%84 = OpCompositeExtract %56 %60 1
%85 = OpRawAccessChainNV %58 %13 %19 %19 %54 RobustnessPerComponentNV
%86 = OpCompositeConstruct %57 %83 %84
OpStore %85 %86 Aligned 8
%87 = OpCompositeExtract %65 %69 0
%88 = OpCompositeExtract %65 %69 1
%89 = OpCompositeExtract %65 %69 2
%90 = OpCompositeExtract %65 %69 3
%91 = OpRawAccessChainNV %67 %13 %19 %19 %63 RobustnessPerComponentNV
%92 = OpCompositeConstruct %66 %87 %88 %89 %90
OpStore %91 %92 Aligned 32
OpReturn
OpFunctionEnd
%30 = OpFunction %5 None %27
%28 = OpFunctionParameter %5
%29 = OpFunctionParameter %5
%31 = OpLabel
%32 = OpUDiv %5 %33 %29
%34 = OpBitwiseAnd %5 %28 %32
OpReturnValue %34
OpFunctionEnd

