#version 460
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 0, std430) restrict readonly buffer _12_14
{
    uvec2 _m0[];
} _14;

layout(set = 0, binding = 0, std430) restrict readonly buffer _17_19
{
    uvec4 _m0[];
} _19;

layout(set = 0, binding = 0, std430) writeonly buffer _21_23
{
    uint _m0[];
} _23;

layout(set = 0, binding = 0, std430) writeonly buffer _25_27
{
    uvec2 _m0[];
} _27;

layout(set = 0, binding = 0, std430) writeonly buffer _29_31
{
    uvec4 _m0[];
} _31;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _77 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 192u, 4u);
    uint _90 = gl_GlobalInvocationID.x << 4u;
    _23._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)] = floatBitsToUint(uintBitsToFloat(_9._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)]));
    _27._m0[ByteAddressMask(gl_GlobalInvocationID.x + 32u, 8u)] = floatBitsToUint(uintBitsToFloat(_14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 32u, 8u)]));
    uint _119 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 192u, 4u);
    uvec3 _120 = floatBitsToUint(uintBitsToFloat(uvec3(_9._m0[_77], _9._m0[_77 + 1u], _9._m0[_77 + 2u])));
    _23._m0[_119] = _120.x;
    _23._m0[_119 + 1u] = _120.y;
    _23._m0[_119 + 2u] = _120.z;
    _31._m0[ByteAddressMask(gl_GlobalInvocationID.x + 96u, 16u)] = floatBitsToUint(uintBitsToFloat(_19._m0[ByteAddressMask(gl_GlobalInvocationID.x + 96u, 16u)]));
    _31._m0[ByteAddressMask(gl_GlobalInvocationID.x + 160u, 16u)] = floatBitsToUint(uintBitsToFloat(_19._m0[ByteAddressMask(gl_GlobalInvocationID.x + 160u, 16u)]));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 139
; Schema: 0
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %9 %14 %19 %23 %27 %31 %34
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %17 "SSBO"
OpName %21 "SSBO"
OpName %25 "SSBO"
OpName %29 "SSBO"
OpName %44 "ByteAddressMask"
OpName %42 "index"
OpName %43 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %16 ArrayStride 16
OpMemberDecorate %17 0 Offset 0
OpDecorate %17 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonWritable
OpDecorate %14 Restrict
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 0
OpDecorate %19 NonWritable
OpDecorate %19 Restrict
OpDecorate %20 ArrayStride 4
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %24 ArrayStride 8
OpMemberDecorate %25 0 Offset 0
OpDecorate %25 Block
OpDecorate %28 ArrayStride 16
OpMemberDecorate %29 0 Offset 0
OpDecorate %29 Block
OpDecorate %23 DescriptorSet 0
OpDecorate %23 Binding 0
OpDecorate %23 NonReadable
OpDecorate %23 Aliased
OpDecorate %27 DescriptorSet 0
OpDecorate %27 Binding 0
OpDecorate %27 NonReadable
OpDecorate %27 Aliased
OpDecorate %31 DescriptorSet 0
OpDecorate %31 Binding 0
OpDecorate %31 NonReadable
OpDecorate %31 Aliased
OpDecorate %34 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 2
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 4
%16 = OpTypeRuntimeArray %15
%17 = OpTypeStruct %16
%18 = OpTypePointer StorageBuffer %17
%19 = OpVariable %18 StorageBuffer
%20 = OpTypeRuntimeArray %5
%21 = OpTypeStruct %20
%22 = OpTypePointer StorageBuffer %21
%23 = OpVariable %22 StorageBuffer
%24 = OpTypeRuntimeArray %10
%25 = OpTypeStruct %24
%26 = OpTypePointer StorageBuffer %25
%27 = OpVariable %26 StorageBuffer
%28 = OpTypeRuntimeArray %15
%29 = OpTypeStruct %28
%30 = OpTypePointer StorageBuffer %29
%31 = OpVariable %30 StorageBuffer
%32 = OpTypeVector %5 3
%33 = OpTypePointer Input %32
%34 = OpVariable %33 Input
%35 = OpTypePointer Input %5
%37 = OpConstant %5 0
%40 = OpConstant %5 2
%41 = OpTypeFunction %5 %5 %5
%47 = OpConstant %5 4294967295
%51 = OpConstant %5 4
%52 = OpTypePointer StorageBuffer %5
%55 = OpTypeFloat 32
%58 = OpConstant %5 3
%60 = OpConstant %5 256
%62 = OpConstant %5 32
%64 = OpConstant %5 8
%65 = OpTypePointer StorageBuffer %10
%68 = OpTypeVector %55 2
%71 = OpConstant %5 12
%73 = OpConstant %5 768
%76 = OpConstant %5 192
%82 = OpConstant %5 1
%88 = OpTypeVector %55 3
%92 = OpConstant %5 1536
%94 = OpConstant %5 96
%96 = OpConstant %5 16
%97 = OpTypePointer StorageBuffer %15
%100 = OpTypeVector %55 4
%103 = OpConstant %5 2560
%105 = OpConstant %5 160
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %137
%137 = OpLabel
%36 = OpAccessChain %35 %34 %37
%38 = OpLoad %5 %36
%39 = OpShiftLeftLogical %5 %38 %40
%50 = OpFunctionCall %5 %44 %38 %51
%53 = OpAccessChain %52 %9 %37 %50
%54 = OpLoad %5 %53
%56 = OpBitcast %55 %54
%57 = OpShiftLeftLogical %5 %38 %58
%59 = OpIAdd %5 %57 %60
%61 = OpIAdd %5 %38 %62
%63 = OpFunctionCall %5 %44 %61 %64
%66 = OpAccessChain %65 %14 %37 %63
%67 = OpLoad %10 %66
%69 = OpBitcast %68 %67
%70 = OpIMul %5 %38 %71
%72 = OpIAdd %5 %70 %73
%74 = OpIMul %5 %38 %58
%75 = OpIAdd %5 %74 %76
%77 = OpFunctionCall %5 %44 %75 %51
%78 = OpAccessChain %52 %9 %37 %77
%79 = OpLoad %5 %78
%81 = OpIAdd %5 %77 %82
%80 = OpAccessChain %52 %9 %37 %81
%83 = OpLoad %5 %80
%85 = OpIAdd %5 %77 %40
%84 = OpAccessChain %52 %9 %37 %85
%86 = OpLoad %5 %84
%87 = OpCompositeConstruct %32 %79 %83 %86
%89 = OpBitcast %88 %87
%90 = OpShiftLeftLogical %5 %38 %51
%91 = OpIAdd %5 %90 %92
%93 = OpIAdd %5 %38 %94
%95 = OpFunctionCall %5 %44 %93 %96
%98 = OpAccessChain %97 %19 %37 %95
%99 = OpLoad %15 %98
%101 = OpBitcast %100 %99
%102 = OpIAdd %5 %90 %103
%104 = OpIAdd %5 %38 %105
%106 = OpFunctionCall %5 %44 %104 %96
%107 = OpAccessChain %97 %19 %37 %106
%108 = OpLoad %15 %107
%109 = OpBitcast %100 %108
%110 = OpFunctionCall %5 %44 %38 %51
%111 = OpBitcast %5 %56
%112 = OpAccessChain %52 %23 %37 %110
OpStore %112 %111
%113 = OpIAdd %5 %38 %62
%114 = OpFunctionCall %5 %44 %113 %64
%115 = OpBitcast %10 %69
%116 = OpAccessChain %65 %27 %37 %114
OpStore %116 %115
%117 = OpIMul %5 %38 %58
%118 = OpIAdd %5 %117 %76
%119 = OpFunctionCall %5 %44 %118 %51
%120 = OpBitcast %32 %89
%121 = OpCompositeExtract %5 %120 0
%122 = OpCompositeExtract %5 %120 1
%123 = OpCompositeExtract %5 %120 2
%124 = OpAccessChain %52 %23 %37 %119
OpStore %124 %121
%126 = OpIAdd %5 %119 %82
%125 = OpAccessChain %52 %23 %37 %126
OpStore %125 %122
%128 = OpIAdd %5 %119 %40
%127 = OpAccessChain %52 %23 %37 %128
OpStore %127 %123
%129 = OpIAdd %5 %38 %94
%130 = OpFunctionCall %5 %44 %129 %96
%131 = OpBitcast %15 %101
%132 = OpAccessChain %97 %31 %37 %130
OpStore %132 %131
%133 = OpIAdd %5 %38 %105
%134 = OpFunctionCall %5 %44 %133 %96
%135 = OpBitcast %15 %109
%136 = OpAccessChain %97 %31 %37 %134
OpStore %136 %135
OpReturn
OpFunctionEnd
%44 = OpFunction %5 None %41
%42 = OpFunctionParameter %5
%43 = OpFunctionParameter %5
%45 = OpLabel
%46 = OpUDiv %5 %47 %43
%48 = OpBitwiseAnd %5 %42 %46
OpReturnValue %48
OpFunctionEnd
#endif
