#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    u16vec2 _m0[];
} _11;

layout(set = 0, binding = 0, std430) restrict readonly buffer _14_16
{
    u16vec4 _m0[];
} _16;

layout(set = 0, binding = 0, std430) restrict readonly buffer _19_21
{
    uint64_t _m0[];
} _21;

layout(set = 0, binding = 0, std430) restrict readonly buffer _25_27
{
    dvec4 _m0[];
} _27;

layout(set = 0, binding = 0, std430) writeonly buffer _29_31
{
    u16vec2 _m0[];
} _31;

layout(set = 0, binding = 0, std430) writeonly buffer _33_35
{
    u16vec4 _m0[];
} _35;

layout(set = 0, binding = 0, std430) writeonly buffer _37_39
{
    uint64_t _m0[];
} _39;

layout(set = 0, binding = 0, std430) writeonly buffer _41_43
{
    dvec4 _m0[];
} _43;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _88 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 64u, 8u);
    u64vec2 _97 = u64vec2(_21._m0[_88], _21._m0[_88 + 1u]);
    _31._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)] = u16vec2(_11._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)]);
    _35._m0[ByteAddressMask(gl_GlobalInvocationID.x + 32u, 8u)] = u16vec4(float16BitsToUint16(uint16BitsToFloat16(_16._m0[ByteAddressMask(gl_GlobalInvocationID.x + 32u, 8u)])));
    uint _123 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 64u, 8u);
    _39._m0[_123] = _97.x;
    _39._m0[_123 + 1u] = _97.y;
    _43._m0[ByteAddressMask(gl_GlobalInvocationID.x + 32u, 32u)] = dvec4(_27._m0[ByteAddressMask(gl_GlobalInvocationID.x + 32u, 32u)]);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 139
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Float64
OpCapability Int64
OpCapability Int16
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %46
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpExecutionMode %3 DenormPreserve 64
OpName %3 "main"
OpName %9 "SSBO"
OpName %14 "SSBO"
OpName %19 "SSBO"
OpName %25 "SSBO"
OpName %29 "SSBO"
OpName %33 "SSBO"
OpName %37 "SSBO"
OpName %41 "SSBO"
OpName %56 "ByteAddressMask"
OpName %54 "index"
OpName %55 "stride"
OpDecorate %8 ArrayStride 4
OpMemberDecorate %9 0 Offset 0
OpDecorate %9 Block
OpDecorate %13 ArrayStride 8
OpMemberDecorate %14 0 Offset 0
OpDecorate %14 Block
OpDecorate %18 ArrayStride 8
OpMemberDecorate %19 0 Offset 0
OpDecorate %19 Block
OpDecorate %24 ArrayStride 32
OpMemberDecorate %25 0 Offset 0
OpDecorate %25 Block
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %11 NonWritable
OpDecorate %11 Restrict
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 0
OpDecorate %16 NonWritable
OpDecorate %16 Restrict
OpDecorate %21 DescriptorSet 0
OpDecorate %21 Binding 0
OpDecorate %21 NonWritable
OpDecorate %21 Restrict
OpDecorate %27 DescriptorSet 0
OpDecorate %27 Binding 0
OpDecorate %27 NonWritable
OpDecorate %27 Restrict
OpDecorate %28 ArrayStride 4
OpMemberDecorate %29 0 Offset 0
OpDecorate %29 Block
OpDecorate %32 ArrayStride 8
OpMemberDecorate %33 0 Offset 0
OpDecorate %33 Block
OpDecorate %36 ArrayStride 8
OpMemberDecorate %37 0 Offset 0
OpDecorate %37 Block
OpDecorate %40 ArrayStride 32
OpMemberDecorate %41 0 Offset 0
OpDecorate %41 Block
OpDecorate %31 DescriptorSet 0
OpDecorate %31 Binding 0
OpDecorate %31 NonReadable
OpDecorate %31 Aliased
OpDecorate %35 DescriptorSet 0
OpDecorate %35 Binding 0
OpDecorate %35 NonReadable
OpDecorate %35 Aliased
OpDecorate %39 DescriptorSet 0
OpDecorate %39 Binding 0
OpDecorate %39 NonReadable
OpDecorate %39 Aliased
OpDecorate %43 DescriptorSet 0
OpDecorate %43 Binding 0
OpDecorate %43 NonReadable
OpDecorate %43 Aliased
OpDecorate %46 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeInt 16 0
%7 = OpTypeVector %6 2
%8 = OpTypeRuntimeArray %7
%9 = OpTypeStruct %8
%10 = OpTypePointer StorageBuffer %9
%11 = OpVariable %10 StorageBuffer
%12 = OpTypeVector %6 4
%13 = OpTypeRuntimeArray %12
%14 = OpTypeStruct %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeInt 64 0
%18 = OpTypeRuntimeArray %17
%19 = OpTypeStruct %18
%20 = OpTypePointer StorageBuffer %19
%21 = OpVariable %20 StorageBuffer
%22 = OpTypeFloat 64
%23 = OpTypeVector %22 4
%24 = OpTypeRuntimeArray %23
%25 = OpTypeStruct %24
%26 = OpTypePointer StorageBuffer %25
%27 = OpVariable %26 StorageBuffer
%28 = OpTypeRuntimeArray %7
%29 = OpTypeStruct %28
%30 = OpTypePointer StorageBuffer %29
%31 = OpVariable %30 StorageBuffer
%32 = OpTypeRuntimeArray %12
%33 = OpTypeStruct %32
%34 = OpTypePointer StorageBuffer %33
%35 = OpVariable %34 StorageBuffer
%36 = OpTypeRuntimeArray %17
%37 = OpTypeStruct %36
%38 = OpTypePointer StorageBuffer %37
%39 = OpVariable %38 StorageBuffer
%40 = OpTypeRuntimeArray %23
%41 = OpTypeStruct %40
%42 = OpTypePointer StorageBuffer %41
%43 = OpVariable %42 StorageBuffer
%44 = OpTypeVector %5 3
%45 = OpTypePointer Input %44
%46 = OpVariable %45 Input
%47 = OpTypePointer Input %5
%49 = OpConstant %5 0
%52 = OpConstant %5 2
%53 = OpTypeFunction %5 %5 %5
%59 = OpConstant %5 4294967295
%63 = OpConstant %5 4
%64 = OpTypePointer StorageBuffer %7
%68 = OpConstant %5 3
%70 = OpConstant %5 256
%72 = OpConstant %5 32
%74 = OpConstant %5 8
%75 = OpTypePointer StorageBuffer %12
%78 = OpTypeFloat 16
%79 = OpTypeVector %78 4
%82 = OpConstant %5 24
%84 = OpConstant %5 512
%87 = OpConstant %5 64
%89 = OpTypePointer StorageBuffer %17
%94 = OpConstant %5 1
%96 = OpTypeVector %17 2
%99 = OpConstant %5 5
%101 = OpConstant %5 1024
%104 = OpTypePointer StorageBuffer %23
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %137
%137 = OpLabel
%48 = OpAccessChain %47 %46 %49
%50 = OpLoad %5 %48
%51 = OpShiftLeftLogical %5 %50 %52
%62 = OpFunctionCall %5 %56 %50 %63
%65 = OpAccessChain %64 %11 %49 %62
%66 = OpLoad %7 %65
%67 = OpShiftLeftLogical %5 %50 %68
%69 = OpIAdd %5 %67 %70
%71 = OpIAdd %5 %50 %72
%73 = OpFunctionCall %5 %56 %71 %74
%76 = OpAccessChain %75 %16 %49 %73
%77 = OpLoad %12 %76
%80 = OpBitcast %79 %77
%81 = OpIMul %5 %50 %82
%83 = OpIAdd %5 %81 %84
%85 = OpIMul %5 %50 %68
%86 = OpIAdd %5 %85 %87
%88 = OpFunctionCall %5 %56 %86 %74
%90 = OpAccessChain %89 %21 %49 %88
%91 = OpLoad %17 %90
%93 = OpIAdd %5 %88 %94
%92 = OpAccessChain %89 %21 %49 %93
%95 = OpLoad %17 %92
%97 = OpCompositeConstruct %96 %91 %95
%98 = OpShiftLeftLogical %5 %50 %99
%100 = OpIAdd %5 %98 %101
%102 = OpIAdd %5 %50 %72
%103 = OpFunctionCall %5 %56 %102 %72
%105 = OpAccessChain %104 %27 %49 %103
%106 = OpLoad %23 %105
%107 = OpFunctionCall %5 %56 %50 %63
%108 = OpCompositeExtract %6 %66 0
%109 = OpCompositeExtract %6 %66 1
%110 = OpCompositeConstruct %7 %108 %109
%111 = OpAccessChain %64 %31 %49 %107
OpStore %111 %110
%112 = OpIAdd %5 %50 %72
%113 = OpFunctionCall %5 %56 %112 %74
%114 = OpBitcast %12 %80
%115 = OpCompositeExtract %6 %114 0
%116 = OpCompositeExtract %6 %114 1
%117 = OpCompositeExtract %6 %114 2
%118 = OpCompositeExtract %6 %114 3
%119 = OpCompositeConstruct %12 %115 %116 %117 %118
%120 = OpAccessChain %75 %35 %49 %113
OpStore %120 %119
%121 = OpIMul %5 %50 %68
%122 = OpIAdd %5 %121 %87
%123 = OpFunctionCall %5 %56 %122 %74
%124 = OpCompositeExtract %17 %97 0
%125 = OpCompositeExtract %17 %97 1
%126 = OpAccessChain %89 %39 %49 %123
OpStore %126 %124
%128 = OpIAdd %5 %123 %94
%127 = OpAccessChain %89 %39 %49 %128
OpStore %127 %125
%129 = OpIAdd %5 %50 %72
%130 = OpFunctionCall %5 %56 %129 %72
%131 = OpCompositeExtract %22 %106 0
%132 = OpCompositeExtract %22 %106 1
%133 = OpCompositeExtract %22 %106 2
%134 = OpCompositeExtract %22 %106 3
%135 = OpCompositeConstruct %23 %131 %132 %133 %134
%136 = OpAccessChain %104 %43 %49 %130
OpStore %136 %135
OpReturn
OpFunctionEnd
%56 = OpFunction %5 None %53
%54 = OpFunctionParameter %5
%55 = OpFunctionParameter %5
%57 = OpLabel
%58 = OpUDiv %5 %59 %55
%60 = OpBitwiseAnd %5 %54 %58
OpReturnValue %60
OpFunctionEnd
#endif
