#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uint16_t _m0[];
} _10;

layout(set = 0, binding = 0, std430) restrict readonly buffer _13_15
{
    u16vec2 _m0[];
} _15;

layout(set = 0, binding = 0, std430) restrict readonly buffer _18_20
{
    u16vec4 _m0[];
} _20;

layout(set = 0, binding = 0, std430) restrict readonly buffer _23_25
{
    uint64_t _m0[];
} _25;

layout(set = 0, binding = 0, std430) restrict readonly buffer _29_31
{
    dvec4 _m0[];
} _31;

layout(set = 0, binding = 0, std430) writeonly buffer _33_35
{
    uint16_t _m0[];
} _35;

layout(set = 0, binding = 0, std430) writeonly buffer _37_39
{
    u16vec2 _m0[];
} _39;

layout(set = 0, binding = 0, std430) writeonly buffer _41_43
{
    u16vec4 _m0[];
} _43;

layout(set = 0, binding = 0, std430) writeonly buffer _45_47
{
    uint64_t _m0[];
} _47;

layout(set = 0, binding = 0, std430) writeonly buffer _49_51
{
    dvec4 _m0[];
} _51;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _83 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 128u, 2u);
    u16vec3 _95 = u16vec3(_10._m0[_83], _10._m0[_83 + 1u], _10._m0[_83 + 2u]);
    uint _116 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 144u, 8u);
    u64vec2 _124 = u64vec2(_25._m0[_116], _25._m0[_116 + 1u]);
    _39._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)] = u16vec2(_15._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)]);
    uint _143 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 128u, 2u);
    _35._m0[_143] = _95.x;
    _35._m0[_143 + 1u] = _95.y;
    _35._m0[_143 + 2u] = _95.z;
    _43._m0[ByteAddressMask(gl_GlobalInvocationID.x + 80u, 8u)] = u16vec4(float16BitsToUint16(uint16BitsToFloat16(_20._m0[ByteAddressMask(gl_GlobalInvocationID.x + 80u, 8u)])));
    uint _163 = ByteAddressMask((gl_GlobalInvocationID.x * 3u) + 144u, 8u);
    _47._m0[_163] = _124.x;
    _47._m0[_163 + 1u] = _124.y;
    _51._m0[ByteAddressMask(gl_GlobalInvocationID.x + 84u, 32u)] = dvec4(_31._m0[ByteAddressMask(gl_GlobalInvocationID.x + 84u, 32u)]);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 179
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Float64
OpCapability Int64
OpCapability Int16
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %54
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpExecutionMode %3 DenormPreserve 64
OpName %3 "main"
OpName %8 "SSBO"
OpName %13 "SSBO"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpName %29 "SSBO"
OpName %33 "SSBO"
OpName %37 "SSBO"
OpName %41 "SSBO"
OpName %45 "SSBO"
OpName %49 "SSBO"
OpName %64 "ByteAddressMask"
OpName %62 "index"
OpName %63 "stride"
OpDecorate %7 ArrayStride 2
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %12 ArrayStride 4
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %17 ArrayStride 8
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %22 ArrayStride 8
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %28 ArrayStride 32
OpMemberDecorate %29 0 Offset 0
OpDecorate %29 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 0
OpDecorate %15 NonWritable
OpDecorate %15 Restrict
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 0
OpDecorate %20 NonWritable
OpDecorate %20 Restrict
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 0
OpDecorate %25 NonWritable
OpDecorate %25 Restrict
OpDecorate %31 DescriptorSet 0
OpDecorate %31 Binding 0
OpDecorate %31 NonWritable
OpDecorate %31 Restrict
OpDecorate %32 ArrayStride 2
OpMemberDecorate %33 0 Offset 0
OpDecorate %33 Block
OpDecorate %36 ArrayStride 4
OpMemberDecorate %37 0 Offset 0
OpDecorate %37 Block
OpDecorate %40 ArrayStride 8
OpMemberDecorate %41 0 Offset 0
OpDecorate %41 Block
OpDecorate %44 ArrayStride 8
OpMemberDecorate %45 0 Offset 0
OpDecorate %45 Block
OpDecorate %48 ArrayStride 32
OpMemberDecorate %49 0 Offset 0
OpDecorate %49 Block
OpDecorate %35 DescriptorSet 0
OpDecorate %35 Binding 0
OpDecorate %35 NonReadable
OpDecorate %35 Aliased
OpDecorate %39 DescriptorSet 0
OpDecorate %39 Binding 0
OpDecorate %39 NonReadable
OpDecorate %39 Aliased
OpDecorate %43 DescriptorSet 0
OpDecorate %43 Binding 0
OpDecorate %43 NonReadable
OpDecorate %43 Aliased
OpDecorate %47 DescriptorSet 0
OpDecorate %47 Binding 0
OpDecorate %47 NonReadable
OpDecorate %47 Aliased
OpDecorate %51 DescriptorSet 0
OpDecorate %51 Binding 0
OpDecorate %51 NonReadable
OpDecorate %51 Aliased
OpDecorate %54 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeInt 16 0
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeVector %6 2
%12 = OpTypeRuntimeArray %11
%13 = OpTypeStruct %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%16 = OpTypeVector %6 4
%17 = OpTypeRuntimeArray %16
%18 = OpTypeStruct %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeInt 64 0
%22 = OpTypeRuntimeArray %21
%23 = OpTypeStruct %22
%24 = OpTypePointer StorageBuffer %23
%25 = OpVariable %24 StorageBuffer
%26 = OpTypeFloat 64
%27 = OpTypeVector %26 4
%28 = OpTypeRuntimeArray %27
%29 = OpTypeStruct %28
%30 = OpTypePointer StorageBuffer %29
%31 = OpVariable %30 StorageBuffer
%32 = OpTypeRuntimeArray %6
%33 = OpTypeStruct %32
%34 = OpTypePointer StorageBuffer %33
%35 = OpVariable %34 StorageBuffer
%36 = OpTypeRuntimeArray %11
%37 = OpTypeStruct %36
%38 = OpTypePointer StorageBuffer %37
%39 = OpVariable %38 StorageBuffer
%40 = OpTypeRuntimeArray %16
%41 = OpTypeStruct %40
%42 = OpTypePointer StorageBuffer %41
%43 = OpVariable %42 StorageBuffer
%44 = OpTypeRuntimeArray %21
%45 = OpTypeStruct %44
%46 = OpTypePointer StorageBuffer %45
%47 = OpVariable %46 StorageBuffer
%48 = OpTypeRuntimeArray %27
%49 = OpTypeStruct %48
%50 = OpTypePointer StorageBuffer %49
%51 = OpVariable %50 StorageBuffer
%52 = OpTypeVector %5 3
%53 = OpTypePointer Input %52
%54 = OpVariable %53 Input
%55 = OpTypePointer Input %5
%57 = OpConstant %5 0
%60 = OpConstant %5 2
%61 = OpTypeFunction %5 %5 %5
%67 = OpConstant %5 4294967295
%71 = OpConstant %5 4
%72 = OpTypePointer StorageBuffer %11
%76 = OpConstant %5 6
%78 = OpConstant %5 256
%80 = OpConstant %5 3
%82 = OpConstant %5 128
%84 = OpTypePointer StorageBuffer %6
%89 = OpConstant %5 1
%94 = OpTypeVector %6 3
%98 = OpConstant %5 640
%100 = OpConstant %5 80
%102 = OpConstant %5 8
%103 = OpTypePointer StorageBuffer %16
%106 = OpTypeFloat 16
%107 = OpTypeVector %106 4
%110 = OpConstant %5 24
%112 = OpConstant %5 1152
%115 = OpConstant %5 144
%117 = OpTypePointer StorageBuffer %21
%123 = OpTypeVector %21 2
%126 = OpConstant %5 5
%128 = OpConstant %5 2688
%130 = OpConstant %5 84
%132 = OpConstant %5 32
%133 = OpTypePointer StorageBuffer %27
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %177
%177 = OpLabel
%56 = OpAccessChain %55 %54 %57
%58 = OpLoad %5 %56
%59 = OpShiftLeftLogical %5 %58 %60
%70 = OpFunctionCall %5 %64 %58 %71
%73 = OpAccessChain %72 %15 %57 %70
%74 = OpLoad %11 %73
%75 = OpIMul %5 %58 %76
%77 = OpIAdd %5 %75 %78
%79 = OpIMul %5 %58 %80
%81 = OpIAdd %5 %79 %82
%83 = OpFunctionCall %5 %64 %81 %60
%85 = OpAccessChain %84 %10 %57 %83
%86 = OpLoad %6 %85
%88 = OpIAdd %5 %83 %89
%87 = OpAccessChain %84 %10 %57 %88
%90 = OpLoad %6 %87
%92 = OpIAdd %5 %83 %60
%91 = OpAccessChain %84 %10 %57 %92
%93 = OpLoad %6 %91
%95 = OpCompositeConstruct %94 %86 %90 %93
%96 = OpShiftLeftLogical %5 %58 %80
%97 = OpIAdd %5 %96 %98
%99 = OpIAdd %5 %58 %100
%101 = OpFunctionCall %5 %64 %99 %102
%104 = OpAccessChain %103 %20 %57 %101
%105 = OpLoad %16 %104
%108 = OpBitcast %107 %105
%109 = OpIMul %5 %58 %110
%111 = OpIAdd %5 %109 %112
%113 = OpIMul %5 %58 %80
%114 = OpIAdd %5 %113 %115
%116 = OpFunctionCall %5 %64 %114 %102
%118 = OpAccessChain %117 %25 %57 %116
%119 = OpLoad %21 %118
%121 = OpIAdd %5 %116 %89
%120 = OpAccessChain %117 %25 %57 %121
%122 = OpLoad %21 %120
%124 = OpCompositeConstruct %123 %119 %122
%125 = OpShiftLeftLogical %5 %58 %126
%127 = OpIAdd %5 %125 %128
%129 = OpIAdd %5 %58 %130
%131 = OpFunctionCall %5 %64 %129 %132
%134 = OpAccessChain %133 %31 %57 %131
%135 = OpLoad %27 %134
%136 = OpFunctionCall %5 %64 %58 %71
%137 = OpCompositeExtract %6 %74 0
%138 = OpCompositeExtract %6 %74 1
%139 = OpCompositeConstruct %11 %137 %138
%140 = OpAccessChain %72 %39 %57 %136
OpStore %140 %139
%141 = OpIMul %5 %58 %80
%142 = OpIAdd %5 %141 %82
%143 = OpFunctionCall %5 %64 %142 %60
%144 = OpCompositeExtract %6 %95 0
%145 = OpCompositeExtract %6 %95 1
%146 = OpCompositeExtract %6 %95 2
%147 = OpAccessChain %84 %35 %57 %143
OpStore %147 %144
%149 = OpIAdd %5 %143 %89
%148 = OpAccessChain %84 %35 %57 %149
OpStore %148 %145
%151 = OpIAdd %5 %143 %60
%150 = OpAccessChain %84 %35 %57 %151
OpStore %150 %146
%152 = OpIAdd %5 %58 %100
%153 = OpFunctionCall %5 %64 %152 %102
%154 = OpBitcast %16 %108
%155 = OpCompositeExtract %6 %154 0
%156 = OpCompositeExtract %6 %154 1
%157 = OpCompositeExtract %6 %154 2
%158 = OpCompositeExtract %6 %154 3
%159 = OpCompositeConstruct %16 %155 %156 %157 %158
%160 = OpAccessChain %103 %43 %57 %153
OpStore %160 %159
%161 = OpIMul %5 %58 %80
%162 = OpIAdd %5 %161 %115
%163 = OpFunctionCall %5 %64 %162 %102
%164 = OpCompositeExtract %21 %124 0
%165 = OpCompositeExtract %21 %124 1
%166 = OpAccessChain %117 %47 %57 %163
OpStore %166 %164
%168 = OpIAdd %5 %163 %89
%167 = OpAccessChain %117 %47 %57 %168
OpStore %167 %165
%169 = OpIAdd %5 %58 %130
%170 = OpFunctionCall %5 %64 %169 %132
%171 = OpCompositeExtract %26 %135 0
%172 = OpCompositeExtract %26 %135 1
%173 = OpCompositeExtract %26 %135 2
%174 = OpCompositeExtract %26 %135 3
%175 = OpCompositeConstruct %27 %171 %172 %173 %174
%176 = OpAccessChain %133 %51 %57 %170
OpStore %176 %175
OpReturn
OpFunctionEnd
%64 = OpFunction %5 None %61
%62 = OpFunctionParameter %5
%63 = OpFunctionParameter %5
%65 = OpLabel
%66 = OpUDiv %5 %67 %63
%68 = OpBitwiseAnd %5 %62 %66
OpReturnValue %68
OpFunctionEnd
#endif
