#version 460
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_shader_16bit_storage : require
#extension GL_KHR_shader_subgroup_quad : require
layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;

vec4 _30;
f16vec3 _62;
dvec4 _107;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 0, std430) writeonly buffer _12_14
{
    uvec4 _m0[];
} _14;

void main()
{
    vec2 _29 = uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x]).xy;
    vec2 _35 = subgroupQuadBroadcast(_29, 1u) - subgroupQuadBroadcast(_29, 0u);
    vec2 _39 = subgroupQuadBroadcast(_29, 2u) - subgroupQuadBroadcast(_29, 0u);
    _14._m0[gl_GlobalInvocationID.x] = uvec4(floatBitsToUint(vec4(_35.x, _35.y, _39.x, _39.y)));
    vec4 _52 = uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x + 1u]);
    f16vec3 _61;
    _61.x = float16_t(_52.x);
    _61.y = float16_t(_52.y);
    _61.z = float16_t(_52.z);
    f16vec3 _71 = (subgroupQuadBroadcast(_61, 2u) - subgroupQuadBroadcast(_61, 0u)) + (subgroupQuadBroadcast(_61, 1u) - subgroupQuadBroadcast(_61, 0u));
    vec4 _78;
    _78.x = float(_71.x);
    _78.y = float(_71.y);
    _78.z = float(_71.z);
    _78.w = 0.0;
    _14._m0[gl_GlobalInvocationID.x + 1u] = uvec4(floatBitsToUint(_78));
    vec4 _95 = uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x + 2u]);
    dvec4 _106;
    _106.x = double(_95.x);
    _106.y = double(_95.y);
    _106.z = double(_95.z);
    _106.w = double(_95.w);
    vec4 _111 = vec4(_106);
    dvec4 _120 = dvec4(subgroupQuadBroadcast(_111, 2u) - subgroupQuadBroadcast(_111, 0u)) + dvec4(subgroupQuadBroadcast(_111, 1u) - subgroupQuadBroadcast(_111, 0u));
    vec4 _129;
    _129.x = float(_120.x);
    _129.y = float(_120.y);
    _129.z = float(_120.z);
    _129.w = float(_120.w);
    _14._m0[gl_GlobalInvocationID.x + 2u] = uvec4(floatBitsToUint(_129));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 143
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Float64
OpCapability GroupNonUniformQuad
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 4 1 1
OpExecutionMode %3 DenormPreserve 16
OpExecutionMode %3 DenormPreserve 64
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 16
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%22 = OpTypePointer StorageBuffer %6
%25 = OpTypeFloat 32
%26 = OpTypeVector %25 4
%28 = OpTypeVector %25 2
%32 = OpConstant %5 3
%34 = OpConstant %5 1
%38 = OpConstant %5 2
%56 = OpTypeFloat 16
%60 = OpTypeVector %56 3
%82 = OpConstant %25 0
%100 = OpTypeFloat 64
%105 = OpTypeVector %100 4
%3 = OpFunction %1 None %2
%4 = OpLabel
%30 = OpUndef %26
%62 = OpUndef %60
%107 = OpUndef %105
OpBranch %141
%141 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%23 = OpAccessChain %22 %10 %20 %21
%24 = OpLoad %6 %23
%27 = OpBitcast %26 %24
%29 = OpVectorShuffle %28 %27 %30 0 1
%31 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %20
%33 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %34
%35 = OpFSub %28 %33 %31
%36 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %20
%37 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %38
%39 = OpFSub %28 %37 %36
%40 = OpVectorShuffle %26 %35 %39 0 1 2 3
%41 = OpBitcast %6 %40
%42 = OpCompositeExtract %5 %41 0
%43 = OpCompositeExtract %5 %41 1
%44 = OpCompositeExtract %5 %41 2
%45 = OpCompositeExtract %5 %41 3
%46 = OpCompositeConstruct %6 %42 %43 %44 %45
%47 = OpAccessChain %22 %14 %20 %21
OpStore %47 %46
%48 = OpIAdd %5 %21 %34
%49 = OpIAdd %5 %21 %34
%50 = OpAccessChain %22 %10 %20 %49
%51 = OpLoad %6 %50
%52 = OpBitcast %26 %51
%53 = OpCompositeExtract %25 %52 0
%54 = OpCompositeExtract %25 %52 1
%55 = OpCompositeExtract %25 %52 2
%57 = OpFConvert %56 %53
%58 = OpFConvert %56 %54
%59 = OpFConvert %56 %55
%61 = OpCompositeInsert %60 %57 %62 0
%63 = OpCompositeInsert %60 %58 %61 1
%64 = OpCompositeInsert %60 %59 %63 2
%65 = OpGroupNonUniformQuadBroadcast %60 %32 %64 %20
%66 = OpGroupNonUniformQuadBroadcast %60 %32 %64 %34
%67 = OpFSub %60 %66 %65
%68 = OpGroupNonUniformQuadBroadcast %60 %32 %64 %20
%69 = OpGroupNonUniformQuadBroadcast %60 %32 %64 %38
%70 = OpFSub %60 %69 %68
%71 = OpFAdd %60 %70 %67
%72 = OpCompositeExtract %56 %71 0
%73 = OpCompositeExtract %56 %71 1
%74 = OpCompositeExtract %56 %71 2
%75 = OpFConvert %25 %72
%76 = OpFConvert %25 %73
%77 = OpFConvert %25 %74
%78 = OpCompositeInsert %26 %75 %30 0
%79 = OpCompositeInsert %26 %76 %78 1
%80 = OpCompositeInsert %26 %77 %79 2
%81 = OpCompositeInsert %26 %82 %80 3
%83 = OpIAdd %5 %21 %34
%84 = OpBitcast %6 %81
%85 = OpCompositeExtract %5 %84 0
%86 = OpCompositeExtract %5 %84 1
%87 = OpCompositeExtract %5 %84 2
%88 = OpCompositeExtract %5 %84 3
%89 = OpCompositeConstruct %6 %85 %86 %87 %88
%90 = OpAccessChain %22 %14 %20 %83
OpStore %90 %89
%91 = OpIAdd %5 %21 %38
%92 = OpIAdd %5 %21 %38
%93 = OpAccessChain %22 %10 %20 %92
%94 = OpLoad %6 %93
%95 = OpBitcast %26 %94
%96 = OpCompositeExtract %25 %95 0
%97 = OpCompositeExtract %25 %95 1
%98 = OpCompositeExtract %25 %95 2
%99 = OpCompositeExtract %25 %95 3
%101 = OpFConvert %100 %96
%102 = OpFConvert %100 %97
%103 = OpFConvert %100 %98
%104 = OpFConvert %100 %99
%106 = OpCompositeInsert %105 %101 %107 0
%108 = OpCompositeInsert %105 %102 %106 1
%109 = OpCompositeInsert %105 %103 %108 2
%110 = OpCompositeInsert %105 %104 %109 3
%111 = OpFConvert %26 %110
%112 = OpGroupNonUniformQuadBroadcast %26 %32 %111 %20
%113 = OpGroupNonUniformQuadBroadcast %26 %32 %111 %34
%114 = OpFSub %26 %113 %112
%115 = OpFConvert %105 %114
%116 = OpGroupNonUniformQuadBroadcast %26 %32 %111 %20
%117 = OpGroupNonUniformQuadBroadcast %26 %32 %111 %38
%118 = OpFSub %26 %117 %116
%119 = OpFConvert %105 %118
%120 = OpFAdd %105 %119 %115
%121 = OpCompositeExtract %100 %120 0
%122 = OpCompositeExtract %100 %120 1
%123 = OpCompositeExtract %100 %120 2
%124 = OpCompositeExtract %100 %120 3
%125 = OpFConvert %25 %121
%126 = OpFConvert %25 %122
%127 = OpFConvert %25 %123
%128 = OpFConvert %25 %124
%129 = OpCompositeInsert %26 %125 %30 0
%130 = OpCompositeInsert %26 %126 %129 1
%131 = OpCompositeInsert %26 %127 %130 2
%132 = OpCompositeInsert %26 %128 %131 3
%133 = OpIAdd %5 %21 %38
%134 = OpBitcast %6 %132
%135 = OpCompositeExtract %5 %134 0
%136 = OpCompositeExtract %5 %134 1
%137 = OpCompositeExtract %5 %134 2
%138 = OpCompositeExtract %5 %134 3
%139 = OpCompositeConstruct %6 %135 %136 %137 %138
%140 = OpAccessChain %22 %14 %20 %133
OpStore %140 %139
OpReturn
OpFunctionEnd
#endif
