#version 460
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_shader_16bit_storage : require
#extension GL_KHR_shader_subgroup_quad : require
layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;

vec4 _30;
f16vec3 _57;
dvec4 _97;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 0, std430) writeonly buffer _12_14
{
    uvec4 _m0[];
} _14;

void main()
{
    vec2 _29 = uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x]).xy;
    vec2 _35 = subgroupQuadBroadcast(_29, 1u) - subgroupQuadBroadcast(_29, 0u);
    vec2 _39 = subgroupQuadBroadcast(_29, 2u) - subgroupQuadBroadcast(_29, 0u);
    _14._m0[gl_GlobalInvocationID.x] = floatBitsToUint(vec4(_35.x, _35.y, _39.x, _39.y));
    vec4 _47 = uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x + 1u]);
    f16vec3 _56;
    _56.x = float16_t(_47.x);
    _56.y = float16_t(_47.y);
    _56.z = float16_t(_47.z);
    f16vec3 _66 = (subgroupQuadBroadcast(_56, 2u) - subgroupQuadBroadcast(_56, 0u)) + (subgroupQuadBroadcast(_56, 1u) - subgroupQuadBroadcast(_56, 0u));
    vec4 _73;
    _73.x = float(_66.x);
    _73.y = float(_66.y);
    _73.z = float(_66.z);
    _73.w = 0.0;
    _14._m0[gl_GlobalInvocationID.x + 1u] = floatBitsToUint(_73);
    vec4 _85 = uintBitsToFloat(_10._m0[gl_GlobalInvocationID.x + 2u]);
    dvec4 _96;
    _96.x = double(_85.x);
    _96.y = double(_85.y);
    _96.z = double(_85.z);
    _96.w = double(_85.w);
    vec4 _101 = vec4(_96);
    dvec4 _110 = dvec4(subgroupQuadBroadcast(_101, 2u) - subgroupQuadBroadcast(_101, 0u)) + dvec4(subgroupQuadBroadcast(_101, 1u) - subgroupQuadBroadcast(_101, 0u));
    vec4 _119;
    _119.x = float(_110.x);
    _119.y = float(_110.y);
    _119.z = float(_110.z);
    _119.w = float(_110.w);
    _14._m0[gl_GlobalInvocationID.x + 2u] = floatBitsToUint(_119);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 128
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Float64
OpCapability GroupNonUniformQuad
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 4 1 1
OpExecutionMode %3 DenormPreserve 16
OpExecutionMode %3 DenormPreserve 64
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 16
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%22 = OpTypePointer StorageBuffer %6
%25 = OpTypeFloat 32
%26 = OpTypeVector %25 4
%28 = OpTypeVector %25 2
%32 = OpConstant %5 3
%34 = OpConstant %5 1
%38 = OpConstant %5 2
%51 = OpTypeFloat 16
%55 = OpTypeVector %51 3
%77 = OpConstant %25 0
%90 = OpTypeFloat 64
%95 = OpTypeVector %90 4
%3 = OpFunction %1 None %2
%4 = OpLabel
%30 = OpUndef %26
%57 = OpUndef %55
%97 = OpUndef %95
OpBranch %126
%126 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%23 = OpAccessChain %22 %10 %20 %21
%24 = OpLoad %6 %23
%27 = OpBitcast %26 %24
%29 = OpVectorShuffle %28 %27 %30 0 1
%31 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %20
%33 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %34
%35 = OpFSub %28 %33 %31
%36 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %20
%37 = OpGroupNonUniformQuadBroadcast %28 %32 %29 %38
%39 = OpFSub %28 %37 %36
%40 = OpVectorShuffle %26 %35 %39 0 1 2 3
%41 = OpBitcast %6 %40
%42 = OpAccessChain %22 %14 %20 %21
OpStore %42 %41
%43 = OpIAdd %5 %21 %34
%44 = OpIAdd %5 %21 %34
%45 = OpAccessChain %22 %10 %20 %44
%46 = OpLoad %6 %45
%47 = OpBitcast %26 %46
%48 = OpCompositeExtract %25 %47 0
%49 = OpCompositeExtract %25 %47 1
%50 = OpCompositeExtract %25 %47 2
%52 = OpFConvert %51 %48
%53 = OpFConvert %51 %49
%54 = OpFConvert %51 %50
%56 = OpCompositeInsert %55 %52 %57 0
%58 = OpCompositeInsert %55 %53 %56 1
%59 = OpCompositeInsert %55 %54 %58 2
%60 = OpGroupNonUniformQuadBroadcast %55 %32 %59 %20
%61 = OpGroupNonUniformQuadBroadcast %55 %32 %59 %34
%62 = OpFSub %55 %61 %60
%63 = OpGroupNonUniformQuadBroadcast %55 %32 %59 %20
%64 = OpGroupNonUniformQuadBroadcast %55 %32 %59 %38
%65 = OpFSub %55 %64 %63
%66 = OpFAdd %55 %65 %62
%67 = OpCompositeExtract %51 %66 0
%68 = OpCompositeExtract %51 %66 1
%69 = OpCompositeExtract %51 %66 2
%70 = OpFConvert %25 %67
%71 = OpFConvert %25 %68
%72 = OpFConvert %25 %69
%73 = OpCompositeInsert %26 %70 %30 0
%74 = OpCompositeInsert %26 %71 %73 1
%75 = OpCompositeInsert %26 %72 %74 2
%76 = OpCompositeInsert %26 %77 %75 3
%78 = OpIAdd %5 %21 %34
%79 = OpBitcast %6 %76
%80 = OpAccessChain %22 %14 %20 %78
OpStore %80 %79
%81 = OpIAdd %5 %21 %38
%82 = OpIAdd %5 %21 %38
%83 = OpAccessChain %22 %10 %20 %82
%84 = OpLoad %6 %83
%85 = OpBitcast %26 %84
%86 = OpCompositeExtract %25 %85 0
%87 = OpCompositeExtract %25 %85 1
%88 = OpCompositeExtract %25 %85 2
%89 = OpCompositeExtract %25 %85 3
%91 = OpFConvert %90 %86
%92 = OpFConvert %90 %87
%93 = OpFConvert %90 %88
%94 = OpFConvert %90 %89
%96 = OpCompositeInsert %95 %91 %97 0
%98 = OpCompositeInsert %95 %92 %96 1
%99 = OpCompositeInsert %95 %93 %98 2
%100 = OpCompositeInsert %95 %94 %99 3
%101 = OpFConvert %26 %100
%102 = OpGroupNonUniformQuadBroadcast %26 %32 %101 %20
%103 = OpGroupNonUniformQuadBroadcast %26 %32 %101 %34
%104 = OpFSub %26 %103 %102
%105 = OpFConvert %95 %104
%106 = OpGroupNonUniformQuadBroadcast %26 %32 %101 %20
%107 = OpGroupNonUniformQuadBroadcast %26 %32 %101 %38
%108 = OpFSub %26 %107 %106
%109 = OpFConvert %95 %108
%110 = OpFAdd %95 %109 %105
%111 = OpCompositeExtract %90 %110 0
%112 = OpCompositeExtract %90 %110 1
%113 = OpCompositeExtract %90 %110 2
%114 = OpCompositeExtract %90 %110 3
%115 = OpFConvert %25 %111
%116 = OpFConvert %25 %112
%117 = OpFConvert %25 %113
%118 = OpFConvert %25 %114
%119 = OpCompositeInsert %26 %115 %30 0
%120 = OpCompositeInsert %26 %116 %119 1
%121 = OpCompositeInsert %26 %117 %120 2
%122 = OpCompositeInsert %26 %118 %121 3
%123 = OpIAdd %5 %21 %38
%124 = OpBitcast %6 %122
%125 = OpAccessChain %22 %14 %20 %123
OpStore %125 %124
OpReturn
OpFunctionEnd
#endif
