RWByteAddressBuffer BAB[5] : register(u0);

[numthreads(64, 1, 1)]
void main(uint thr : SV_DispatchThreadID)
{
	BAB[0].Store<float4>(4 * thr, BAB[0].Load<float4>(4 * thr) + 4.0);
	BAB[1].Store<float4>(8 * thr, BAB[1].Load<float4>(8 * thr) + 4.0);
	BAB[2].Store<float4>(12 * thr, BAB[2].Load<float4>(12 * thr) + 4.0);
	BAB[3].Store<float4>(16 * thr, BAB[3].Load<float4>(16 * thr) + 4.0);
	BAB[4].Store<float4>(20 * thr, BAB[4].Load<float4>(20 * thr) + 4.0);
}
