RWByteAddressBuffer Buf : register(u0);

[numthreads(1, 1, 1)]
void main(uint3 index : SV_DispatchThreadID)
{
	uint result = 0;

	// Single branch
	[branch]
	if (index.x == 10)
		result = 40;
	else
		result = 50;

	// 2-level branch
	[branch]
	if (index.x == 20)
	{
		[branch]
		if (index.y == 30)
			result += 20;
		else
			result *= result;
	}
	else
	{
		[branch]
		if (index.y == 40)
			result += 70;
		else
			result *= 10;
	}

	Buf.Store(0, result);
}
