RWByteAddressBuffer Buf : register(u0);

uint func(uint3 index)
{
	uint result = 0;
	[branch]
	if (index.x == 10)
	{
		[branch]
		if (index.z == 40)
			return index.x * index.y;
		result += index.y;
	}
	else if (index.y == 20)
	{
		[branch]
		if (index.z == 50)
			return index.x * (index.y + 4);
		result += index.z;
	}

	result += index.x;

	return result;
}

[numthreads(1, 1, 1)]
void main(uint3 index : SV_DispatchThreadID)
{
	uint result = func(index);
	Buf.Store(0, result);
}
