RWByteAddressBuffer Buf : register(u0);

[numthreads(1, 1, 1)]
void main(uint3 index : SV_DispatchThreadID)
{
	uint result = 0;
	uint i = 0;

	while (i < index.x)
	{
		[branch]
		if (Buf.Load(4 * i) == 40)
		{
			[branch]
			if (i == 10)
			{
				Buf.Store(256 * i, i);
				i *= index.y;
				continue;
			}
			result += Buf.Load(16 * i);
		}
		else
		{
			result += Buf.Load(12 * i);
		}
		result += Buf.Load(8 * i);
		i++;
	}

	Buf.Store(0, result);
}
