RWByteAddressBuffer Buf : register(u0);

[numthreads(1, 1, 1)]
void main(uint3 index : SV_DispatchThreadID)
{
	uint result = 0;

	// Two level loop, with one break.
	[loop]
	for (uint j = 0; j < index.y; j++)
	{
		[loop]
		for (uint k = 0; k < index.z; k++)
		{
			if (Buf.Load(k * 128) == 10)
			{
				result += Buf.Load(8);
				break;
			}

			result += Buf.Load(4 * (j ^ k));
		}
	}
	Buf.Store(0, result);
}
