// Invalid, because of false positive: SPIRV-Tools issue 3100.

RWByteAddressBuffer Buf : register(u0);

[numthreads(1, 1, 1)]
void main(uint3 index : SV_DispatchThreadID)
{
	uint result = 0;

	// Three level loop.
	[loop]
	for (uint i = 0; i < index.x; i++)
	{
		[loop]
		for (uint j = 0; j < index.y; j++)
		{
			[loop]
			for (uint k = 0; k < index.z; k++)
			{
				result += Buf.Load(4 * (i ^ j ^ k));
			}
		}
	}
	Buf.Store(0, result);
}
