#version 460
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require
#if defined(GL_EXT_control_flow_attributes)
#extension GL_EXT_control_flow_attributes : require
#define SPIRV_CROSS_FLATTEN [[flatten]]
#define SPIRV_CROSS_BRANCH [[dont_flatten]]
#define SPIRV_CROSS_UNROLL [[unroll]]
#define SPIRV_CROSS_LOOP [[dont_unroll]]
#else
#define SPIRV_CROSS_FLATTEN
#define SPIRV_CROSS_BRANCH
#define SPIRV_CROSS_UNROLL
#define SPIRV_CROSS_LOOP
#endif
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, scalar) buffer SSBO
{
    u64vec3 _m0[];
} _11[];

layout(set = 0, binding = 0, scalar) restrict readonly buffer _13_16
{
    u64vec3 _m0[];
} _16[];

layout(set = 0, binding = 0, std430) buffer _18_21
{
    uint64_t _m0[];
} _21[];

layout(set = 0, binding = 0, std430) restrict readonly buffer _23_26
{
    uint64_t _m0[];
} _26[];

uint64_t UDiv(uint64_t num, uint64_t den)
{
    uint64_t _98;
    SPIRV_CROSS_FLATTEN
    if (den == 0ul)
    {
        _98 = 18446744073709551615ul;
    }
    else
    {
        _98 = num / den;
    }
    return _98;
}

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _47 = gl_GlobalInvocationID.x * 2u;
    uint _56 = (gl_GlobalInvocationID.x * 2u) + 1u;
    uint _65 = gl_GlobalInvocationID.x << 3u;
    _11[0u]._m0[gl_GlobalInvocationID.x * 8u] = u64vec3(_16[1u]._m0[_56].x + _16[1u]._m0[_47].x, _16[1u]._m0[_56].y + _16[1u]._m0[_47].y, _16[1u]._m0[_56].z + _16[1u]._m0[_47].z);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 1u] = u64vec3(_16[1u]._m0[_47].x - _16[1u]._m0[_56].x, _16[1u]._m0[_47].y - _16[1u]._m0[_56].y, _16[1u]._m0[_47].z - _16[1u]._m0[_56].z);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 2u] = u64vec3(_16[1u]._m0[_56].x * _16[1u]._m0[_47].x, _16[1u]._m0[_56].y * _16[1u]._m0[_47].y, _16[1u]._m0[_56].z * _16[1u]._m0[_47].z);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 3u] = u64vec3(UDiv(_16[1u]._m0[_47].x, _16[1u]._m0[_56].x), UDiv(_16[1u]._m0[_47].y, _16[1u]._m0[_56].y), UDiv(_16[1u]._m0[_47].z, _16[1u]._m0[_56].z));
    uint64_t _108 = _16[1u]._m0[_56].x & 63ul;
    uint64_t _110 = _16[1u]._m0[_56].y & 63ul;
    uint64_t _111 = _16[1u]._m0[_56].z & 63ul;
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 4u] = u64vec3(_16[1u]._m0[_47].x << _108, _16[1u]._m0[_47].y << _110, _16[1u]._m0[_47].z << _111);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 5u] = u64vec3(_16[1u]._m0[_47].x >> _108, _16[1u]._m0[_47].y >> _110, _16[1u]._m0[_47].z >> _111);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 6u] = u64vec3(uint64_t(int64_t(_16[1u]._m0[_47].x) >> int64_t(_108)), uint64_t(int64_t(_16[1u]._m0[_47].y) >> int64_t(_110)), uint64_t(int64_t(_16[1u]._m0[_47].z) >> int64_t(_111)));
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 7u] = u64vec3(_16[1u]._m0[_56].x & _16[1u]._m0[_47].x, _16[1u]._m0[_56].y & _16[1u]._m0[_47].y, _16[1u]._m0[_56].z & _16[1u]._m0[_47].z);
    uint _160 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 8u);
    u64vec2 _168 = u64vec2(_26[3u]._m0[_160], _26[3u]._m0[_160 + 1u]);
    uint _171 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    _21[2u]._m0[_171] = _168.x;
    _21[2u]._m0[_171 + 1u] = _168.y;
    _21[2u]._m0[_171 + 2u] = _16[1u]._m0[_47].z;
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 179
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability RuntimeDescriptorArray
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %30
OpExecutionMode %3 LocalSize 128 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %13 "SSBO"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpName %89 "UDiv"
OpName %87 "num"
OpName %88 "den"
OpName %154 "ByteAddressMask"
OpName %152 "index"
OpName %153 "stride"
OpDecorate %7 ArrayStride 24
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %12 ArrayStride 24
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 0
OpDecorate %16 NonWritable
OpDecorate %16 Restrict
OpDecorate %17 ArrayStride 8
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %21 DescriptorSet 0
OpDecorate %21 Binding 0
OpDecorate %22 ArrayStride 8
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %26 DescriptorSet 0
OpDecorate %26 Binding 0
OpDecorate %26 NonWritable
OpDecorate %26 Restrict
OpDecorate %30 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 64 0
%6 = OpTypeVector %5 3
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypeRuntimeArray %8
%10 = OpTypePointer StorageBuffer %9
%11 = OpVariable %10 StorageBuffer
%12 = OpTypeRuntimeArray %6
%13 = OpTypeStruct %12
%14 = OpTypeRuntimeArray %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeRuntimeArray %5
%18 = OpTypeStruct %17
%19 = OpTypeRuntimeArray %18
%20 = OpTypePointer StorageBuffer %19
%21 = OpVariable %20 StorageBuffer
%22 = OpTypeRuntimeArray %5
%23 = OpTypeStruct %22
%24 = OpTypeRuntimeArray %23
%25 = OpTypePointer StorageBuffer %24
%26 = OpVariable %25 StorageBuffer
%27 = OpTypeInt 32 0
%28 = OpTypeVector %27 3
%29 = OpTypePointer Input %28
%30 = OpVariable %29 Input
%31 = OpTypePointer Input %27
%33 = OpConstant %27 0
%35 = OpTypePointer StorageBuffer %8
%37 = OpTypePointer StorageBuffer %13
%39 = OpConstant %27 1
%40 = OpTypePointer StorageBuffer %18
%42 = OpConstant %27 2
%43 = OpTypePointer StorageBuffer %23
%45 = OpConstant %27 3
%48 = OpTypePointer StorageBuffer %6
%67 = OpConstant %27 8
%86 = OpTypeFunction %5 %5 %5
%91 = OpConstant %5 18446744073709551615
%94 = OpTypeBool
%96 = OpConstantNull %5
%109 = OpConstant %5 63
%116 = OpConstant %27 4
%125 = OpConstant %27 5
%134 = OpConstant %27 6
%143 = OpConstant %27 7
%149 = OpConstant %27 24
%151 = OpTypeFunction %27 %27 %27
%157 = OpConstant %27 4294967295
%161 = OpTypePointer StorageBuffer %5
%167 = OpTypeVector %5 2
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %177
%177 = OpLabel
%32 = OpAccessChain %31 %30 %33
%34 = OpLoad %27 %32
%36 = OpAccessChain %35 %11 %33
%38 = OpAccessChain %37 %16 %39
%41 = OpAccessChain %40 %21 %42
%44 = OpAccessChain %43 %26 %45
%46 = OpShiftLeftLogical %27 %34 %39
%47 = OpIMul %27 %34 %42
%49 = OpAccessChain %48 %38 %33 %47
%50 = OpLoad %6 %49
%51 = OpCompositeExtract %5 %50 0
%52 = OpCompositeExtract %5 %50 1
%53 = OpCompositeExtract %5 %50 2
%54 = OpBitwiseOr %27 %46 %39
%55 = OpIMul %27 %34 %42
%56 = OpIAdd %27 %55 %39
%57 = OpAccessChain %48 %38 %33 %56
%58 = OpLoad %6 %57
%59 = OpCompositeExtract %5 %58 0
%60 = OpCompositeExtract %5 %58 1
%61 = OpCompositeExtract %5 %58 2
%62 = OpIAdd %5 %59 %51
%63 = OpIAdd %5 %60 %52
%64 = OpIAdd %5 %61 %53
%65 = OpShiftLeftLogical %27 %34 %45
%66 = OpIMul %27 %34 %67
%68 = OpCompositeConstruct %6 %62 %63 %64
%69 = OpAccessChain %48 %36 %33 %66
OpStore %69 %68
%70 = OpISub %5 %51 %59
%71 = OpISub %5 %52 %60
%72 = OpISub %5 %53 %61
%73 = OpBitwiseOr %27 %65 %39
%74 = OpIMul %27 %34 %67
%75 = OpIAdd %27 %74 %39
%76 = OpCompositeConstruct %6 %70 %71 %72
%77 = OpAccessChain %48 %36 %33 %75
OpStore %77 %76
%78 = OpIMul %5 %59 %51
%79 = OpIMul %5 %60 %52
%80 = OpIMul %5 %61 %53
%81 = OpBitwiseOr %27 %65 %42
%82 = OpIMul %27 %34 %67
%83 = OpIAdd %27 %82 %42
%84 = OpCompositeConstruct %6 %78 %79 %80
%85 = OpAccessChain %48 %36 %33 %83
OpStore %85 %84
%100 = OpFunctionCall %5 %89 %51 %59
%101 = OpFunctionCall %5 %89 %52 %60
%102 = OpFunctionCall %5 %89 %53 %61
%103 = OpBitwiseOr %27 %65 %45
%104 = OpIMul %27 %34 %67
%105 = OpIAdd %27 %104 %45
%106 = OpCompositeConstruct %6 %100 %101 %102
%107 = OpAccessChain %48 %36 %33 %105
OpStore %107 %106
%108 = OpBitwiseAnd %5 %59 %109
%110 = OpBitwiseAnd %5 %60 %109
%111 = OpBitwiseAnd %5 %61 %109
%112 = OpShiftLeftLogical %5 %51 %108
%113 = OpShiftLeftLogical %5 %52 %110
%114 = OpShiftLeftLogical %5 %53 %111
%115 = OpBitwiseOr %27 %65 %116
%117 = OpIMul %27 %34 %67
%118 = OpIAdd %27 %117 %116
%119 = OpCompositeConstruct %6 %112 %113 %114
%120 = OpAccessChain %48 %36 %33 %118
OpStore %120 %119
%121 = OpShiftRightLogical %5 %51 %108
%122 = OpShiftRightLogical %5 %52 %110
%123 = OpShiftRightLogical %5 %53 %111
%124 = OpBitwiseOr %27 %65 %125
%126 = OpIMul %27 %34 %67
%127 = OpIAdd %27 %126 %125
%128 = OpCompositeConstruct %6 %121 %122 %123
%129 = OpAccessChain %48 %36 %33 %127
OpStore %129 %128
%130 = OpShiftRightArithmetic %5 %51 %108
%131 = OpShiftRightArithmetic %5 %52 %110
%132 = OpShiftRightArithmetic %5 %53 %111
%133 = OpBitwiseOr %27 %65 %134
%135 = OpIMul %27 %34 %67
%136 = OpIAdd %27 %135 %134
%137 = OpCompositeConstruct %6 %130 %131 %132
%138 = OpAccessChain %48 %36 %33 %136
OpStore %138 %137
%139 = OpBitwiseAnd %5 %59 %51
%140 = OpBitwiseAnd %5 %60 %52
%141 = OpBitwiseAnd %5 %61 %53
%142 = OpBitwiseOr %27 %65 %143
%144 = OpIMul %27 %34 %67
%145 = OpIAdd %27 %144 %143
%146 = OpCompositeConstruct %6 %139 %140 %141
%147 = OpAccessChain %48 %36 %33 %145
OpStore %147 %146
%148 = OpIMul %27 %34 %149
%150 = OpIMul %27 %34 %45
%160 = OpFunctionCall %27 %154 %150 %67
%162 = OpAccessChain %161 %44 %33 %160
%163 = OpLoad %5 %162
%165 = OpIAdd %27 %160 %39
%164 = OpAccessChain %161 %44 %33 %165
%166 = OpLoad %5 %164
%168 = OpCompositeConstruct %167 %163 %166
%169 = OpCompositeExtract %5 %168 0
%170 = OpCompositeExtract %5 %168 1
%171 = OpFunctionCall %27 %154 %34 %67
%172 = OpAccessChain %161 %41 %33 %171
OpStore %172 %169
%174 = OpIAdd %27 %171 %39
%173 = OpAccessChain %161 %41 %33 %174
OpStore %173 %170
%176 = OpIAdd %27 %171 %42
%175 = OpAccessChain %161 %41 %33 %176
OpStore %175 %53
OpReturn
OpFunctionEnd
%89 = OpFunction %5 None %86
%87 = OpFunctionParameter %5
%88 = OpFunctionParameter %5
%90 = OpLabel
%95 = OpIEqual %94 %88 %96
OpSelectionMerge %93 Flatten
OpBranchConditional %95 %93 %92
%92 = OpLabel
%97 = OpUDiv %5 %87 %88
OpBranch %93
%93 = OpLabel
%98 = OpPhi %5 %91 %90 %97 %92
OpReturnValue %98
OpFunctionEnd
%154 = OpFunction %27 None %151
%152 = OpFunctionParameter %27
%153 = OpFunctionParameter %27
%155 = OpLabel
%156 = OpUDiv %27 %157 %153
%158 = OpBitwiseAnd %27 %152 %156
OpReturnValue %158
OpFunctionEnd
#endif
