#version 460
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(set = 15, binding = 0, std430) restrict readonly buffer SSBO_Offsets
{
    uvec2 _m0[];
} _10;

layout(set = 0, binding = 0, std430) buffer SSBO
{
    uint64_t _m0[];
} _16[];

layout(set = 0, binding = 0, std430) restrict readonly buffer _18_21
{
    uint64_t _m0[];
} _21[];

layout(set = 0, binding = 0, std430) buffer _23_26
{
    uint64_t _m0[];
} _26[];

layout(set = 0, binding = 0, std430) restrict readonly buffer _28_31
{
    uint64_t _m0[];
} _31[];

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uvec2 _46 = _10._m0[subgroupBroadcastFirst(0u)] >> uvec2(3u);
    uvec2 _54 = _10._m0[subgroupBroadcastFirst(1u)] >> uvec2(3u);
    uvec2 _61 = _10._m0[subgroupBroadcastFirst(2u)] >> uvec2(3u);
    uvec2 _67 = _10._m0[subgroupBroadcastFirst(3u)] >> uvec2(3u);
    uint _69 = gl_GlobalInvocationID.x * 6u;
    uint _76 = (_69 < _54.y) ? (_69 + _54.x) : 536870908u;
    u64vec3 _88 = u64vec3(_21[1u]._m0[_76], _21[1u]._m0[_76 + 1u], _21[1u]._m0[_76 + 2u]);
    uint64_t _89 = _88.x;
    uint64_t _90 = _88.y;
    uint64_t _91 = _88.z;
    uint _94 = (gl_GlobalInvocationID.x * 6u) + 3u;
    uint _99 = (_94 < _54.y) ? (_94 + _54.x) : 536870908u;
    u64vec3 _108 = u64vec3(_21[1u]._m0[_99], _21[1u]._m0[_99 + 1u], _21[1u]._m0[_99 + 2u]);
    uint64_t _109 = _108.x;
    uint64_t _110 = _108.y;
    uint64_t _111 = _108.z;
    uint _115 = gl_GlobalInvocationID.x << 3u;
    uint _116 = gl_GlobalInvocationID.x * 24u;
    uint _122 = (_116 < _46.y) ? (_116 + _46.x) : 536870908u;
    _16[0u]._m0[_122] = _109 + _89;
    _16[0u]._m0[_122 + 1u] = _110 + _90;
    _16[0u]._m0[_122 + 2u] = _111 + _91;
    uint _133 = (gl_GlobalInvocationID.x * 24u) + 3u;
    uint _138 = (_133 < _46.y) ? (_133 + _46.x) : 536870908u;
    _16[0u]._m0[_138] = _89 - _109;
    _16[0u]._m0[_138 + 1u] = _90 - _110;
    _16[0u]._m0[_138 + 2u] = _91 - _111;
    uint _149 = (gl_GlobalInvocationID.x * 24u) + 6u;
    uint _154 = (_149 < _46.y) ? (_149 + _46.x) : 536870908u;
    _16[0u]._m0[_154] = _109 * _89;
    _16[0u]._m0[_154 + 1u] = _110 * _90;
    _16[0u]._m0[_154 + 2u] = _111 * _91;
    bool _162 = _109 != 0ul;
    bool _166 = _110 != 0ul;
    bool _170 = _111 != 0ul;
    uint _177 = (gl_GlobalInvocationID.x * 24u) + 9u;
    uint _182 = (_177 < _46.y) ? (_177 + _46.x) : 536870908u;
    _16[0u]._m0[_182] = _162 ? (_89 / (_162 ? _109 : 18446744073709551615ul)) : 18446744073709551615ul;
    _16[0u]._m0[_182 + 1u] = _166 ? (_90 / (_166 ? _110 : 18446744073709551615ul)) : 18446744073709551615ul;
    _16[0u]._m0[_182 + 2u] = _170 ? (_91 / (_170 ? _111 : 18446744073709551615ul)) : 18446744073709551615ul;
    uint64_t _188 = _109 & 63ul;
    uint64_t _190 = _110 & 63ul;
    uint64_t _191 = _111 & 63ul;
    uint _199 = (gl_GlobalInvocationID.x * 24u) + 12u;
    uint _204 = (_199 < _46.y) ? (_199 + _46.x) : 536870908u;
    _16[0u]._m0[_204] = _89 << _188;
    _16[0u]._m0[_204 + 1u] = _90 << _190;
    _16[0u]._m0[_204 + 2u] = _91 << _191;
    uint _217 = (gl_GlobalInvocationID.x * 24u) + 15u;
    uint _222 = (_217 < _46.y) ? (_217 + _46.x) : 536870908u;
    _16[0u]._m0[_222] = _89 >> _188;
    _16[0u]._m0[_222 + 1u] = _90 >> _190;
    _16[0u]._m0[_222 + 2u] = _91 >> _191;
    uint _234 = (gl_GlobalInvocationID.x * 24u) + 18u;
    uint _239 = (_234 < _46.y) ? (_234 + _46.x) : 536870908u;
    _16[0u]._m0[_239] = uint64_t(int64_t(_89) >> int64_t(_188));
    _16[0u]._m0[_239 + 1u] = uint64_t(int64_t(_90) >> int64_t(_190));
    _16[0u]._m0[_239 + 2u] = uint64_t(int64_t(_91) >> int64_t(_191));
    uint _252 = (gl_GlobalInvocationID.x * 24u) + 21u;
    uint _257 = (_252 < _46.y) ? (_252 + _46.x) : 536870908u;
    _16[0u]._m0[_257] = _109 & _89;
    _16[0u]._m0[_257 + 1u] = _110 & _90;
    _16[0u]._m0[_257 + 2u] = _111 & _91;
    uint _274 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 8u);
    uint _280 = (_274 < _67.y) ? (_274 + _67.x) : 536870908u;
    u64vec2 _287 = u64vec2(_31[3u]._m0[_280], _31[3u]._m0[_280 + 1u]);
    uint _290 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    uint _295 = (_290 < _61.y) ? (_290 + _61.x) : 536870908u;
    _26[2u]._m0[_295] = _287.x;
    _26[2u]._m0[_295 + 1u] = _287.y;
    _26[2u]._m0[_295 + 2u] = _91;
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 303
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability GroupNonUniformBallot
OpCapability RuntimeDescriptorArray
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %34
OpExecutionMode %3 LocalSize 128 1 1
OpName %3 "main"
OpName %8 "SSBO_Offsets"
OpName %13 "SSBO"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpName %28 "SSBO"
OpName %268 "ByteAddressMask"
OpName %266 "index"
OpName %267 "stride"
OpDecorate %7 ArrayStride 8
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 15
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %12 ArrayStride 8
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 0
OpDecorate %17 ArrayStride 8
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %21 DescriptorSet 0
OpDecorate %21 Binding 0
OpDecorate %21 NonWritable
OpDecorate %21 Restrict
OpDecorate %22 ArrayStride 8
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %26 DescriptorSet 0
OpDecorate %26 Binding 0
OpDecorate %27 ArrayStride 8
OpMemberDecorate %28 0 Offset 0
OpDecorate %28 Block
OpDecorate %31 DescriptorSet 0
OpDecorate %31 Binding 0
OpDecorate %31 NonWritable
OpDecorate %31 Restrict
OpDecorate %34 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 2
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeInt 64 0
%12 = OpTypeRuntimeArray %11
%13 = OpTypeStruct %12
%14 = OpTypeRuntimeArray %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeRuntimeArray %11
%18 = OpTypeStruct %17
%19 = OpTypeRuntimeArray %18
%20 = OpTypePointer StorageBuffer %19
%21 = OpVariable %20 StorageBuffer
%22 = OpTypeRuntimeArray %11
%23 = OpTypeStruct %22
%24 = OpTypeRuntimeArray %23
%25 = OpTypePointer StorageBuffer %24
%26 = OpVariable %25 StorageBuffer
%27 = OpTypeRuntimeArray %11
%28 = OpTypeStruct %27
%29 = OpTypeRuntimeArray %28
%30 = OpTypePointer StorageBuffer %29
%31 = OpVariable %30 StorageBuffer
%32 = OpTypeVector %5 3
%33 = OpTypePointer Input %32
%34 = OpVariable %33 Input
%35 = OpTypePointer Input %5
%37 = OpConstant %5 0
%39 = OpTypePointer StorageBuffer %13
%42 = OpConstant %5 3
%43 = OpTypePointer StorageBuffer %6
%47 = OpConstantComposite %6 %42 %42
%48 = OpTypePointer StorageBuffer %18
%50 = OpConstant %5 1
%55 = OpTypePointer StorageBuffer %23
%57 = OpConstant %5 2
%62 = OpTypePointer StorageBuffer %28
%70 = OpConstant %5 6
%74 = OpTypeBool
%77 = OpConstant %5 536870908
%78 = OpTypePointer StorageBuffer %11
%87 = OpTypeVector %11 3
%117 = OpConstant %5 24
%160 = OpConstant %11 0
%161 = OpConstant %11 18446744073709551615
%176 = OpConstant %5 9
%189 = OpConstant %11 63
%196 = OpConstant %5 4
%198 = OpConstant %5 12
%214 = OpConstant %5 5
%216 = OpConstant %5 15
%233 = OpConstant %5 18
%249 = OpConstant %5 7
%251 = OpConstant %5 21
%265 = OpTypeFunction %5 %5 %5
%271 = OpConstant %5 4294967295
%275 = OpConstant %5 8
%286 = OpTypeVector %11 2
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %301
%301 = OpLabel
%36 = OpAccessChain %35 %34 %37
%38 = OpLoad %5 %36
%40 = OpAccessChain %39 %16 %37
%41 = OpGroupNonUniformBroadcastFirst %5 %42 %37
%44 = OpAccessChain %43 %10 %37 %41
%45 = OpLoad %6 %44
%46 = OpShiftRightLogical %6 %45 %47
%49 = OpAccessChain %48 %21 %50
%51 = OpGroupNonUniformBroadcastFirst %5 %42 %50
%52 = OpAccessChain %43 %10 %37 %51
%53 = OpLoad %6 %52
%54 = OpShiftRightLogical %6 %53 %47
%56 = OpAccessChain %55 %26 %57
%58 = OpGroupNonUniformBroadcastFirst %5 %42 %57
%59 = OpAccessChain %43 %10 %37 %58
%60 = OpLoad %6 %59
%61 = OpShiftRightLogical %6 %60 %47
%63 = OpAccessChain %62 %31 %42
%64 = OpGroupNonUniformBroadcastFirst %5 %42 %42
%65 = OpAccessChain %43 %10 %37 %64
%66 = OpLoad %6 %65
%67 = OpShiftRightLogical %6 %66 %47
%68 = OpShiftLeftLogical %5 %38 %50
%69 = OpIMul %5 %38 %70
%71 = OpCompositeExtract %5 %54 0
%72 = OpCompositeExtract %5 %54 1
%73 = OpIAdd %5 %69 %71
%75 = OpULessThan %74 %69 %72
%76 = OpSelect %5 %75 %73 %77
%79 = OpAccessChain %78 %49 %37 %76
%80 = OpLoad %11 %79
%82 = OpIAdd %5 %76 %50
%81 = OpAccessChain %78 %49 %37 %82
%83 = OpLoad %11 %81
%85 = OpIAdd %5 %76 %57
%84 = OpAccessChain %78 %49 %37 %85
%86 = OpLoad %11 %84
%88 = OpCompositeConstruct %87 %80 %83 %86
%89 = OpCompositeExtract %11 %88 0
%90 = OpCompositeExtract %11 %88 1
%91 = OpCompositeExtract %11 %88 2
%92 = OpBitwiseOr %5 %68 %50
%93 = OpIMul %5 %38 %70
%94 = OpIAdd %5 %93 %42
%95 = OpCompositeExtract %5 %54 0
%96 = OpCompositeExtract %5 %54 1
%97 = OpIAdd %5 %94 %95
%98 = OpULessThan %74 %94 %96
%99 = OpSelect %5 %98 %97 %77
%100 = OpAccessChain %78 %49 %37 %99
%101 = OpLoad %11 %100
%103 = OpIAdd %5 %99 %50
%102 = OpAccessChain %78 %49 %37 %103
%104 = OpLoad %11 %102
%106 = OpIAdd %5 %99 %57
%105 = OpAccessChain %78 %49 %37 %106
%107 = OpLoad %11 %105
%108 = OpCompositeConstruct %87 %101 %104 %107
%109 = OpCompositeExtract %11 %108 0
%110 = OpCompositeExtract %11 %108 1
%111 = OpCompositeExtract %11 %108 2
%112 = OpIAdd %11 %109 %89
%113 = OpIAdd %11 %110 %90
%114 = OpIAdd %11 %111 %91
%115 = OpShiftLeftLogical %5 %38 %42
%116 = OpIMul %5 %38 %117
%118 = OpCompositeExtract %5 %46 0
%119 = OpCompositeExtract %5 %46 1
%120 = OpIAdd %5 %116 %118
%121 = OpULessThan %74 %116 %119
%122 = OpSelect %5 %121 %120 %77
%123 = OpAccessChain %78 %40 %37 %122
OpStore %123 %112
%125 = OpIAdd %5 %122 %50
%124 = OpAccessChain %78 %40 %37 %125
OpStore %124 %113
%127 = OpIAdd %5 %122 %57
%126 = OpAccessChain %78 %40 %37 %127
OpStore %126 %114
%128 = OpISub %11 %89 %109
%129 = OpISub %11 %90 %110
%130 = OpISub %11 %91 %111
%131 = OpBitwiseOr %5 %115 %50
%132 = OpIMul %5 %38 %117
%133 = OpIAdd %5 %132 %42
%134 = OpCompositeExtract %5 %46 0
%135 = OpCompositeExtract %5 %46 1
%136 = OpIAdd %5 %133 %134
%137 = OpULessThan %74 %133 %135
%138 = OpSelect %5 %137 %136 %77
%139 = OpAccessChain %78 %40 %37 %138
OpStore %139 %128
%141 = OpIAdd %5 %138 %50
%140 = OpAccessChain %78 %40 %37 %141
OpStore %140 %129
%143 = OpIAdd %5 %138 %57
%142 = OpAccessChain %78 %40 %37 %143
OpStore %142 %130
%144 = OpIMul %11 %109 %89
%145 = OpIMul %11 %110 %90
%146 = OpIMul %11 %111 %91
%147 = OpBitwiseOr %5 %115 %57
%148 = OpIMul %5 %38 %117
%149 = OpIAdd %5 %148 %70
%150 = OpCompositeExtract %5 %46 0
%151 = OpCompositeExtract %5 %46 1
%152 = OpIAdd %5 %149 %150
%153 = OpULessThan %74 %149 %151
%154 = OpSelect %5 %153 %152 %77
%155 = OpAccessChain %78 %40 %37 %154
OpStore %155 %144
%157 = OpIAdd %5 %154 %50
%156 = OpAccessChain %78 %40 %37 %157
OpStore %156 %145
%159 = OpIAdd %5 %154 %57
%158 = OpAccessChain %78 %40 %37 %159
OpStore %158 %146
%162 = OpINotEqual %74 %109 %160
%163 = OpSelect %11 %162 %109 %161
%164 = OpUDiv %11 %89 %163
%165 = OpSelect %11 %162 %164 %161
%166 = OpINotEqual %74 %110 %160
%167 = OpSelect %11 %166 %110 %161
%168 = OpUDiv %11 %90 %167
%169 = OpSelect %11 %166 %168 %161
%170 = OpINotEqual %74 %111 %160
%171 = OpSelect %11 %170 %111 %161
%172 = OpUDiv %11 %91 %171
%173 = OpSelect %11 %170 %172 %161
%174 = OpBitwiseOr %5 %115 %42
%175 = OpIMul %5 %38 %117
%177 = OpIAdd %5 %175 %176
%178 = OpCompositeExtract %5 %46 0
%179 = OpCompositeExtract %5 %46 1
%180 = OpIAdd %5 %177 %178
%181 = OpULessThan %74 %177 %179
%182 = OpSelect %5 %181 %180 %77
%183 = OpAccessChain %78 %40 %37 %182
OpStore %183 %165
%185 = OpIAdd %5 %182 %50
%184 = OpAccessChain %78 %40 %37 %185
OpStore %184 %169
%187 = OpIAdd %5 %182 %57
%186 = OpAccessChain %78 %40 %37 %187
OpStore %186 %173
%188 = OpBitwiseAnd %11 %109 %189
%190 = OpBitwiseAnd %11 %110 %189
%191 = OpBitwiseAnd %11 %111 %189
%192 = OpShiftLeftLogical %11 %89 %188
%193 = OpShiftLeftLogical %11 %90 %190
%194 = OpShiftLeftLogical %11 %91 %191
%195 = OpBitwiseOr %5 %115 %196
%197 = OpIMul %5 %38 %117
%199 = OpIAdd %5 %197 %198
%200 = OpCompositeExtract %5 %46 0
%201 = OpCompositeExtract %5 %46 1
%202 = OpIAdd %5 %199 %200
%203 = OpULessThan %74 %199 %201
%204 = OpSelect %5 %203 %202 %77
%205 = OpAccessChain %78 %40 %37 %204
OpStore %205 %192
%207 = OpIAdd %5 %204 %50
%206 = OpAccessChain %78 %40 %37 %207
OpStore %206 %193
%209 = OpIAdd %5 %204 %57
%208 = OpAccessChain %78 %40 %37 %209
OpStore %208 %194
%210 = OpShiftRightLogical %11 %89 %188
%211 = OpShiftRightLogical %11 %90 %190
%212 = OpShiftRightLogical %11 %91 %191
%213 = OpBitwiseOr %5 %115 %214
%215 = OpIMul %5 %38 %117
%217 = OpIAdd %5 %215 %216
%218 = OpCompositeExtract %5 %46 0
%219 = OpCompositeExtract %5 %46 1
%220 = OpIAdd %5 %217 %218
%221 = OpULessThan %74 %217 %219
%222 = OpSelect %5 %221 %220 %77
%223 = OpAccessChain %78 %40 %37 %222
OpStore %223 %210
%225 = OpIAdd %5 %222 %50
%224 = OpAccessChain %78 %40 %37 %225
OpStore %224 %211
%227 = OpIAdd %5 %222 %57
%226 = OpAccessChain %78 %40 %37 %227
OpStore %226 %212
%228 = OpShiftRightArithmetic %11 %89 %188
%229 = OpShiftRightArithmetic %11 %90 %190
%230 = OpShiftRightArithmetic %11 %91 %191
%231 = OpBitwiseOr %5 %115 %70
%232 = OpIMul %5 %38 %117
%234 = OpIAdd %5 %232 %233
%235 = OpCompositeExtract %5 %46 0
%236 = OpCompositeExtract %5 %46 1
%237 = OpIAdd %5 %234 %235
%238 = OpULessThan %74 %234 %236
%239 = OpSelect %5 %238 %237 %77
%240 = OpAccessChain %78 %40 %37 %239
OpStore %240 %228
%242 = OpIAdd %5 %239 %50
%241 = OpAccessChain %78 %40 %37 %242
OpStore %241 %229
%244 = OpIAdd %5 %239 %57
%243 = OpAccessChain %78 %40 %37 %244
OpStore %243 %230
%245 = OpBitwiseAnd %11 %109 %89
%246 = OpBitwiseAnd %11 %110 %90
%247 = OpBitwiseAnd %11 %111 %91
%248 = OpBitwiseOr %5 %115 %249
%250 = OpIMul %5 %38 %117
%252 = OpIAdd %5 %250 %251
%253 = OpCompositeExtract %5 %46 0
%254 = OpCompositeExtract %5 %46 1
%255 = OpIAdd %5 %252 %253
%256 = OpULessThan %74 %252 %254
%257 = OpSelect %5 %256 %255 %77
%258 = OpAccessChain %78 %40 %37 %257
OpStore %258 %245
%260 = OpIAdd %5 %257 %50
%259 = OpAccessChain %78 %40 %37 %260
OpStore %259 %246
%262 = OpIAdd %5 %257 %57
%261 = OpAccessChain %78 %40 %37 %262
OpStore %261 %247
%263 = OpIMul %5 %38 %117
%264 = OpIMul %5 %38 %42
%274 = OpFunctionCall %5 %268 %264 %275
%276 = OpCompositeExtract %5 %67 0
%277 = OpCompositeExtract %5 %67 1
%278 = OpIAdd %5 %274 %276
%279 = OpULessThan %74 %274 %277
%280 = OpSelect %5 %279 %278 %77
%281 = OpAccessChain %78 %63 %37 %280
%282 = OpLoad %11 %281
%284 = OpIAdd %5 %280 %50
%283 = OpAccessChain %78 %63 %37 %284
%285 = OpLoad %11 %283
%287 = OpCompositeConstruct %286 %282 %285
%288 = OpCompositeExtract %11 %287 0
%289 = OpCompositeExtract %11 %287 1
%290 = OpFunctionCall %5 %268 %38 %275
%291 = OpCompositeExtract %5 %61 0
%292 = OpCompositeExtract %5 %61 1
%293 = OpIAdd %5 %290 %291
%294 = OpULessThan %74 %290 %292
%295 = OpSelect %5 %294 %293 %77
%296 = OpAccessChain %78 %56 %37 %295
OpStore %296 %288
%298 = OpIAdd %5 %295 %50
%297 = OpAccessChain %78 %56 %37 %298
OpStore %297 %289
%300 = OpIAdd %5 %295 %57
%299 = OpAccessChain %78 %56 %37 %300
OpStore %299 %91
OpReturn
OpFunctionEnd
%268 = OpFunction %5 None %265
%266 = OpFunctionParameter %5
%267 = OpFunctionParameter %5
%269 = OpLabel
%270 = OpUDiv %5 %271 %267
%272 = OpBitwiseAnd %5 %266 %270
OpReturnValue %272
OpFunctionEnd
#endif
