#version 460
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, scalar) buffer SSBO
{
    u64vec3 _m0[];
} _11[];

layout(set = 0, binding = 0, scalar) restrict readonly buffer _13_16
{
    u64vec3 _m0[];
} _16[];

layout(set = 0, binding = 0, std430) buffer _18_21
{
    uint64_t _m0[];
} _21[];

layout(set = 0, binding = 0, std430) restrict readonly buffer _23_26
{
    uint64_t _m0[];
} _26[];

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _47 = gl_GlobalInvocationID.x * 2u;
    uint _56 = (gl_GlobalInvocationID.x * 2u) + 1u;
    uint _65 = gl_GlobalInvocationID.x << 3u;
    _11[0u]._m0[gl_GlobalInvocationID.x * 8u] = u64vec3(_16[1u]._m0[_56].x + _16[1u]._m0[_47].x, _16[1u]._m0[_56].y + _16[1u]._m0[_47].y, _16[1u]._m0[_56].z + _16[1u]._m0[_47].z);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 1u] = u64vec3(_16[1u]._m0[_47].x - _16[1u]._m0[_56].x, _16[1u]._m0[_47].y - _16[1u]._m0[_56].y, _16[1u]._m0[_47].z - _16[1u]._m0[_56].z);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 2u] = u64vec3(_16[1u]._m0[_56].x * _16[1u]._m0[_47].x, _16[1u]._m0[_56].y * _16[1u]._m0[_47].y, _16[1u]._m0[_56].z * _16[1u]._m0[_47].z);
    bool _89 = _16[1u]._m0[_56].x != 0ul;
    bool _93 = _16[1u]._m0[_56].y != 0ul;
    bool _97 = _16[1u]._m0[_56].z != 0ul;
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 3u] = u64vec3(_89 ? (_16[1u]._m0[_47].x / (_89 ? _16[1u]._m0[_56].x : 18446744073709551615ul)) : 18446744073709551615ul, _93 ? (_16[1u]._m0[_47].y / (_93 ? _16[1u]._m0[_56].y : 18446744073709551615ul)) : 18446744073709551615ul, _97 ? (_16[1u]._m0[_47].z / (_97 ? _16[1u]._m0[_56].z : 18446744073709551615ul)) : 18446744073709551615ul);
    uint64_t _106 = _16[1u]._m0[_56].x & 63ul;
    uint64_t _108 = _16[1u]._m0[_56].y & 63ul;
    uint64_t _109 = _16[1u]._m0[_56].z & 63ul;
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 4u] = u64vec3(_16[1u]._m0[_47].x << _106, _16[1u]._m0[_47].y << _108, _16[1u]._m0[_47].z << _109);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 5u] = u64vec3(_16[1u]._m0[_47].x >> _106, _16[1u]._m0[_47].y >> _108, _16[1u]._m0[_47].z >> _109);
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 6u] = u64vec3(uint64_t(int64_t(_16[1u]._m0[_47].x) >> int64_t(_106)), uint64_t(int64_t(_16[1u]._m0[_47].y) >> int64_t(_108)), uint64_t(int64_t(_16[1u]._m0[_47].z) >> int64_t(_109)));
    _11[0u]._m0[(gl_GlobalInvocationID.x * 8u) + 7u] = u64vec3(_16[1u]._m0[_56].x & _16[1u]._m0[_47].x, _16[1u]._m0[_56].y & _16[1u]._m0[_47].y, _16[1u]._m0[_56].z & _16[1u]._m0[_47].z);
    uint _158 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 8u);
    u64vec2 _166 = u64vec2(_26[3u]._m0[_158], _26[3u]._m0[_158 + 1u]);
    uint _169 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    _21[2u]._m0[_169] = _166.x;
    _21[2u]._m0[_169 + 1u] = _166.y;
    _21[2u]._m0[_169 + 2u] = _16[1u]._m0[_47].z;
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 177
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability RuntimeDescriptorArray
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %30
OpExecutionMode %3 LocalSize 128 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %13 "SSBO"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpName %152 "ByteAddressMask"
OpName %150 "index"
OpName %151 "stride"
OpDecorate %7 ArrayStride 24
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %12 ArrayStride 24
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 0
OpDecorate %16 NonWritable
OpDecorate %16 Restrict
OpDecorate %17 ArrayStride 8
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %21 DescriptorSet 0
OpDecorate %21 Binding 0
OpDecorate %22 ArrayStride 8
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %26 DescriptorSet 0
OpDecorate %26 Binding 0
OpDecorate %26 NonWritable
OpDecorate %26 Restrict
OpDecorate %30 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 64 0
%6 = OpTypeVector %5 3
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypeRuntimeArray %8
%10 = OpTypePointer StorageBuffer %9
%11 = OpVariable %10 StorageBuffer
%12 = OpTypeRuntimeArray %6
%13 = OpTypeStruct %12
%14 = OpTypeRuntimeArray %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeRuntimeArray %5
%18 = OpTypeStruct %17
%19 = OpTypeRuntimeArray %18
%20 = OpTypePointer StorageBuffer %19
%21 = OpVariable %20 StorageBuffer
%22 = OpTypeRuntimeArray %5
%23 = OpTypeStruct %22
%24 = OpTypeRuntimeArray %23
%25 = OpTypePointer StorageBuffer %24
%26 = OpVariable %25 StorageBuffer
%27 = OpTypeInt 32 0
%28 = OpTypeVector %27 3
%29 = OpTypePointer Input %28
%30 = OpVariable %29 Input
%31 = OpTypePointer Input %27
%33 = OpConstant %27 0
%35 = OpTypePointer StorageBuffer %8
%37 = OpTypePointer StorageBuffer %13
%39 = OpConstant %27 1
%40 = OpTypePointer StorageBuffer %18
%42 = OpConstant %27 2
%43 = OpTypePointer StorageBuffer %23
%45 = OpConstant %27 3
%48 = OpTypePointer StorageBuffer %6
%67 = OpConstant %27 8
%86 = OpConstant %5 0
%87 = OpConstant %5 18446744073709551615
%88 = OpTypeBool
%107 = OpConstant %5 63
%114 = OpConstant %27 4
%123 = OpConstant %27 5
%132 = OpConstant %27 6
%141 = OpConstant %27 7
%147 = OpConstant %27 24
%149 = OpTypeFunction %27 %27 %27
%155 = OpConstant %27 4294967295
%159 = OpTypePointer StorageBuffer %5
%165 = OpTypeVector %5 2
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %175
%175 = OpLabel
%32 = OpAccessChain %31 %30 %33
%34 = OpLoad %27 %32
%36 = OpAccessChain %35 %11 %33
%38 = OpAccessChain %37 %16 %39
%41 = OpAccessChain %40 %21 %42
%44 = OpAccessChain %43 %26 %45
%46 = OpShiftLeftLogical %27 %34 %39
%47 = OpIMul %27 %34 %42
%49 = OpAccessChain %48 %38 %33 %47
%50 = OpLoad %6 %49
%51 = OpCompositeExtract %5 %50 0
%52 = OpCompositeExtract %5 %50 1
%53 = OpCompositeExtract %5 %50 2
%54 = OpBitwiseOr %27 %46 %39
%55 = OpIMul %27 %34 %42
%56 = OpIAdd %27 %55 %39
%57 = OpAccessChain %48 %38 %33 %56
%58 = OpLoad %6 %57
%59 = OpCompositeExtract %5 %58 0
%60 = OpCompositeExtract %5 %58 1
%61 = OpCompositeExtract %5 %58 2
%62 = OpIAdd %5 %59 %51
%63 = OpIAdd %5 %60 %52
%64 = OpIAdd %5 %61 %53
%65 = OpShiftLeftLogical %27 %34 %45
%66 = OpIMul %27 %34 %67
%68 = OpCompositeConstruct %6 %62 %63 %64
%69 = OpAccessChain %48 %36 %33 %66
OpStore %69 %68
%70 = OpISub %5 %51 %59
%71 = OpISub %5 %52 %60
%72 = OpISub %5 %53 %61
%73 = OpBitwiseOr %27 %65 %39
%74 = OpIMul %27 %34 %67
%75 = OpIAdd %27 %74 %39
%76 = OpCompositeConstruct %6 %70 %71 %72
%77 = OpAccessChain %48 %36 %33 %75
OpStore %77 %76
%78 = OpIMul %5 %59 %51
%79 = OpIMul %5 %60 %52
%80 = OpIMul %5 %61 %53
%81 = OpBitwiseOr %27 %65 %42
%82 = OpIMul %27 %34 %67
%83 = OpIAdd %27 %82 %42
%84 = OpCompositeConstruct %6 %78 %79 %80
%85 = OpAccessChain %48 %36 %33 %83
OpStore %85 %84
%89 = OpINotEqual %88 %59 %86
%90 = OpSelect %5 %89 %59 %87
%91 = OpUDiv %5 %51 %90
%92 = OpSelect %5 %89 %91 %87
%93 = OpINotEqual %88 %60 %86
%94 = OpSelect %5 %93 %60 %87
%95 = OpUDiv %5 %52 %94
%96 = OpSelect %5 %93 %95 %87
%97 = OpINotEqual %88 %61 %86
%98 = OpSelect %5 %97 %61 %87
%99 = OpUDiv %5 %53 %98
%100 = OpSelect %5 %97 %99 %87
%101 = OpBitwiseOr %27 %65 %45
%102 = OpIMul %27 %34 %67
%103 = OpIAdd %27 %102 %45
%104 = OpCompositeConstruct %6 %92 %96 %100
%105 = OpAccessChain %48 %36 %33 %103
OpStore %105 %104
%106 = OpBitwiseAnd %5 %59 %107
%108 = OpBitwiseAnd %5 %60 %107
%109 = OpBitwiseAnd %5 %61 %107
%110 = OpShiftLeftLogical %5 %51 %106
%111 = OpShiftLeftLogical %5 %52 %108
%112 = OpShiftLeftLogical %5 %53 %109
%113 = OpBitwiseOr %27 %65 %114
%115 = OpIMul %27 %34 %67
%116 = OpIAdd %27 %115 %114
%117 = OpCompositeConstruct %6 %110 %111 %112
%118 = OpAccessChain %48 %36 %33 %116
OpStore %118 %117
%119 = OpShiftRightLogical %5 %51 %106
%120 = OpShiftRightLogical %5 %52 %108
%121 = OpShiftRightLogical %5 %53 %109
%122 = OpBitwiseOr %27 %65 %123
%124 = OpIMul %27 %34 %67
%125 = OpIAdd %27 %124 %123
%126 = OpCompositeConstruct %6 %119 %120 %121
%127 = OpAccessChain %48 %36 %33 %125
OpStore %127 %126
%128 = OpShiftRightArithmetic %5 %51 %106
%129 = OpShiftRightArithmetic %5 %52 %108
%130 = OpShiftRightArithmetic %5 %53 %109
%131 = OpBitwiseOr %27 %65 %132
%133 = OpIMul %27 %34 %67
%134 = OpIAdd %27 %133 %132
%135 = OpCompositeConstruct %6 %128 %129 %130
%136 = OpAccessChain %48 %36 %33 %134
OpStore %136 %135
%137 = OpBitwiseAnd %5 %59 %51
%138 = OpBitwiseAnd %5 %60 %52
%139 = OpBitwiseAnd %5 %61 %53
%140 = OpBitwiseOr %27 %65 %141
%142 = OpIMul %27 %34 %67
%143 = OpIAdd %27 %142 %141
%144 = OpCompositeConstruct %6 %137 %138 %139
%145 = OpAccessChain %48 %36 %33 %143
OpStore %145 %144
%146 = OpIMul %27 %34 %147
%148 = OpIMul %27 %34 %45
%158 = OpFunctionCall %27 %152 %148 %67
%160 = OpAccessChain %159 %44 %33 %158
%161 = OpLoad %5 %160
%163 = OpIAdd %27 %158 %39
%162 = OpAccessChain %159 %44 %33 %163
%164 = OpLoad %5 %162
%166 = OpCompositeConstruct %165 %161 %164
%167 = OpCompositeExtract %5 %166 0
%168 = OpCompositeExtract %5 %166 1
%169 = OpFunctionCall %27 %152 %34 %67
%170 = OpAccessChain %159 %41 %33 %169
OpStore %170 %167
%172 = OpIAdd %27 %169 %39
%171 = OpAccessChain %159 %41 %33 %172
OpStore %171 %168
%174 = OpIAdd %27 %169 %42
%173 = OpAccessChain %159 %41 %33 %174
OpStore %173 %53
OpReturn
OpFunctionEnd
%152 = OpFunction %27 None %149
%150 = OpFunctionParameter %27
%151 = OpFunctionParameter %27
%153 = OpLabel
%154 = OpUDiv %27 %155 %151
%156 = OpBitwiseAnd %27 %150 %154
OpReturnValue %156
OpFunctionEnd
#endif
