; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 61
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability UntypedPointersKHR
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_untyped_pointers"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%15 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %32 "ssbo"
OpName %44 "ssbo"
OpName %52 "ssbo"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 1
OpDecorate %13 NonReadable
OpDecorate %31 ArrayStride 4
OpDecorate %32 Block
OpMemberDecorate %32 0 Offset 0
OpDecorate %43 ArrayStride 4
OpDecorate %44 Block
OpMemberDecorate %44 0 Offset 0
OpDecorate %51 ArrayStride 4
OpDecorate %52 Block
OpMemberDecorate %52 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%16 = OpTypeFloat 32
%17 = OpConstant %16 46.5
%19 = OpConstant %16 0
%20 = OpTypeVector %16 2
%23 = OpConstant %5 16
%24 = OpConstant %16 45.5
%28 = OpTypeFloat 16
%29 = OpTypeVector %28 2
%30 = OpConstant %5 4
%31 = OpTypeRuntimeArray %29
%32 = OpTypeStruct %31
%33 = OpTypeUntypedPointerKHR StorageBuffer
%35 = OpConstant %5 0
%38 = OpConstant %5 1
%40 = OpConstant %5 100
%41 = OpTypePointer StorageBuffer %5
%43 = OpTypeRuntimeArray %29
%44 = OpTypeStruct %43
%49 = OpConstant %5 101
%51 = OpTypeRuntimeArray %29
%52 = OpTypeStruct %51
%57 = OpConstant %5 102
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %59
%59 = OpLabel
%21 = OpCompositeConstruct %20 %17 %19
%18 = OpExtInst %5 %15 PackHalf2x16 %21
%22 = OpShiftLeftLogical %5 %18 %23
%26 = OpCompositeConstruct %20 %24 %19
%25 = OpExtInst %5 %15 PackHalf2x16 %26
%27 = OpBitwiseOr %5 %22 %25
%34 = OpUntypedAccessChainKHR %33 %32 %9 %35 %30
%36 = OpBitcast %29 %27
%37 = OpAtomicFAddEXT %29 %34 %38 %35 %36
%39 = OpBitcast %5 %37
%42 = OpAccessChain %41 %13 %35 %40
OpStore %42 %39
%45 = OpUntypedAccessChainKHR %33 %44 %9 %35 %30
%46 = OpBitcast %29 %27
%47 = OpAtomicFMinEXT %29 %45 %38 %35 %46
%48 = OpBitcast %5 %47
%50 = OpAccessChain %41 %13 %35 %49
OpStore %50 %48
%53 = OpUntypedAccessChainKHR %33 %52 %9 %35 %30
%54 = OpBitcast %29 %27
%55 = OpAtomicFMaxEXT %29 %53 %38 %35 %54
%56 = OpBitcast %5 %55
%58 = OpAccessChain %41 %13 %35 %57
OpStore %58 %56
OpReturn
OpFunctionEnd

