#version 460
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_atomic_float : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 4, std430) writeonly buffer SSBO
{
    uint _m0[];
} _20;

layout(set = 0, binding = 5, std430) writeonly buffer _23_25
{
    uvec2 _m0[];
} _25;

layout(set = 0, binding = 0, rg16f) uniform image1D _8;
layout(set = 0, binding = 1, rg16f) uniform image2D _11;
layout(set = 0, binding = 2, rg16f) uniform image3D _14;
layout(set = 0, binding = 3, rg16f) uniform image3D _15;

void main()
{
    uint _42 = (packHalf2x16(vec2(46.5, 0.0)) << 16u) | packHalf2x16(vec2(45.5, 0.0));
    f16vec2 _50 = imageAtomicAdd(_8, int(5u), unpackFloat2x16(_42));
    _20._m0[101u] = packFloat2x16(_50);
    f16vec2 _61 = imageAtomicAdd(_11, ivec2(uvec2(6u, 7u)), unpackFloat2x16(_42));
    _20._m0[102u] = packFloat2x16(_61);
    f16vec2 _72 = imageAtomicAdd(_14, ivec3(uvec3(8u, 9u, 10u)), unpackFloat2x16(_42));
    _20._m0[103u] = packFloat2x16(_72);
    f16vec2 _98 = imageAtomicAdd(_15, ivec3(uvec3(22u, 12u, 13u)), unpackFloat2x16((packHalf2x16(vec2(79.5, 0.0)) << 16u) | packHalf2x16(vec2(78.5, 0.0))));
    f16vec2 _104 = imageAtomicAdd(_15, ivec3(uvec3(23u, 12u, 13u)), unpackFloat2x16((packHalf2x16(vec2(81.5, 0.0)) << 16u) | packHalf2x16(vec2(80.5, 0.0))));
    _25._m0[105u] = uvec2(packFloat2x16(_98), packFloat2x16(_104));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 112
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Image1D
OpCapability StorageImageExtendedFormats
OpCapability DenormPreserve
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%31 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %18 "SSBO"
OpName %23 "SSBO"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %8 NonReadable
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 1
OpDecorate %11 NonReadable
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 2
OpDecorate %14 NonReadable
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 3
OpDecorate %15 NonReadable
OpDecorate %17 ArrayStride 4
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 4
OpDecorate %20 NonReadable
OpDecorate %22 ArrayStride 8
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 5
OpDecorate %25 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeFloat 32
%6 = OpTypeImage %5 1D 0 0 0 2 Rg16f
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeImage %5 2D 0 0 0 2 Rg16f
%10 = OpTypePointer UniformConstant %9
%11 = OpVariable %10 UniformConstant
%12 = OpTypeImage %5 3D 0 0 0 2 Rg16f
%13 = OpTypePointer UniformConstant %12
%14 = OpVariable %13 UniformConstant
%15 = OpVariable %13 UniformConstant
%16 = OpTypeInt 32 0
%17 = OpTypeRuntimeArray %16
%18 = OpTypeStruct %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeVector %16 2
%22 = OpTypeRuntimeArray %21
%23 = OpTypeStruct %22
%24 = OpTypePointer StorageBuffer %23
%25 = OpVariable %24 StorageBuffer
%32 = OpConstant %5 46.5
%34 = OpConstant %5 0
%35 = OpTypeVector %5 2
%38 = OpConstant %16 16
%39 = OpConstant %5 45.5
%43 = OpTypeFloat 16
%44 = OpTypeVector %43 2
%45 = OpConstant %16 5
%46 = OpTypePointer Image %44
%48 = OpConstant %16 0
%51 = OpConstant %16 1
%53 = OpConstant %16 101
%54 = OpTypePointer StorageBuffer %16
%56 = OpConstant %16 6
%57 = OpConstant %16 7
%63 = OpConstant %16 102
%65 = OpConstant %16 8
%66 = OpConstant %16 9
%67 = OpConstant %16 10
%68 = OpTypeVector %16 3
%74 = OpConstant %16 103
%76 = OpConstant %5 79.5
%80 = OpConstant %5 78.5
%84 = OpConstant %5 81.5
%88 = OpConstant %5 80.5
%92 = OpConstant %16 22
%93 = OpConstant %16 12
%94 = OpConstant %16 13
%100 = OpConstant %16 23
%106 = OpConstant %16 105
%108 = OpTypePointer StorageBuffer %21
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %110
%110 = OpLabel
%26 = OpLoad %12 %15
%27 = OpLoad %12 %14
%28 = OpLoad %9 %11
%29 = OpLoad %6 %8
%36 = OpCompositeConstruct %35 %32 %34
%33 = OpExtInst %16 %31 PackHalf2x16 %36
%37 = OpShiftLeftLogical %16 %33 %38
%41 = OpCompositeConstruct %35 %39 %34
%40 = OpExtInst %16 %31 PackHalf2x16 %41
%42 = OpBitwiseOr %16 %37 %40
%47 = OpImageTexelPointer %46 %8 %45 %48
%49 = OpBitcast %44 %42
%50 = OpAtomicFAddEXT %44 %47 %51 %48 %49
%52 = OpBitcast %16 %50
%55 = OpAccessChain %54 %20 %48 %53
OpStore %55 %52
%58 = OpCompositeConstruct %21 %56 %57
%59 = OpImageTexelPointer %46 %11 %58 %48
%60 = OpBitcast %44 %42
%61 = OpAtomicFAddEXT %44 %59 %51 %48 %60
%62 = OpBitcast %16 %61
%64 = OpAccessChain %54 %20 %48 %63
OpStore %64 %62
%69 = OpCompositeConstruct %68 %65 %66 %67
%70 = OpImageTexelPointer %46 %14 %69 %48
%71 = OpBitcast %44 %42
%72 = OpAtomicFAddEXT %44 %70 %51 %48 %71
%73 = OpBitcast %16 %72
%75 = OpAccessChain %54 %20 %48 %74
OpStore %75 %73
%78 = OpCompositeConstruct %35 %76 %34
%77 = OpExtInst %16 %31 PackHalf2x16 %78
%79 = OpShiftLeftLogical %16 %77 %38
%82 = OpCompositeConstruct %35 %80 %34
%81 = OpExtInst %16 %31 PackHalf2x16 %82
%83 = OpBitwiseOr %16 %79 %81
%86 = OpCompositeConstruct %35 %84 %34
%85 = OpExtInst %16 %31 PackHalf2x16 %86
%87 = OpShiftLeftLogical %16 %85 %38
%90 = OpCompositeConstruct %35 %88 %34
%89 = OpExtInst %16 %31 PackHalf2x16 %90
%91 = OpBitwiseOr %16 %87 %89
%95 = OpCompositeConstruct %68 %92 %93 %94
%96 = OpImageTexelPointer %46 %15 %95 %48
%97 = OpBitcast %44 %83
%98 = OpAtomicFAddEXT %44 %96 %51 %48 %97
%99 = OpBitcast %16 %98
%101 = OpCompositeConstruct %68 %100 %93 %94
%102 = OpImageTexelPointer %46 %15 %101 %48
%103 = OpBitcast %44 %91
%104 = OpAtomicFAddEXT %44 %102 %51 %48 %103
%105 = OpBitcast %16 %104
%107 = OpCompositeConstruct %21 %99 %105
%109 = OpAccessChain %108 %25 %48 %106
OpStore %109 %107
OpReturn
OpFunctionEnd
#endif
