; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 65
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability UntypedPointersKHR
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_untyped_pointers"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%15 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %32 "ssbo"
OpName %46 "ssbo"
OpName %55 "ssbo"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 1
OpDecorate %13 NonReadable
OpDecorate %31 ArrayStride 4
OpDecorate %32 Block
OpMemberDecorate %32 0 Offset 0
OpDecorate %45 ArrayStride 4
OpDecorate %46 Block
OpMemberDecorate %46 0 Offset 0
OpDecorate %54 ArrayStride 4
OpDecorate %55 Block
OpMemberDecorate %55 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%16 = OpTypeFloat 32
%17 = OpConstant %16 46.5
%19 = OpConstant %16 0
%20 = OpTypeVector %16 2
%23 = OpConstant %5 16
%24 = OpConstant %16 45.5
%28 = OpTypeFloat 16
%29 = OpTypeVector %28 2
%30 = OpConstant %5 8
%31 = OpTypeRuntimeArray %29
%32 = OpTypeStruct %31
%34 = OpConstant %5 4
%35 = OpTypeUntypedPointerKHR StorageBuffer
%37 = OpConstant %5 0
%40 = OpConstant %5 1
%42 = OpConstant %5 100
%43 = OpTypePointer StorageBuffer %5
%45 = OpTypeRuntimeArray %29
%46 = OpTypeStruct %45
%52 = OpConstant %5 101
%54 = OpTypeRuntimeArray %29
%55 = OpTypeStruct %54
%61 = OpConstant %5 102
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %63
%63 = OpLabel
%21 = OpCompositeConstruct %20 %17 %19
%18 = OpExtInst %5 %15 PackHalf2x16 %21
%22 = OpShiftLeftLogical %5 %18 %23
%26 = OpCompositeConstruct %20 %24 %19
%25 = OpExtInst %5 %15 PackHalf2x16 %26
%27 = OpBitwiseOr %5 %22 %25
%33 = OpUDiv %5 %30 %34
%36 = OpUntypedAccessChainKHR %35 %32 %9 %37 %33
%38 = OpBitcast %29 %27
%39 = OpAtomicFAddEXT %29 %36 %40 %37 %38
%41 = OpBitcast %5 %39
%44 = OpAccessChain %43 %13 %37 %42
OpStore %44 %41
%47 = OpUDiv %5 %30 %34
%48 = OpUntypedAccessChainKHR %35 %46 %9 %37 %47
%49 = OpBitcast %29 %27
%50 = OpAtomicFMinEXT %29 %48 %40 %37 %49
%51 = OpBitcast %5 %50
%53 = OpAccessChain %43 %13 %37 %52
OpStore %53 %51
%56 = OpUDiv %5 %30 %34
%57 = OpUntypedAccessChainKHR %35 %55 %9 %37 %56
%58 = OpBitcast %29 %27
%59 = OpAtomicFMaxEXT %29 %57 %40 %37 %58
%60 = OpBitcast %5 %59
%62 = OpAccessChain %43 %13 %37 %61
OpStore %62 %60
OpReturn
OpFunctionEnd

