; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 64
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability UntypedPointersKHR
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_untyped_pointers"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%15 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %31 "e"
OpName %44 "e"
OpName %53 "e"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 1
OpDecorate %13 NonReadable
OpMemberDecorate %31 0 Offset 0
OpMemberDecorate %44 0 Offset 0
OpMemberDecorate %53 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%16 = OpTypeFloat 32
%17 = OpConstant %16 46.5
%19 = OpConstant %16 0
%20 = OpTypeVector %16 2
%23 = OpConstant %5 16
%24 = OpConstant %16 45.5
%28 = OpTypeFloat 16
%29 = OpTypeVector %28 2
%30 = OpConstant %5 4
%31 = OpTypeStruct %20
%32 = OpTypeUntypedPointerKHR StorageBuffer
%34 = OpConstant %5 0
%38 = OpConstant %5 1
%41 = OpConstant %5 100
%42 = OpTypePointer StorageBuffer %5
%44 = OpTypeStruct %20
%51 = OpConstant %5 101
%53 = OpTypeStruct %20
%60 = OpConstant %5 102
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %62
%62 = OpLabel
%21 = OpCompositeConstruct %20 %17 %19
%18 = OpExtInst %5 %15 PackHalf2x16 %21
%22 = OpShiftLeftLogical %5 %18 %23
%26 = OpCompositeConstruct %20 %24 %19
%25 = OpExtInst %5 %15 PackHalf2x16 %26
%27 = OpBitwiseOr %5 %22 %25
%33 = OpUntypedAccessChainKHR %32 %31 %9 %34 %30
%35 = OpExtInst %20 %15 UnpackHalf2x16 %27
%36 = OpFConvert %29 %35
%37 = OpAtomicFAddEXT %29 %33 %38 %34 %36
%39 = OpFConvert %20 %37
%40 = OpExtInst %5 %15 PackHalf2x16 %39
%43 = OpAccessChain %42 %13 %34 %41
OpStore %43 %40
%45 = OpUntypedAccessChainKHR %32 %44 %9 %34 %30
%46 = OpExtInst %20 %15 UnpackHalf2x16 %27
%47 = OpFConvert %29 %46
%48 = OpAtomicFMinEXT %29 %45 %38 %34 %47
%49 = OpFConvert %20 %48
%50 = OpExtInst %5 %15 PackHalf2x16 %49
%52 = OpAccessChain %42 %13 %34 %51
OpStore %52 %50
%54 = OpUntypedAccessChainKHR %32 %53 %9 %34 %30
%55 = OpExtInst %20 %15 UnpackHalf2x16 %27
%56 = OpFConvert %29 %55
%57 = OpAtomicFMaxEXT %29 %54 %38 %34 %56
%58 = OpFConvert %20 %57
%59 = OpExtInst %5 %15 PackHalf2x16 %58
%61 = OpAccessChain %42 %13 %34 %60
OpStore %61 %59
OpReturn
OpFunctionEnd

