; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 43
; Schema: 0
OpCapability Shader
OpCapability UntypedPointersKHR
OpCapability AtomicFloat32AddEXT
OpExtension "SPV_EXT_shader_atomic_float_add"
OpExtension "SPV_KHR_untyped_pointers"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %17
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %29 "ssbo"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 1
OpDecorate %13 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
OpDecorate %28 ArrayStride 4
OpDecorate %29 Block
OpMemberDecorate %29 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%22 = OpTypeFloat 32
%25 = OpConstant %22 45.5
%27 = OpConstant %5 4
%28 = OpTypeRuntimeArray %22
%29 = OpTypeStruct %28
%30 = OpTypeUntypedPointerKHR StorageBuffer
%34 = OpConstant %5 1
%37 = OpConstant %5 100
%39 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %41
%41 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%23 = OpConvertUToF %22 %21
%24 = OpFAdd %22 %23 %25
%26 = OpBitcast %5 %24
%31 = OpUntypedAccessChainKHR %30 %29 %9 %20 %27
%32 = OpBitcast %22 %26
%33 = OpAtomicFAddEXT %22 %31 %34 %20 %32
%35 = OpBitcast %5 %33
%36 = OpBitcast %22 %35
%38 = OpBitcast %5 %36
%40 = OpAccessChain %39 %13 %20 %37
OpStore %40 %38
OpReturn
OpFunctionEnd

