; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 45
; Schema: 0
OpCapability Shader
OpCapability UntypedPointersKHR
OpCapability AtomicFloat32AddEXT
OpExtension "SPV_EXT_shader_atomic_float_add"
OpExtension "SPV_KHR_untyped_pointers"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %17
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %29 "ssbo"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonReadable
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 1
OpDecorate %13 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
OpDecorate %28 ArrayStride 4
OpDecorate %29 Block
OpMemberDecorate %29 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%22 = OpTypeFloat 32
%25 = OpConstant %22 45.5
%27 = OpConstant %5 8
%28 = OpTypeRuntimeArray %22
%29 = OpTypeStruct %28
%31 = OpConstant %5 4
%32 = OpTypeUntypedPointerKHR StorageBuffer
%36 = OpConstant %5 1
%39 = OpConstant %5 100
%41 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %43
%43 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%23 = OpConvertUToF %22 %21
%24 = OpFAdd %22 %23 %25
%26 = OpBitcast %5 %24
%30 = OpUDiv %5 %27 %31
%33 = OpUntypedAccessChainKHR %32 %29 %9 %20 %30
%34 = OpBitcast %22 %26
%35 = OpAtomicFAddEXT %22 %33 %36 %20 %34
%37 = OpBitcast %5 %35
%38 = OpBitcast %22 %37
%40 = OpBitcast %5 %38
%42 = OpAccessChain %41 %13 %20 %39
OpStore %42 %40
OpReturn
OpFunctionEnd

