#version 460
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_shader_image_int64 : require
#extension GL_EXT_shader_atomic_int64 : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 3, std430) writeonly buffer SSBO
{
    uvec2 _m0[];
} _20;

layout(set = 0, binding = 0, r64ui) uniform u64image1D _8;
layout(set = 0, binding = 1, r64ui) uniform u64image2D _11;
layout(set = 0, binding = 2, r64ui) uniform u64image3D _14;

void main()
{
    uint64_t _32 = uint64_t(gl_GlobalInvocationID.x);
    uint64_t _33 = _32 + 1ul;
    uint _35 = uint(_33);
    uint _38 = uint(_33 >> 32ul);
    uint64_t _44 = imageAtomicAdd(_8, int(5u), packUint2x32(uvec2(_35, _38)));
    _20._m0[101u] = uvec2(unpackUint2x32(_44));
    uint64_t _59 = imageAtomicAdd(_11, ivec2(uvec2(6u, 7u)), packUint2x32(uvec2(_35, _38)));
    _20._m0[102u] = uvec2(unpackUint2x32(_59));
    uint64_t _73 = imageAtomicAdd(_14, ivec3(uvec3(8u, 9u, 10u)), packUint2x32(uvec2(_35, _38)));
    _20._m0[103u] = uvec2(unpackUint2x32(_73));
    uint64_t _80 = _32 + 2ul;
    uint64_t _88 = imageAtomicCompSwap(_8, int(8u), packUint2x32(uvec2(uint(_80), uint(_80 >> 32ul))), packUint2x32(uvec2(_35, _38)));
    _20._m0[104u] = uvec2(unpackUint2x32(_88));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 99
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability Int64Atomics
OpCapability Image1D
OpCapability StorageImageExtendedFormats
OpCapability Int64ImageEXT
OpExtension "SPV_EXT_shader_image_int64"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %27
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %18 "SSBO"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %8 NonReadable
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 1
OpDecorate %11 NonReadable
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 2
OpDecorate %14 NonReadable
OpDecorate %17 ArrayStride 8
OpMemberDecorate %18 0 Offset 0
OpDecorate %18 Block
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 3
OpDecorate %20 NonReadable
OpDecorate %27 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 64 0
%6 = OpTypeImage %5 1D 0 0 0 2 R64ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeImage %5 2D 0 0 0 2 R64ui
%10 = OpTypePointer UniformConstant %9
%11 = OpVariable %10 UniformConstant
%12 = OpTypeImage %5 3D 0 0 0 2 R64ui
%13 = OpTypePointer UniformConstant %12
%14 = OpVariable %13 UniformConstant
%15 = OpTypeInt 32 0
%16 = OpTypeVector %15 2
%17 = OpTypeRuntimeArray %16
%18 = OpTypeStruct %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%25 = OpTypeVector %15 3
%26 = OpTypePointer Input %25
%27 = OpVariable %26 Input
%28 = OpTypePointer Input %15
%30 = OpConstant %15 0
%34 = OpConstant %5 1
%37 = OpConstant %5 32
%39 = OpConstant %15 5
%40 = OpTypePointer Image %5
%45 = OpConstant %15 1
%49 = OpConstant %15 101
%51 = OpTypePointer StorageBuffer %16
%53 = OpConstant %15 6
%54 = OpConstant %15 7
%63 = OpConstant %15 102
%66 = OpConstant %15 8
%67 = OpConstant %15 9
%68 = OpConstant %15 10
%77 = OpConstant %15 103
%81 = OpConstant %5 2
%94 = OpConstant %15 104
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %97
%97 = OpLabel
%21 = OpLoad %12 %14
%22 = OpLoad %9 %11
%23 = OpLoad %6 %8
%29 = OpAccessChain %28 %27 %30
%31 = OpLoad %15 %29
%32 = OpUConvert %5 %31
%33 = OpIAdd %5 %32 %34
%35 = OpUConvert %15 %33
%36 = OpShiftRightLogical %5 %33 %37
%38 = OpUConvert %15 %36
%41 = OpImageTexelPointer %40 %8 %39 %30
%42 = OpCompositeConstruct %16 %35 %38
%43 = OpBitcast %5 %42
%44 = OpAtomicIAdd %5 %41 %45 %30 %43
%46 = OpBitcast %16 %44
%47 = OpCompositeExtract %15 %46 0
%48 = OpCompositeExtract %15 %46 1
%50 = OpCompositeConstruct %16 %47 %48
%52 = OpAccessChain %51 %20 %30 %49
OpStore %52 %50
%55 = OpCompositeConstruct %16 %53 %54
%56 = OpImageTexelPointer %40 %11 %55 %30
%57 = OpCompositeConstruct %16 %35 %38
%58 = OpBitcast %5 %57
%59 = OpAtomicIAdd %5 %56 %45 %30 %58
%60 = OpBitcast %16 %59
%61 = OpCompositeExtract %15 %60 0
%62 = OpCompositeExtract %15 %60 1
%64 = OpCompositeConstruct %16 %61 %62
%65 = OpAccessChain %51 %20 %30 %63
OpStore %65 %64
%69 = OpCompositeConstruct %25 %66 %67 %68
%70 = OpImageTexelPointer %40 %14 %69 %30
%71 = OpCompositeConstruct %16 %35 %38
%72 = OpBitcast %5 %71
%73 = OpAtomicIAdd %5 %70 %45 %30 %72
%74 = OpBitcast %16 %73
%75 = OpCompositeExtract %15 %74 0
%76 = OpCompositeExtract %15 %74 1
%78 = OpCompositeConstruct %16 %75 %76
%79 = OpAccessChain %51 %20 %30 %77
OpStore %79 %78
%80 = OpIAdd %5 %32 %81
%82 = OpUConvert %15 %80
%83 = OpShiftRightLogical %5 %80 %37
%84 = OpUConvert %15 %83
%85 = OpImageTexelPointer %40 %8 %66 %30
%86 = OpCompositeConstruct %16 %82 %84
%87 = OpBitcast %5 %86
%89 = OpCompositeConstruct %16 %35 %38
%90 = OpBitcast %5 %89
%88 = OpAtomicCompareExchange %5 %85 %45 %30 %30 %90 %87
%91 = OpBitcast %16 %88
%92 = OpCompositeExtract %15 %91 0
%93 = OpCompositeExtract %15 %91 1
%95 = OpCompositeConstruct %16 %92 %93
%96 = OpAccessChain %51 %20 %30 %94
OpStore %96 %95
OpReturn
OpFunctionEnd
#endif
