#version 460
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_shader_image_int64 : require
#extension GL_EXT_shader_atomic_int64 : require
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 0, std430) buffer _12_14
{
    uint64_t _m0[];
} _14;

layout(set = 0, binding = 4, std430) writeonly buffer _26_28
{
    uvec2 _m0[];
} _28;

layout(set = 0, binding = 1, r64ui) uniform u64image1D _17;
layout(set = 0, binding = 2, r64ui) uniform u64image2D _20;
layout(set = 0, binding = 3, r64ui) uniform u64image3D _23;

void main()
{
    uint64_t _40 = uint64_t(gl_GlobalInvocationID.x);
    uint64_t _41 = _40 + 1ul;
    uint _43 = uint(_41);
    uint _46 = uint(_41 >> 32ul);
    uint64_t _47 = _40 + 2ul;
    uint _49 = uint(_47);
    uint _51 = uint(_47 >> 32ul);
    uint _53 = 16u / 8u;
    uint64_t _59 = atomicAdd(_14._m0[_53], packUint2x32(uvec2(_43, _46)));
    _28._m0[100u] = uvec2(unpackUint2x32(_59));
    uint _68 = 16u / 8u;
    uint64_t _72 = atomicMin(_14._m0[_68], packUint2x32(uvec2(_43, _46)));
    _28._m0[101u] = uvec2(unpackUint2x32(_72));
    uint _79 = 16u / 8u;
    uint64_t _83 = atomicMax(_14._m0[_79], packUint2x32(uvec2(_43, _46)));
    _28._m0[102u] = uvec2(unpackUint2x32(_83));
    uint _90 = 16u / 8u;
    uint64_t _94 = atomicAnd(_14._m0[_90], packUint2x32(uvec2(_43, _46)));
    _28._m0[103u] = uvec2(unpackUint2x32(_94));
    uint _101 = 16u / 8u;
    uint64_t _105 = atomicOr(_14._m0[_101], packUint2x32(uvec2(_43, _46)));
    _28._m0[104u] = uvec2(unpackUint2x32(_105));
    uint _112 = 16u / 8u;
    uint64_t _116 = atomicXor(_14._m0[_112], packUint2x32(uvec2(_43, _46)));
    _28._m0[105u] = uvec2(unpackUint2x32(_116));
    uint _123 = 16u / 8u;
    uint64_t _127 = atomicExchange(_14._m0[_123], packUint2x32(uvec2(_43, _46)));
    _28._m0[106u] = uvec2(unpackUint2x32(_127));
    uint _134 = 16u / 8u;
    uint64_t _138 = atomicCompSwap(_14._m0[_134], packUint2x32(uvec2(_49, _51)), packUint2x32(uvec2(_43, _46)));
    _28._m0[110u] = uvec2(unpackUint2x32(_138));
    uint64_t _152 = imageAtomicAdd(_17, int(5u), packUint2x32(uvec2(_43, _46)));
    _28._m0[107u] = uvec2(unpackUint2x32(_152));
    uint64_t _165 = imageAtomicAdd(_20, ivec2(uvec2(6u, 7u)), packUint2x32(uvec2(_43, _46)));
    _28._m0[108u] = uvec2(unpackUint2x32(_165));
    uint64_t _178 = imageAtomicAdd(_23, ivec3(uvec3(8u, 9u, 10u)), packUint2x32(uvec2(_43, _46)));
    _28._m0[109u] = uvec2(unpackUint2x32(_178));
    uint64_t _188 = imageAtomicCompSwap(_17, int(8u), packUint2x32(uvec2(_49, _51)), packUint2x32(uvec2(_43, _46)));
    _28._m0[111u] = uvec2(unpackUint2x32(_188));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 199
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability Int64Atomics
OpCapability Image1D
OpCapability Int64ImageEXT
OpExtension "SPV_EXT_shader_image_int64"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %35
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %26 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 Aliased
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 Aliased
OpDecorate %17 DescriptorSet 0
OpDecorate %17 Binding 1
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 2
OpDecorate %23 DescriptorSet 0
OpDecorate %23 Binding 3
OpDecorate %25 ArrayStride 8
OpMemberDecorate %26 0 Offset 0
OpDecorate %26 Block
OpDecorate %28 DescriptorSet 0
OpDecorate %28 Binding 4
OpDecorate %28 NonReadable
OpDecorate %35 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeInt 64 0
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeImage %10 1D 0 0 0 2 R64ui
%16 = OpTypePointer UniformConstant %15
%17 = OpVariable %16 UniformConstant
%18 = OpTypeImage %10 2D 0 0 0 2 R64ui
%19 = OpTypePointer UniformConstant %18
%20 = OpVariable %19 UniformConstant
%21 = OpTypeImage %10 3D 0 0 0 2 R64ui
%22 = OpTypePointer UniformConstant %21
%23 = OpVariable %22 UniformConstant
%24 = OpTypeVector %5 2
%25 = OpTypeRuntimeArray %24
%26 = OpTypeStruct %25
%27 = OpTypePointer StorageBuffer %26
%28 = OpVariable %27 StorageBuffer
%33 = OpTypeVector %5 3
%34 = OpTypePointer Input %33
%35 = OpVariable %34 Input
%36 = OpTypePointer Input %5
%38 = OpConstant %5 0
%42 = OpConstant %10 1
%45 = OpConstant %10 32
%48 = OpConstant %10 2
%52 = OpConstant %5 16
%54 = OpConstant %5 8
%55 = OpTypePointer StorageBuffer %10
%60 = OpConstant %5 1
%64 = OpConstant %5 100
%66 = OpTypePointer StorageBuffer %24
%76 = OpConstant %5 101
%87 = OpConstant %5 102
%98 = OpConstant %5 103
%109 = OpConstant %5 104
%120 = OpConstant %5 105
%131 = OpConstant %5 106
%144 = OpConstant %5 110
%147 = OpConstant %5 5
%148 = OpTypePointer Image %10
%156 = OpConstant %5 107
%159 = OpConstant %5 6
%160 = OpConstant %5 7
%169 = OpConstant %5 108
%172 = OpConstant %5 9
%173 = OpConstant %5 10
%182 = OpConstant %5 109
%194 = OpConstant %5 111
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %197
%197 = OpLabel
%29 = OpLoad %21 %23
%30 = OpLoad %18 %20
%31 = OpLoad %15 %17
%37 = OpAccessChain %36 %35 %38
%39 = OpLoad %5 %37
%40 = OpUConvert %10 %39
%41 = OpIAdd %10 %40 %42
%43 = OpUConvert %5 %41
%44 = OpShiftRightLogical %10 %41 %45
%46 = OpUConvert %5 %44
%47 = OpIAdd %10 %40 %48
%49 = OpUConvert %5 %47
%50 = OpShiftRightLogical %10 %47 %45
%51 = OpUConvert %5 %50
%53 = OpUDiv %5 %52 %54
%56 = OpAccessChain %55 %14 %38 %53
%57 = OpCompositeConstruct %24 %43 %46
%58 = OpBitcast %10 %57
%59 = OpAtomicIAdd %10 %56 %60 %38 %58
%61 = OpBitcast %24 %59
%62 = OpCompositeExtract %5 %61 0
%63 = OpCompositeExtract %5 %61 1
%65 = OpCompositeConstruct %24 %62 %63
%67 = OpAccessChain %66 %28 %38 %64
OpStore %67 %65
%68 = OpUDiv %5 %52 %54
%69 = OpAccessChain %55 %14 %38 %68
%70 = OpCompositeConstruct %24 %43 %46
%71 = OpBitcast %10 %70
%72 = OpAtomicUMin %10 %69 %60 %38 %71
%73 = OpBitcast %24 %72
%74 = OpCompositeExtract %5 %73 0
%75 = OpCompositeExtract %5 %73 1
%77 = OpCompositeConstruct %24 %74 %75
%78 = OpAccessChain %66 %28 %38 %76
OpStore %78 %77
%79 = OpUDiv %5 %52 %54
%80 = OpAccessChain %55 %14 %38 %79
%81 = OpCompositeConstruct %24 %43 %46
%82 = OpBitcast %10 %81
%83 = OpAtomicUMax %10 %80 %60 %38 %82
%84 = OpBitcast %24 %83
%85 = OpCompositeExtract %5 %84 0
%86 = OpCompositeExtract %5 %84 1
%88 = OpCompositeConstruct %24 %85 %86
%89 = OpAccessChain %66 %28 %38 %87
OpStore %89 %88
%90 = OpUDiv %5 %52 %54
%91 = OpAccessChain %55 %14 %38 %90
%92 = OpCompositeConstruct %24 %43 %46
%93 = OpBitcast %10 %92
%94 = OpAtomicAnd %10 %91 %60 %38 %93
%95 = OpBitcast %24 %94
%96 = OpCompositeExtract %5 %95 0
%97 = OpCompositeExtract %5 %95 1
%99 = OpCompositeConstruct %24 %96 %97
%100 = OpAccessChain %66 %28 %38 %98
OpStore %100 %99
%101 = OpUDiv %5 %52 %54
%102 = OpAccessChain %55 %14 %38 %101
%103 = OpCompositeConstruct %24 %43 %46
%104 = OpBitcast %10 %103
%105 = OpAtomicOr %10 %102 %60 %38 %104
%106 = OpBitcast %24 %105
%107 = OpCompositeExtract %5 %106 0
%108 = OpCompositeExtract %5 %106 1
%110 = OpCompositeConstruct %24 %107 %108
%111 = OpAccessChain %66 %28 %38 %109
OpStore %111 %110
%112 = OpUDiv %5 %52 %54
%113 = OpAccessChain %55 %14 %38 %112
%114 = OpCompositeConstruct %24 %43 %46
%115 = OpBitcast %10 %114
%116 = OpAtomicXor %10 %113 %60 %38 %115
%117 = OpBitcast %24 %116
%118 = OpCompositeExtract %5 %117 0
%119 = OpCompositeExtract %5 %117 1
%121 = OpCompositeConstruct %24 %118 %119
%122 = OpAccessChain %66 %28 %38 %120
OpStore %122 %121
%123 = OpUDiv %5 %52 %54
%124 = OpAccessChain %55 %14 %38 %123
%125 = OpCompositeConstruct %24 %43 %46
%126 = OpBitcast %10 %125
%127 = OpAtomicExchange %10 %124 %60 %38 %126
%128 = OpBitcast %24 %127
%129 = OpCompositeExtract %5 %128 0
%130 = OpCompositeExtract %5 %128 1
%132 = OpCompositeConstruct %24 %129 %130
%133 = OpAccessChain %66 %28 %38 %131
OpStore %133 %132
%134 = OpUDiv %5 %52 %54
%135 = OpAccessChain %55 %14 %38 %134
%136 = OpCompositeConstruct %24 %49 %51
%137 = OpBitcast %10 %136
%139 = OpCompositeConstruct %24 %43 %46
%140 = OpBitcast %10 %139
%138 = OpAtomicCompareExchange %10 %135 %60 %38 %38 %140 %137
%141 = OpBitcast %24 %138
%142 = OpCompositeExtract %5 %141 0
%143 = OpCompositeExtract %5 %141 1
%145 = OpCompositeConstruct %24 %142 %143
%146 = OpAccessChain %66 %28 %38 %144
OpStore %146 %145
%149 = OpImageTexelPointer %148 %17 %147 %38
%150 = OpCompositeConstruct %24 %43 %46
%151 = OpBitcast %10 %150
%152 = OpAtomicIAdd %10 %149 %60 %38 %151
%153 = OpBitcast %24 %152
%154 = OpCompositeExtract %5 %153 0
%155 = OpCompositeExtract %5 %153 1
%157 = OpCompositeConstruct %24 %154 %155
%158 = OpAccessChain %66 %28 %38 %156
OpStore %158 %157
%161 = OpCompositeConstruct %24 %159 %160
%162 = OpImageTexelPointer %148 %20 %161 %38
%163 = OpCompositeConstruct %24 %43 %46
%164 = OpBitcast %10 %163
%165 = OpAtomicIAdd %10 %162 %60 %38 %164
%166 = OpBitcast %24 %165
%167 = OpCompositeExtract %5 %166 0
%168 = OpCompositeExtract %5 %166 1
%170 = OpCompositeConstruct %24 %167 %168
%171 = OpAccessChain %66 %28 %38 %169
OpStore %171 %170
%174 = OpCompositeConstruct %33 %54 %172 %173
%175 = OpImageTexelPointer %148 %23 %174 %38
%176 = OpCompositeConstruct %24 %43 %46
%177 = OpBitcast %10 %176
%178 = OpAtomicIAdd %10 %175 %60 %38 %177
%179 = OpBitcast %24 %178
%180 = OpCompositeExtract %5 %179 0
%181 = OpCompositeExtract %5 %179 1
%183 = OpCompositeConstruct %24 %180 %181
%184 = OpAccessChain %66 %28 %38 %182
OpStore %184 %183
%185 = OpImageTexelPointer %148 %17 %54 %38
%186 = OpCompositeConstruct %24 %49 %51
%187 = OpBitcast %10 %186
%189 = OpCompositeConstruct %24 %43 %46
%190 = OpBitcast %10 %189
%188 = OpAtomicCompareExchange %10 %185 %60 %38 %38 %190 %187
%191 = OpBitcast %24 %188
%192 = OpCompositeExtract %5 %191 0
%193 = OpCompositeExtract %5 %191 1
%195 = OpCompositeConstruct %24 %192 %193
%196 = OpAccessChain %66 %28 %38 %194
OpStore %196 %195
OpReturn
OpFunctionEnd
#endif
