#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 15, binding = 0, std430) restrict readonly buffer SSBO_Offsets
{
    uvec2 _m0[];
} _13;

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
    uint _m8;
    uint _m9;
    uint _m10;
    uint _m11;
    uint _m12;
    uint _m13;
    uint _m14;
    uint _m15;
} registers;

layout(set = 1, binding = 0) uniform usamplerBuffer _17[];
layout(set = 1, binding = 0) uniform usamplerBuffer _20[];
layout(set = 4, binding = 0, r32ui) uniform writeonly uimageBuffer _24[];
layout(set = 4, binding = 0, r32ui) uniform writeonly uimageBuffer _27[];
layout(set = 4, binding = 0, r32ui) uniform uimageBuffer _30[];
layout(set = 4, binding = 0) uniform writeonly uimageBuffer _34[];

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _46 = (subgroupBroadcastFirst(registers._m4) * 2u) + 1u;
    uint _59 = (subgroupBroadcastFirst(registers._m4) * 2u) + 1u;
    uint _65 = registers._m4 + 1u;
    uint _69 = (subgroupBroadcastFirst(_65) * 2u) + 1u;
    uint _78 = (subgroupBroadcastFirst(registers._m4) * 2u) + 1u;
    uint _85 = registers._m1 + 1u;
    uint _89 = (subgroupBroadcastFirst(_85) * 2u) + 1u;
    uint _98 = (subgroupBroadcastFirst(registers._m1) * 2u) + 1u;
    uint _110 = gl_GlobalInvocationID.x * 2u;
    uint _116 = (_110 < _13._m0[_98].y) ? (_110 + _13._m0[_98].x) : 1073741820u;
    vec2 _127 = uintBitsToFloat(uvec2(texelFetch(_17[registers._m1], int(_116)).x, texelFetch(_17[registers._m1], int(_116 + 1u)).x));
    uint _130 = gl_GlobalInvocationID.x * 2u;
    uint _135 = (_130 < _13._m0[_78].y) ? (_130 + _13._m0[_78].x) : 1073741820u;
    imageStore(_24[registers._m4], int(_135), uvec4(floatBitsToUint(_127.x)));
    imageStore(_24[registers._m4], int(_135 + 1u), uvec4(floatBitsToUint(_127.y)));
    uint _152 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _157 = (_152 < _13._m0[_89].y) ? (_152 + _13._m0[_89].x) : 1073741820u;
    uvec4 _169 = uvec4(texelFetch(_20[_85], int(_157)).x, texelFetch(_20[_85], int(_157 + 1u)).x, texelFetch(_20[_85], int(_157 + 2u)).x, texelFetch(_20[_85], int(_157 + 3u)).x);
    uint _175 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _180 = (_175 < _13._m0[_69].y) ? (_175 + _13._m0[_69].x) : 1073741820u;
    imageStore(_27[_65], int(_180), uvec4(_169.x));
    imageStore(_27[_65], int(_180 + 1u), uvec4(_169.y));
    imageStore(_27[_65], int(_180 + 2u), uvec4(_169.z));
    imageStore(_27[_65], int(_180 + 3u), uvec4(_169.w));
    uint _188 = gl_GlobalInvocationID.x * 2u;
    uint _193 = (_188 < _13._m0[_98].y) ? (_188 + _13._m0[_98].x) : 1073741820u;
    vec2 _200 = uintBitsToFloat(uvec2(texelFetch(_17[registers._m1], int(_193)).x, texelFetch(_17[registers._m1], int(_193 + 1u)).x));
    uint _203 = gl_GlobalInvocationID.x * 2u;
    uint _208 = (_203 < _13._m0[_78].y) ? (_203 + _13._m0[_78].x) : 1073741820u;
    imageStore(_24[registers._m4], int(_208), uvec4(floatBitsToUint(_200.x)));
    imageStore(_24[registers._m4], int(_208 + 1u), uvec4(floatBitsToUint(_200.y)));
    uint _215 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _220 = (_215 < _13._m0[_89].y) ? (_215 + _13._m0[_89].x) : 1073741820u;
    uvec4 _232 = uvec4(texelFetch(_20[_85], int(_220)).x, texelFetch(_20[_85], int(_220 + 1u)).x, texelFetch(_20[_85], int(_220 + 2u)).x, texelFetch(_20[_85], int(_220 + 3u)).x);
    uint _238 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _243 = (_238 < _13._m0[_69].y) ? (_238 + _13._m0[_69].x) : 1073741820u;
    imageStore(_27[_65], int(_243), uvec4(_232.x));
    imageStore(_27[_65], int(_243 + 1u), uvec4(_232.y));
    imageStore(_27[_65], int(_243 + 2u), uvec4(_232.z));
    imageStore(_27[_65], int(_243 + 3u), uvec4(_232.w));
    uint _255 = registers._m1 + (gl_WorkGroupID.x + 2u);
    uint _259 = (subgroupBroadcastFirst(_255) * 2u) + 1u;
    uint _262 = gl_GlobalInvocationID.x * 2u;
    uint _267 = (_262 < _13._m0[_259].y) ? (_262 + _13._m0[_259].x) : 1073741820u;
    vec2 _274 = uintBitsToFloat(uvec2(texelFetch(_17[_255], int(_267)).x, texelFetch(_17[_255], int(_267 + 1u)).x));
    uint _281 = registers._m4 + (gl_WorkGroupID.x + 0u);
    uint _285 = (subgroupBroadcastFirst(_281) * 2u) + 1u;
    uint _288 = gl_GlobalInvocationID.x * 2u;
    uint _293 = (_288 < _13._m0[_285].y) ? (_288 + _13._m0[_285].x) : 1073741820u;
    imageStore(_24[_281], int(_293), uvec4(floatBitsToUint(_274.x)));
    imageStore(_24[_281], int(_293 + 1u), uvec4(floatBitsToUint(_274.y)));
    uint _303 = registers._m1 + (gl_GlobalInvocationID.x + 2u);
    uint _306 = (_303 * 2u) + 1u;
    uint _309 = gl_GlobalInvocationID.x * 2u;
    uint _314 = (_309 < _13._m0[_306].y) ? (_309 + _13._m0[_306].x) : 1073741820u;
    vec2 _321 = uintBitsToFloat(uvec2(texelFetch(_17[nonuniformEXT(_303)], int(_314)).x, texelFetch(_17[nonuniformEXT(_303)], int(_314 + 1u)).x));
    uint _328 = registers._m4 + (gl_GlobalInvocationID.x + 0u);
    uint _331 = (_328 * 2u) + 1u;
    uint _334 = gl_GlobalInvocationID.x * 2u;
    uint _339 = (_334 < _13._m0[_331].y) ? (_334 + _13._m0[_331].x) : 1073741820u;
    imageStore(_24[nonuniformEXT(_328)], int(_339), uvec4(floatBitsToUint(_321.x)));
    imageStore(_24[nonuniformEXT(_328)], int(_339 + 1u), uvec4(floatBitsToUint(_321.y)));
    uint _349 = registers._m1 + (gl_WorkGroupID.x + 3u);
    uint _353 = (subgroupBroadcastFirst(_349) * 2u) + 1u;
    uint _357 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _362 = (_357 < _13._m0[_353].y) ? (_357 + _13._m0[_353].x) : 1073741820u;
    uvec4 _374 = uvec4(texelFetch(_20[_349], int(_362)).x, texelFetch(_20[_349], int(_362 + 1u)).x, texelFetch(_20[_349], int(_362 + 2u)).x, texelFetch(_20[_349], int(_362 + 3u)).x);
    uint _383 = registers._m4 + (gl_WorkGroupID.x + 1u);
    uint _387 = (subgroupBroadcastFirst(_383) * 2u) + 1u;
    uint _391 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _396 = (_391 < _13._m0[_387].y) ? (_391 + _13._m0[_387].x) : 1073741820u;
    imageStore(_27[_383], int(_396), uvec4(_374.x));
    imageStore(_27[_383], int(_396 + 1u), uvec4(_374.y));
    imageStore(_27[_383], int(_396 + 2u), uvec4(_374.z));
    imageStore(_27[_383], int(_396 + 3u), uvec4(_374.w));
    uint _408 = registers._m1 + (gl_GlobalInvocationID.x + 3u);
    uint _411 = (_408 * 2u) + 1u;
    uint _415 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _420 = (_415 < _13._m0[_411].y) ? (_415 + _13._m0[_411].x) : 1073741820u;
    uvec4 _432 = uvec4(texelFetch(_20[nonuniformEXT(_408)], int(_420)).x, texelFetch(_20[nonuniformEXT(_408)], int(_420 + 1u)).x, texelFetch(_20[nonuniformEXT(_408)], int(_420 + 2u)).x, texelFetch(_20[nonuniformEXT(_408)], int(_420 + 3u)).x);
    uint _441 = registers._m4 + (gl_GlobalInvocationID.x + 1u);
    uint _444 = (_441 * 2u) + 1u;
    uint _448 = ByteAddressMask(gl_GlobalInvocationID.x * 4u, 4u);
    uint _453 = (_448 < _13._m0[_444].y) ? (_448 + _13._m0[_444].x) : 1073741820u;
    imageStore(_27[nonuniformEXT(_441)], int(_453), uvec4(_432.x));
    imageStore(_27[nonuniformEXT(_441)], int(_453 + 1u), uvec4(_432.y));
    imageStore(_27[nonuniformEXT(_441)], int(_453 + 2u), uvec4(_432.z));
    imageStore(_27[nonuniformEXT(_441)], int(_453 + 3u), uvec4(_432.w));
    uint _462 = (gl_GlobalInvocationID.x * 2u) + 1u;
    uint _470 = imageAtomicAdd(_30[registers._m4], int((_462 < _13._m0[_59].y) ? (_462 + _13._m0[_59].x) : 1073741820u), 1u);
    uint _473 = gl_GlobalInvocationID.x * 2u;
    uint _480 = imageAtomicAdd(_30[registers._m4], int((_473 < _13._m0[_59].y) ? (_473 + _13._m0[_59].x) : 1073741820u), _13._m0[_78].y / 2u);
    uint _481 = gl_GlobalInvocationID.x << 2u;
    imageStore(_34[registers._m4], int((gl_GlobalInvocationID.x < _13._m0[_46].y) ? (gl_GlobalInvocationID.x + _13._m0[_46].x) : 4294967295u), uvec4(_481, _481 | 1u, _481 | 2u, _481 | 3u));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 493
; Schema: 0
OpCapability Shader
OpCapability SampledBuffer
OpCapability ImageBuffer
OpCapability ImageQuery
OpCapability StorageImageWriteWithoutFormat
OpCapability GroupNonUniformBallot
OpCapability RuntimeDescriptorArray
OpCapability UniformTexelBufferArrayDynamicIndexing
OpCapability StorageTexelBufferArrayDynamicIndexing
OpCapability UniformTexelBufferArrayNonUniformIndexing
OpCapability StorageTexelBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %103 %107
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %146 "ByteAddressMask"
OpName %144 "index"
OpName %145 "stride"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpMemberDecorate %6 8 Offset 32
OpMemberDecorate %6 9 Offset 36
OpMemberDecorate %6 10 Offset 40
OpMemberDecorate %6 11 Offset 44
OpMemberDecorate %6 12 Offset 48
OpMemberDecorate %6 13 Offset 52
OpMemberDecorate %6 14 Offset 56
OpMemberDecorate %6 15 Offset 60
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %17 DescriptorSet 1
OpDecorate %17 Binding 0
OpDecorate %20 DescriptorSet 1
OpDecorate %20 Binding 0
OpDecorate %24 DescriptorSet 4
OpDecorate %24 Binding 0
OpDecorate %24 NonReadable
OpDecorate %27 DescriptorSet 4
OpDecorate %27 Binding 0
OpDecorate %27 NonReadable
OpDecorate %30 DescriptorSet 4
OpDecorate %30 Binding 0
OpDecorate %34 DescriptorSet 4
OpDecorate %34 Binding 0
OpDecorate %34 NonReadable
OpDecorate %103 BuiltIn GlobalInvocationId
OpDecorate %107 BuiltIn WorkgroupId
OpDecorate %303 NonUniform
OpDecorate %304 NonUniform
OpDecorate %328 NonUniform
OpDecorate %329 NonUniform
OpDecorate %408 NonUniform
OpDecorate %409 NonUniform
OpDecorate %441 NonUniform
OpDecorate %442 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeImage %5 Buffer 0 0 0 1 Unknown
%15 = OpTypeRuntimeArray %14
%16 = OpTypePointer UniformConstant %15
%17 = OpVariable %16 UniformConstant
%18 = OpTypeRuntimeArray %14
%19 = OpTypePointer UniformConstant %18
%20 = OpVariable %19 UniformConstant
%21 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%22 = OpTypeRuntimeArray %21
%23 = OpTypePointer UniformConstant %22
%24 = OpVariable %23 UniformConstant
%25 = OpTypeRuntimeArray %21
%26 = OpTypePointer UniformConstant %25
%27 = OpVariable %26 UniformConstant
%28 = OpTypeRuntimeArray %21
%29 = OpTypePointer UniformConstant %28
%30 = OpVariable %29 UniformConstant
%31 = OpTypeImage %5 Buffer 0 0 0 2 Unknown
%32 = OpTypeRuntimeArray %31
%33 = OpTypePointer UniformConstant %32
%34 = OpVariable %33 UniformConstant
%35 = OpTypePointer UniformConstant %31
%37 = OpTypePointer PushConstant %5
%39 = OpConstant %5 4
%43 = OpConstant %5 3
%45 = OpConstant %5 2
%47 = OpConstant %5 1
%48 = OpTypePointer StorageBuffer %9
%50 = OpConstant %5 0
%52 = OpTypePointer UniformConstant %21
%81 = OpTypePointer UniformConstant %14
%101 = OpTypeVector %5 3
%102 = OpTypePointer Input %101
%103 = OpVariable %102 Input
%104 = OpTypePointer Input %5
%107 = OpVariable %102 Input
%114 = OpTypeBool
%117 = OpConstant %5 1073741820
%118 = OpTypeVector %5 4
%125 = OpTypeFloat 32
%126 = OpTypeVector %125 2
%143 = OpTypeFunction %5 %5 %5
%149 = OpConstant %5 4294967295
%468 = OpTypePointer Image %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %491
%491 = OpLabel
%38 = OpAccessChain %37 %8 %39
%40 = OpLoad %5 %38
%36 = OpAccessChain %35 %34 %40
%41 = OpLoad %31 %36
%42 = OpGroupNonUniformBroadcastFirst %5 %43 %40
%44 = OpIMul %5 %42 %45
%46 = OpIAdd %5 %44 %47
%49 = OpAccessChain %48 %13 %50 %46
%51 = OpLoad %9 %49
%54 = OpAccessChain %37 %8 %39
%55 = OpLoad %5 %54
%53 = OpAccessChain %52 %30 %55
%56 = OpLoad %21 %53
%57 = OpGroupNonUniformBroadcastFirst %5 %43 %55
%58 = OpIMul %5 %57 %45
%59 = OpIAdd %5 %58 %47
%60 = OpAccessChain %48 %13 %50 %59
%61 = OpLoad %9 %60
%63 = OpAccessChain %37 %8 %39
%64 = OpLoad %5 %63
%65 = OpIAdd %5 %64 %47
%62 = OpAccessChain %52 %27 %65
%66 = OpLoad %21 %62
%67 = OpGroupNonUniformBroadcastFirst %5 %43 %65
%68 = OpIMul %5 %67 %45
%69 = OpIAdd %5 %68 %47
%70 = OpAccessChain %48 %13 %50 %69
%71 = OpLoad %9 %70
%73 = OpAccessChain %37 %8 %39
%74 = OpLoad %5 %73
%72 = OpAccessChain %52 %24 %74
%75 = OpLoad %21 %72
%76 = OpGroupNonUniformBroadcastFirst %5 %43 %74
%77 = OpIMul %5 %76 %45
%78 = OpIAdd %5 %77 %47
%79 = OpAccessChain %48 %13 %50 %78
%80 = OpLoad %9 %79
%83 = OpAccessChain %37 %8 %47
%84 = OpLoad %5 %83
%85 = OpIAdd %5 %84 %47
%82 = OpAccessChain %81 %20 %85
%86 = OpLoad %14 %82
%87 = OpGroupNonUniformBroadcastFirst %5 %43 %85
%88 = OpIMul %5 %87 %45
%89 = OpIAdd %5 %88 %47
%90 = OpAccessChain %48 %13 %50 %89
%91 = OpLoad %9 %90
%93 = OpAccessChain %37 %8 %47
%94 = OpLoad %5 %93
%92 = OpAccessChain %81 %17 %94
%95 = OpLoad %14 %92
%96 = OpGroupNonUniformBroadcastFirst %5 %43 %94
%97 = OpIMul %5 %96 %45
%98 = OpIAdd %5 %97 %47
%99 = OpAccessChain %48 %13 %50 %98
%100 = OpLoad %9 %99
%105 = OpAccessChain %104 %103 %50
%106 = OpLoad %5 %105
%108 = OpAccessChain %104 %107 %50
%109 = OpLoad %5 %108
%110 = OpIMul %5 %106 %45
%111 = OpCompositeExtract %5 %100 0
%112 = OpCompositeExtract %5 %100 1
%113 = OpIAdd %5 %110 %111
%115 = OpULessThan %114 %110 %112
%116 = OpSelect %5 %115 %113 %117
%119 = OpImageFetch %118 %95 %116
%120 = OpCompositeExtract %5 %119 0
%122 = OpIAdd %5 %116 %47
%121 = OpImageFetch %118 %95 %122
%123 = OpCompositeExtract %5 %121 0
%124 = OpCompositeConstruct %9 %120 %123
%127 = OpBitcast %126 %124
%128 = OpCompositeExtract %125 %127 0
%129 = OpCompositeExtract %125 %127 1
%130 = OpIMul %5 %106 %45
%131 = OpCompositeExtract %5 %80 0
%132 = OpCompositeExtract %5 %80 1
%133 = OpIAdd %5 %130 %131
%134 = OpULessThan %114 %130 %132
%135 = OpSelect %5 %134 %133 %117
%136 = OpBitcast %5 %128
%137 = OpBitcast %5 %129
%138 = OpCompositeConstruct %118 %136 %136 %136 %136
OpImageWrite %75 %135 %138
%139 = OpCompositeConstruct %118 %137 %137 %137 %137
%140 = OpIAdd %5 %135 %47
OpImageWrite %75 %140 %139
%141 = OpShiftLeftLogical %5 %106 %39
%142 = OpIMul %5 %106 %39
%152 = OpFunctionCall %5 %146 %142 %39
%153 = OpCompositeExtract %5 %91 0
%154 = OpCompositeExtract %5 %91 1
%155 = OpIAdd %5 %152 %153
%156 = OpULessThan %114 %152 %154
%157 = OpSelect %5 %156 %155 %117
%158 = OpImageFetch %118 %86 %157
%159 = OpCompositeExtract %5 %158 0
%161 = OpIAdd %5 %157 %47
%160 = OpImageFetch %118 %86 %161
%162 = OpCompositeExtract %5 %160 0
%164 = OpIAdd %5 %157 %45
%163 = OpImageFetch %118 %86 %164
%165 = OpCompositeExtract %5 %163 0
%167 = OpIAdd %5 %157 %43
%166 = OpImageFetch %118 %86 %167
%168 = OpCompositeExtract %5 %166 0
%169 = OpCompositeConstruct %118 %159 %162 %165 %168
%170 = OpCompositeExtract %5 %169 0
%171 = OpCompositeExtract %5 %169 1
%172 = OpCompositeExtract %5 %169 2
%173 = OpCompositeExtract %5 %169 3
%174 = OpIMul %5 %106 %39
%175 = OpFunctionCall %5 %146 %174 %39
%176 = OpCompositeExtract %5 %71 0
%177 = OpCompositeExtract %5 %71 1
%178 = OpIAdd %5 %175 %176
%179 = OpULessThan %114 %175 %177
%180 = OpSelect %5 %179 %178 %117
%181 = OpCompositeConstruct %118 %170 %170 %170 %170
OpImageWrite %66 %180 %181
%182 = OpCompositeConstruct %118 %171 %171 %171 %171
%183 = OpIAdd %5 %180 %47
OpImageWrite %66 %183 %182
%184 = OpCompositeConstruct %118 %172 %172 %172 %172
%185 = OpIAdd %5 %180 %45
OpImageWrite %66 %185 %184
%186 = OpCompositeConstruct %118 %173 %173 %173 %173
%187 = OpIAdd %5 %180 %43
OpImageWrite %66 %187 %186
%188 = OpIMul %5 %106 %45
%189 = OpCompositeExtract %5 %100 0
%190 = OpCompositeExtract %5 %100 1
%191 = OpIAdd %5 %188 %189
%192 = OpULessThan %114 %188 %190
%193 = OpSelect %5 %192 %191 %117
%194 = OpImageFetch %118 %95 %193
%195 = OpCompositeExtract %5 %194 0
%197 = OpIAdd %5 %193 %47
%196 = OpImageFetch %118 %95 %197
%198 = OpCompositeExtract %5 %196 0
%199 = OpCompositeConstruct %9 %195 %198
%200 = OpBitcast %126 %199
%201 = OpCompositeExtract %125 %200 0
%202 = OpCompositeExtract %125 %200 1
%203 = OpIMul %5 %106 %45
%204 = OpCompositeExtract %5 %80 0
%205 = OpCompositeExtract %5 %80 1
%206 = OpIAdd %5 %203 %204
%207 = OpULessThan %114 %203 %205
%208 = OpSelect %5 %207 %206 %117
%209 = OpBitcast %5 %201
%210 = OpBitcast %5 %202
%211 = OpCompositeConstruct %118 %209 %209 %209 %209
OpImageWrite %75 %208 %211
%212 = OpCompositeConstruct %118 %210 %210 %210 %210
%213 = OpIAdd %5 %208 %47
OpImageWrite %75 %213 %212
%214 = OpIMul %5 %106 %39
%215 = OpFunctionCall %5 %146 %214 %39
%216 = OpCompositeExtract %5 %91 0
%217 = OpCompositeExtract %5 %91 1
%218 = OpIAdd %5 %215 %216
%219 = OpULessThan %114 %215 %217
%220 = OpSelect %5 %219 %218 %117
%221 = OpImageFetch %118 %86 %220
%222 = OpCompositeExtract %5 %221 0
%224 = OpIAdd %5 %220 %47
%223 = OpImageFetch %118 %86 %224
%225 = OpCompositeExtract %5 %223 0
%227 = OpIAdd %5 %220 %45
%226 = OpImageFetch %118 %86 %227
%228 = OpCompositeExtract %5 %226 0
%230 = OpIAdd %5 %220 %43
%229 = OpImageFetch %118 %86 %230
%231 = OpCompositeExtract %5 %229 0
%232 = OpCompositeConstruct %118 %222 %225 %228 %231
%233 = OpCompositeExtract %5 %232 0
%234 = OpCompositeExtract %5 %232 1
%235 = OpCompositeExtract %5 %232 2
%236 = OpCompositeExtract %5 %232 3
%237 = OpIMul %5 %106 %39
%238 = OpFunctionCall %5 %146 %237 %39
%239 = OpCompositeExtract %5 %71 0
%240 = OpCompositeExtract %5 %71 1
%241 = OpIAdd %5 %238 %239
%242 = OpULessThan %114 %238 %240
%243 = OpSelect %5 %242 %241 %117
%244 = OpCompositeConstruct %118 %233 %233 %233 %233
OpImageWrite %66 %243 %244
%245 = OpCompositeConstruct %118 %234 %234 %234 %234
%246 = OpIAdd %5 %243 %47
OpImageWrite %66 %246 %245
%247 = OpCompositeConstruct %118 %235 %235 %235 %235
%248 = OpIAdd %5 %243 %45
OpImageWrite %66 %248 %247
%249 = OpCompositeConstruct %118 %236 %236 %236 %236
%250 = OpIAdd %5 %243 %43
OpImageWrite %66 %250 %249
%251 = OpIAdd %5 %109 %45
%253 = OpAccessChain %37 %8 %47
%254 = OpLoad %5 %253
%255 = OpIAdd %5 %254 %251
%252 = OpAccessChain %81 %17 %255
%256 = OpLoad %14 %252
%257 = OpGroupNonUniformBroadcastFirst %5 %43 %255
%258 = OpIMul %5 %257 %45
%259 = OpIAdd %5 %258 %47
%260 = OpAccessChain %48 %13 %50 %259
%261 = OpLoad %9 %260
%262 = OpIMul %5 %106 %45
%263 = OpCompositeExtract %5 %261 0
%264 = OpCompositeExtract %5 %261 1
%265 = OpIAdd %5 %262 %263
%266 = OpULessThan %114 %262 %264
%267 = OpSelect %5 %266 %265 %117
%268 = OpImageFetch %118 %256 %267
%269 = OpCompositeExtract %5 %268 0
%271 = OpIAdd %5 %267 %47
%270 = OpImageFetch %118 %256 %271
%272 = OpCompositeExtract %5 %270 0
%273 = OpCompositeConstruct %9 %269 %272
%274 = OpBitcast %126 %273
%275 = OpCompositeExtract %125 %274 0
%276 = OpCompositeExtract %125 %274 1
%277 = OpIAdd %5 %109 %50
%279 = OpAccessChain %37 %8 %39
%280 = OpLoad %5 %279
%281 = OpIAdd %5 %280 %277
%278 = OpAccessChain %52 %24 %281
%282 = OpLoad %21 %278
%283 = OpGroupNonUniformBroadcastFirst %5 %43 %281
%284 = OpIMul %5 %283 %45
%285 = OpIAdd %5 %284 %47
%286 = OpAccessChain %48 %13 %50 %285
%287 = OpLoad %9 %286
%288 = OpIMul %5 %106 %45
%289 = OpCompositeExtract %5 %287 0
%290 = OpCompositeExtract %5 %287 1
%291 = OpIAdd %5 %288 %289
%292 = OpULessThan %114 %288 %290
%293 = OpSelect %5 %292 %291 %117
%294 = OpBitcast %5 %275
%295 = OpBitcast %5 %276
%296 = OpCompositeConstruct %118 %294 %294 %294 %294
OpImageWrite %282 %293 %296
%297 = OpCompositeConstruct %118 %295 %295 %295 %295
%298 = OpIAdd %5 %293 %47
OpImageWrite %282 %298 %297
%299 = OpIAdd %5 %106 %45
%301 = OpAccessChain %37 %8 %47
%302 = OpLoad %5 %301
%303 = OpIAdd %5 %302 %299
%300 = OpAccessChain %81 %17 %303
%304 = OpLoad %14 %300
%305 = OpIMul %5 %303 %45
%306 = OpIAdd %5 %305 %47
%307 = OpAccessChain %48 %13 %50 %306
%308 = OpLoad %9 %307
%309 = OpIMul %5 %106 %45
%310 = OpCompositeExtract %5 %308 0
%311 = OpCompositeExtract %5 %308 1
%312 = OpIAdd %5 %309 %310
%313 = OpULessThan %114 %309 %311
%314 = OpSelect %5 %313 %312 %117
%315 = OpImageFetch %118 %304 %314
%316 = OpCompositeExtract %5 %315 0
%318 = OpIAdd %5 %314 %47
%317 = OpImageFetch %118 %304 %318
%319 = OpCompositeExtract %5 %317 0
%320 = OpCompositeConstruct %9 %316 %319
%321 = OpBitcast %126 %320
%322 = OpCompositeExtract %125 %321 0
%323 = OpCompositeExtract %125 %321 1
%324 = OpIAdd %5 %106 %50
%326 = OpAccessChain %37 %8 %39
%327 = OpLoad %5 %326
%328 = OpIAdd %5 %327 %324
%325 = OpAccessChain %52 %24 %328
%329 = OpLoad %21 %325
%330 = OpIMul %5 %328 %45
%331 = OpIAdd %5 %330 %47
%332 = OpAccessChain %48 %13 %50 %331
%333 = OpLoad %9 %332
%334 = OpIMul %5 %106 %45
%335 = OpCompositeExtract %5 %333 0
%336 = OpCompositeExtract %5 %333 1
%337 = OpIAdd %5 %334 %335
%338 = OpULessThan %114 %334 %336
%339 = OpSelect %5 %338 %337 %117
%340 = OpBitcast %5 %322
%341 = OpBitcast %5 %323
%342 = OpCompositeConstruct %118 %340 %340 %340 %340
OpImageWrite %329 %339 %342
%343 = OpCompositeConstruct %118 %341 %341 %341 %341
%344 = OpIAdd %5 %339 %47
OpImageWrite %329 %344 %343
%345 = OpIAdd %5 %109 %43
%347 = OpAccessChain %37 %8 %47
%348 = OpLoad %5 %347
%349 = OpIAdd %5 %348 %345
%346 = OpAccessChain %81 %20 %349
%350 = OpLoad %14 %346
%351 = OpGroupNonUniformBroadcastFirst %5 %43 %349
%352 = OpIMul %5 %351 %45
%353 = OpIAdd %5 %352 %47
%354 = OpAccessChain %48 %13 %50 %353
%355 = OpLoad %9 %354
%356 = OpIMul %5 %106 %39
%357 = OpFunctionCall %5 %146 %356 %39
%358 = OpCompositeExtract %5 %355 0
%359 = OpCompositeExtract %5 %355 1
%360 = OpIAdd %5 %357 %358
%361 = OpULessThan %114 %357 %359
%362 = OpSelect %5 %361 %360 %117
%363 = OpImageFetch %118 %350 %362
%364 = OpCompositeExtract %5 %363 0
%366 = OpIAdd %5 %362 %47
%365 = OpImageFetch %118 %350 %366
%367 = OpCompositeExtract %5 %365 0
%369 = OpIAdd %5 %362 %45
%368 = OpImageFetch %118 %350 %369
%370 = OpCompositeExtract %5 %368 0
%372 = OpIAdd %5 %362 %43
%371 = OpImageFetch %118 %350 %372
%373 = OpCompositeExtract %5 %371 0
%374 = OpCompositeConstruct %118 %364 %367 %370 %373
%375 = OpCompositeExtract %5 %374 0
%376 = OpCompositeExtract %5 %374 1
%377 = OpCompositeExtract %5 %374 2
%378 = OpCompositeExtract %5 %374 3
%379 = OpIAdd %5 %109 %47
%381 = OpAccessChain %37 %8 %39
%382 = OpLoad %5 %381
%383 = OpIAdd %5 %382 %379
%380 = OpAccessChain %52 %27 %383
%384 = OpLoad %21 %380
%385 = OpGroupNonUniformBroadcastFirst %5 %43 %383
%386 = OpIMul %5 %385 %45
%387 = OpIAdd %5 %386 %47
%388 = OpAccessChain %48 %13 %50 %387
%389 = OpLoad %9 %388
%390 = OpIMul %5 %106 %39
%391 = OpFunctionCall %5 %146 %390 %39
%392 = OpCompositeExtract %5 %389 0
%393 = OpCompositeExtract %5 %389 1
%394 = OpIAdd %5 %391 %392
%395 = OpULessThan %114 %391 %393
%396 = OpSelect %5 %395 %394 %117
%397 = OpCompositeConstruct %118 %375 %375 %375 %375
OpImageWrite %384 %396 %397
%398 = OpCompositeConstruct %118 %376 %376 %376 %376
%399 = OpIAdd %5 %396 %47
OpImageWrite %384 %399 %398
%400 = OpCompositeConstruct %118 %377 %377 %377 %377
%401 = OpIAdd %5 %396 %45
OpImageWrite %384 %401 %400
%402 = OpCompositeConstruct %118 %378 %378 %378 %378
%403 = OpIAdd %5 %396 %43
OpImageWrite %384 %403 %402
%404 = OpIAdd %5 %106 %43
%406 = OpAccessChain %37 %8 %47
%407 = OpLoad %5 %406
%408 = OpIAdd %5 %407 %404
%405 = OpAccessChain %81 %20 %408
%409 = OpLoad %14 %405
%410 = OpIMul %5 %408 %45
%411 = OpIAdd %5 %410 %47
%412 = OpAccessChain %48 %13 %50 %411
%413 = OpLoad %9 %412
%414 = OpIMul %5 %106 %39
%415 = OpFunctionCall %5 %146 %414 %39
%416 = OpCompositeExtract %5 %413 0
%417 = OpCompositeExtract %5 %413 1
%418 = OpIAdd %5 %415 %416
%419 = OpULessThan %114 %415 %417
%420 = OpSelect %5 %419 %418 %117
%421 = OpImageFetch %118 %409 %420
%422 = OpCompositeExtract %5 %421 0
%424 = OpIAdd %5 %420 %47
%423 = OpImageFetch %118 %409 %424
%425 = OpCompositeExtract %5 %423 0
%427 = OpIAdd %5 %420 %45
%426 = OpImageFetch %118 %409 %427
%428 = OpCompositeExtract %5 %426 0
%430 = OpIAdd %5 %420 %43
%429 = OpImageFetch %118 %409 %430
%431 = OpCompositeExtract %5 %429 0
%432 = OpCompositeConstruct %118 %422 %425 %428 %431
%433 = OpCompositeExtract %5 %432 0
%434 = OpCompositeExtract %5 %432 1
%435 = OpCompositeExtract %5 %432 2
%436 = OpCompositeExtract %5 %432 3
%437 = OpIAdd %5 %106 %47
%439 = OpAccessChain %37 %8 %39
%440 = OpLoad %5 %439
%441 = OpIAdd %5 %440 %437
%438 = OpAccessChain %52 %27 %441
%442 = OpLoad %21 %438
%443 = OpIMul %5 %441 %45
%444 = OpIAdd %5 %443 %47
%445 = OpAccessChain %48 %13 %50 %444
%446 = OpLoad %9 %445
%447 = OpIMul %5 %106 %39
%448 = OpFunctionCall %5 %146 %447 %39
%449 = OpCompositeExtract %5 %446 0
%450 = OpCompositeExtract %5 %446 1
%451 = OpIAdd %5 %448 %449
%452 = OpULessThan %114 %448 %450
%453 = OpSelect %5 %452 %451 %117
%454 = OpCompositeConstruct %118 %433 %433 %433 %433
OpImageWrite %442 %453 %454
%455 = OpCompositeConstruct %118 %434 %434 %434 %434
%456 = OpIAdd %5 %453 %47
OpImageWrite %442 %456 %455
%457 = OpCompositeConstruct %118 %435 %435 %435 %435
%458 = OpIAdd %5 %453 %45
OpImageWrite %442 %458 %457
%459 = OpCompositeConstruct %118 %436 %436 %436 %436
%460 = OpIAdd %5 %453 %43
OpImageWrite %442 %460 %459
%461 = OpIMul %5 %106 %45
%462 = OpIAdd %5 %461 %47
%463 = OpCompositeExtract %5 %61 0
%464 = OpCompositeExtract %5 %61 1
%465 = OpIAdd %5 %462 %463
%466 = OpULessThan %114 %462 %464
%467 = OpSelect %5 %466 %465 %117
%469 = OpImageTexelPointer %468 %53 %467 %50
%470 = OpAtomicIAdd %5 %469 %47 %50 %47
%471 = OpCompositeExtract %5 %80 1
%472 = OpUDiv %5 %471 %45
%473 = OpIMul %5 %106 %45
%474 = OpCompositeExtract %5 %61 0
%475 = OpCompositeExtract %5 %61 1
%476 = OpIAdd %5 %473 %474
%477 = OpULessThan %114 %473 %475
%478 = OpSelect %5 %477 %476 %117
%479 = OpImageTexelPointer %468 %53 %478 %50
%480 = OpAtomicIAdd %5 %479 %47 %50 %472
%481 = OpShiftLeftLogical %5 %106 %45
%482 = OpBitwiseOr %5 %481 %47
%483 = OpBitwiseOr %5 %481 %45
%484 = OpBitwiseOr %5 %481 %43
%485 = OpCompositeExtract %5 %51 0
%486 = OpCompositeExtract %5 %51 1
%487 = OpIAdd %5 %106 %485
%488 = OpULessThan %114 %106 %486
%489 = OpSelect %5 %488 %487 %149
%490 = OpCompositeConstruct %118 %481 %482 %483 %484
OpImageWrite %41 %489 %490
OpReturn
OpFunctionEnd
%146 = OpFunction %5 None %143
%144 = OpFunctionParameter %5
%145 = OpFunctionParameter %5
%147 = OpLabel
%148 = OpUDiv %5 %149 %145
%150 = OpBitwiseAnd %5 %144 %148
OpReturnValue %150
OpFunctionEnd
#endif
