#version 460
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#if defined(GL_EXT_control_flow_attributes)
#extension GL_EXT_control_flow_attributes : require
#define SPIRV_CROSS_FLATTEN [[flatten]]
#define SPIRV_CROSS_BRANCH [[dont_flatten]]
#define SPIRV_CROSS_UNROLL [[unroll]]
#define SPIRV_CROSS_LOOP [[dont_unroll]]
#else
#define SPIRV_CROSS_FLATTEN
#define SPIRV_CROSS_BRANCH
#define SPIRV_CROSS_UNROLL
#define SPIRV_CROSS_LOOP
#endif
#extension GL_KHR_shader_subgroup_ballot : require
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(set = 15, binding = 0, std430) restrict readonly buffer SSBO_Offsets
{
    uvec2 _m0[];
} _13;

layout(set = 1, binding = 0, std430) restrict readonly buffer SSBO
{
    uint64_t _m0[];
} _19[];

layout(set = 1, binding = 0, std430) restrict readonly buffer _21_24
{
    uint64_t _m0[];
} _24[];

layout(set = 4, binding = 0, std430) writeonly buffer _26_29
{
    uint64_t _m0[];
} _29[];

layout(set = 4, binding = 0, std430) writeonly buffer _31_34
{
    uint64_t _m0[];
} _34[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
} registers;

uint64_t UDiv(uint64_t num, uint64_t den)
{
    uint64_t _186;
    SPIRV_CROSS_FLATTEN
    if (den == 0ul)
    {
        _186 = 18446744073709551615ul;
    }
    else
    {
        _186 = num / den;
    }
    return _186;
}

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _41 = registers._m4 + 1u;
    uvec2 _49 = _13._m0[subgroupBroadcastFirst(_41)] >> uvec2(3u);
    uvec2 _58 = _13._m0[subgroupBroadcastFirst(registers._m4)] >> uvec2(3u);
    uint _63 = registers._m1 + 1u;
    uvec2 _67 = _13._m0[subgroupBroadcastFirst(_63)] >> uvec2(3u);
    uvec2 _75 = _13._m0[subgroupBroadcastFirst(registers._m1)] >> uvec2(3u);
    uint _83 = gl_GlobalInvocationID.x * 6u;
    uint _90 = (_83 < _75.y) ? (_83 + _75.x) : 536870908u;
    u64vec3 _103 = u64vec3(_19[registers._m1]._m0[_90], _19[registers._m1]._m0[_90 + 1u], _19[registers._m1]._m0[_90 + 2u]);
    uint64_t _104 = _103.x;
    uint64_t _105 = _103.y;
    uint64_t _106 = _103.z;
    uint _109 = (gl_GlobalInvocationID.x * 6u) + 3u;
    uint _114 = (_109 < _75.y) ? (_109 + _75.x) : 536870908u;
    u64vec3 _123 = u64vec3(_19[registers._m1]._m0[_114], _19[registers._m1]._m0[_114 + 1u], _19[registers._m1]._m0[_114 + 2u]);
    uint64_t _124 = _123.x;
    uint64_t _125 = _123.y;
    uint64_t _126 = _123.z;
    uint _130 = gl_GlobalInvocationID.x << 3u;
    uint _131 = gl_GlobalInvocationID.x * 24u;
    uint _137 = (_131 < _58.y) ? (_131 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_137] = _124 + _104;
    _29[registers._m4]._m0[_137 + 1u] = _125 + _105;
    _29[registers._m4]._m0[_137 + 2u] = _126 + _106;
    uint _148 = (gl_GlobalInvocationID.x * 24u) + 3u;
    uint _153 = (_148 < _58.y) ? (_148 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_153] = _104 - _124;
    _29[registers._m4]._m0[_153 + 1u] = _105 - _125;
    _29[registers._m4]._m0[_153 + 2u] = _106 - _126;
    uint _164 = (gl_GlobalInvocationID.x * 24u) + 6u;
    uint _169 = (_164 < _58.y) ? (_164 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_169] = _124 * _104;
    _29[registers._m4]._m0[_169 + 1u] = _125 * _105;
    _29[registers._m4]._m0[_169 + 2u] = _126 * _106;
    uint _194 = (gl_GlobalInvocationID.x * 24u) + 9u;
    uint _199 = (_194 < _58.y) ? (_194 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_199] = UDiv(_104, _124);
    _29[registers._m4]._m0[_199 + 1u] = UDiv(_105, _125);
    _29[registers._m4]._m0[_199 + 2u] = UDiv(_106, _126);
    uint64_t _205 = _124 & 63ul;
    uint64_t _207 = _125 & 63ul;
    uint64_t _208 = _126 & 63ul;
    uint _215 = (gl_GlobalInvocationID.x * 24u) + 12u;
    uint _220 = (_215 < _58.y) ? (_215 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_220] = _104 << _205;
    _29[registers._m4]._m0[_220 + 1u] = _105 << _207;
    _29[registers._m4]._m0[_220 + 2u] = _106 << _208;
    uint _233 = (gl_GlobalInvocationID.x * 24u) + 15u;
    uint _238 = (_233 < _58.y) ? (_233 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_238] = _104 >> _205;
    _29[registers._m4]._m0[_238 + 1u] = _105 >> _207;
    _29[registers._m4]._m0[_238 + 2u] = _106 >> _208;
    uint _250 = (gl_GlobalInvocationID.x * 24u) + 18u;
    uint _255 = (_250 < _58.y) ? (_250 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_255] = uint64_t(int64_t(_104) >> int64_t(_205));
    _29[registers._m4]._m0[_255 + 1u] = uint64_t(int64_t(_105) >> int64_t(_207));
    _29[registers._m4]._m0[_255 + 2u] = uint64_t(int64_t(_106) >> int64_t(_208));
    uint _268 = (gl_GlobalInvocationID.x * 24u) + 21u;
    uint _273 = (_268 < _58.y) ? (_268 + _58.x) : 536870908u;
    _29[registers._m4]._m0[_273] = _124 & _104;
    _29[registers._m4]._m0[_273 + 1u] = _125 & _105;
    _29[registers._m4]._m0[_273 + 2u] = _126 & _106;
    uint _290 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 8u);
    uint _296 = (_290 < _67.y) ? (_290 + _67.x) : 536870908u;
    u64vec2 _303 = u64vec2(_24[_63]._m0[_296], _24[_63]._m0[_296 + 1u]);
    uint _306 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    uint _311 = (_306 < _49.y) ? (_306 + _49.x) : 536870908u;
    _34[_41]._m0[_311] = _303.x;
    _34[_41]._m0[_311 + 1u] = _303.y;
    _34[_41]._m0[_311 + 2u] = _106;
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 319
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability GroupNonUniformBallot
OpCapability RuntimeDescriptorArray
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %78
OpExecutionMode %3 LocalSize 128 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %16 "SSBO"
OpName %21 "SSBO"
OpName %26 "SSBO"
OpName %31 "SSBO"
OpName %178 "UDiv"
OpName %176 "num"
OpName %177 "den"
OpName %284 "ByteAddressMask"
OpName %282 "index"
OpName %283 "stride"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %15 ArrayStride 8
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %19 DescriptorSet 1
OpDecorate %19 Binding 0
OpDecorate %19 NonWritable
OpDecorate %19 Restrict
OpDecorate %20 ArrayStride 8
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %24 DescriptorSet 1
OpDecorate %24 Binding 0
OpDecorate %24 NonWritable
OpDecorate %24 Restrict
OpDecorate %25 ArrayStride 8
OpMemberDecorate %26 0 Offset 0
OpDecorate %26 Block
OpDecorate %29 DescriptorSet 4
OpDecorate %29 Binding 0
OpDecorate %29 NonReadable
OpDecorate %30 ArrayStride 8
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
OpDecorate %34 DescriptorSet 4
OpDecorate %34 Binding 0
OpDecorate %34 NonReadable
OpDecorate %78 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeInt 64 0
%15 = OpTypeRuntimeArray %14
%16 = OpTypeStruct %15
%17 = OpTypeRuntimeArray %16
%18 = OpTypePointer StorageBuffer %17
%19 = OpVariable %18 StorageBuffer
%20 = OpTypeRuntimeArray %14
%21 = OpTypeStruct %20
%22 = OpTypeRuntimeArray %21
%23 = OpTypePointer StorageBuffer %22
%24 = OpVariable %23 StorageBuffer
%25 = OpTypeRuntimeArray %14
%26 = OpTypeStruct %25
%27 = OpTypeRuntimeArray %26
%28 = OpTypePointer StorageBuffer %27
%29 = OpVariable %28 StorageBuffer
%30 = OpTypeRuntimeArray %14
%31 = OpTypeStruct %30
%32 = OpTypeRuntimeArray %31
%33 = OpTypePointer StorageBuffer %32
%34 = OpVariable %33 StorageBuffer
%35 = OpTypePointer StorageBuffer %31
%37 = OpTypePointer PushConstant %5
%39 = OpConstant %5 4
%42 = OpConstant %5 1
%44 = OpConstant %5 3
%45 = OpTypePointer StorageBuffer %9
%47 = OpConstant %5 0
%50 = OpConstantComposite %9 %44 %44
%51 = OpTypePointer StorageBuffer %26
%59 = OpTypePointer StorageBuffer %21
%68 = OpTypePointer StorageBuffer %16
%76 = OpTypeVector %5 3
%77 = OpTypePointer Input %76
%78 = OpVariable %77 Input
%79 = OpTypePointer Input %5
%84 = OpConstant %5 6
%88 = OpTypeBool
%91 = OpConstant %5 536870908
%92 = OpTypePointer StorageBuffer %14
%100 = OpConstant %5 2
%102 = OpTypeVector %14 3
%132 = OpConstant %5 24
%175 = OpTypeFunction %14 %14 %14
%180 = OpConstant %14 18446744073709551615
%184 = OpConstantNull %14
%193 = OpConstant %5 9
%206 = OpConstant %14 63
%214 = OpConstant %5 12
%230 = OpConstant %5 5
%232 = OpConstant %5 15
%249 = OpConstant %5 18
%265 = OpConstant %5 7
%267 = OpConstant %5 21
%281 = OpTypeFunction %5 %5 %5
%287 = OpConstant %5 4294967295
%291 = OpConstant %5 8
%302 = OpTypeVector %14 2
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %317
%317 = OpLabel
%38 = OpAccessChain %37 %8 %39
%40 = OpLoad %5 %38
%41 = OpIAdd %5 %40 %42
%36 = OpAccessChain %35 %34 %41
%43 = OpGroupNonUniformBroadcastFirst %5 %44 %41
%46 = OpAccessChain %45 %13 %47 %43
%48 = OpLoad %9 %46
%49 = OpShiftRightLogical %9 %48 %50
%53 = OpAccessChain %37 %8 %39
%54 = OpLoad %5 %53
%52 = OpAccessChain %51 %29 %54
%55 = OpGroupNonUniformBroadcastFirst %5 %44 %54
%56 = OpAccessChain %45 %13 %47 %55
%57 = OpLoad %9 %56
%58 = OpShiftRightLogical %9 %57 %50
%61 = OpAccessChain %37 %8 %42
%62 = OpLoad %5 %61
%63 = OpIAdd %5 %62 %42
%60 = OpAccessChain %59 %24 %63
%64 = OpGroupNonUniformBroadcastFirst %5 %44 %63
%65 = OpAccessChain %45 %13 %47 %64
%66 = OpLoad %9 %65
%67 = OpShiftRightLogical %9 %66 %50
%70 = OpAccessChain %37 %8 %42
%71 = OpLoad %5 %70
%69 = OpAccessChain %68 %19 %71
%72 = OpGroupNonUniformBroadcastFirst %5 %44 %71
%73 = OpAccessChain %45 %13 %47 %72
%74 = OpLoad %9 %73
%75 = OpShiftRightLogical %9 %74 %50
%80 = OpAccessChain %79 %78 %47
%81 = OpLoad %5 %80
%82 = OpShiftLeftLogical %5 %81 %42
%83 = OpIMul %5 %81 %84
%85 = OpCompositeExtract %5 %75 0
%86 = OpCompositeExtract %5 %75 1
%87 = OpIAdd %5 %83 %85
%89 = OpULessThan %88 %83 %86
%90 = OpSelect %5 %89 %87 %91
%93 = OpAccessChain %92 %69 %47 %90
%94 = OpLoad %14 %93
%96 = OpIAdd %5 %90 %42
%95 = OpAccessChain %92 %69 %47 %96
%97 = OpLoad %14 %95
%99 = OpIAdd %5 %90 %100
%98 = OpAccessChain %92 %69 %47 %99
%101 = OpLoad %14 %98
%103 = OpCompositeConstruct %102 %94 %97 %101
%104 = OpCompositeExtract %14 %103 0
%105 = OpCompositeExtract %14 %103 1
%106 = OpCompositeExtract %14 %103 2
%107 = OpBitwiseOr %5 %82 %42
%108 = OpIMul %5 %81 %84
%109 = OpIAdd %5 %108 %44
%110 = OpCompositeExtract %5 %75 0
%111 = OpCompositeExtract %5 %75 1
%112 = OpIAdd %5 %109 %110
%113 = OpULessThan %88 %109 %111
%114 = OpSelect %5 %113 %112 %91
%115 = OpAccessChain %92 %69 %47 %114
%116 = OpLoad %14 %115
%118 = OpIAdd %5 %114 %42
%117 = OpAccessChain %92 %69 %47 %118
%119 = OpLoad %14 %117
%121 = OpIAdd %5 %114 %100
%120 = OpAccessChain %92 %69 %47 %121
%122 = OpLoad %14 %120
%123 = OpCompositeConstruct %102 %116 %119 %122
%124 = OpCompositeExtract %14 %123 0
%125 = OpCompositeExtract %14 %123 1
%126 = OpCompositeExtract %14 %123 2
%127 = OpIAdd %14 %124 %104
%128 = OpIAdd %14 %125 %105
%129 = OpIAdd %14 %126 %106
%130 = OpShiftLeftLogical %5 %81 %44
%131 = OpIMul %5 %81 %132
%133 = OpCompositeExtract %5 %58 0
%134 = OpCompositeExtract %5 %58 1
%135 = OpIAdd %5 %131 %133
%136 = OpULessThan %88 %131 %134
%137 = OpSelect %5 %136 %135 %91
%138 = OpAccessChain %92 %52 %47 %137
OpStore %138 %127
%140 = OpIAdd %5 %137 %42
%139 = OpAccessChain %92 %52 %47 %140
OpStore %139 %128
%142 = OpIAdd %5 %137 %100
%141 = OpAccessChain %92 %52 %47 %142
OpStore %141 %129
%143 = OpISub %14 %104 %124
%144 = OpISub %14 %105 %125
%145 = OpISub %14 %106 %126
%146 = OpBitwiseOr %5 %130 %42
%147 = OpIMul %5 %81 %132
%148 = OpIAdd %5 %147 %44
%149 = OpCompositeExtract %5 %58 0
%150 = OpCompositeExtract %5 %58 1
%151 = OpIAdd %5 %148 %149
%152 = OpULessThan %88 %148 %150
%153 = OpSelect %5 %152 %151 %91
%154 = OpAccessChain %92 %52 %47 %153
OpStore %154 %143
%156 = OpIAdd %5 %153 %42
%155 = OpAccessChain %92 %52 %47 %156
OpStore %155 %144
%158 = OpIAdd %5 %153 %100
%157 = OpAccessChain %92 %52 %47 %158
OpStore %157 %145
%159 = OpIMul %14 %124 %104
%160 = OpIMul %14 %125 %105
%161 = OpIMul %14 %126 %106
%162 = OpBitwiseOr %5 %130 %100
%163 = OpIMul %5 %81 %132
%164 = OpIAdd %5 %163 %84
%165 = OpCompositeExtract %5 %58 0
%166 = OpCompositeExtract %5 %58 1
%167 = OpIAdd %5 %164 %165
%168 = OpULessThan %88 %164 %166
%169 = OpSelect %5 %168 %167 %91
%170 = OpAccessChain %92 %52 %47 %169
OpStore %170 %159
%172 = OpIAdd %5 %169 %42
%171 = OpAccessChain %92 %52 %47 %172
OpStore %171 %160
%174 = OpIAdd %5 %169 %100
%173 = OpAccessChain %92 %52 %47 %174
OpStore %173 %161
%188 = OpFunctionCall %14 %178 %104 %124
%189 = OpFunctionCall %14 %178 %105 %125
%190 = OpFunctionCall %14 %178 %106 %126
%191 = OpBitwiseOr %5 %130 %44
%192 = OpIMul %5 %81 %132
%194 = OpIAdd %5 %192 %193
%195 = OpCompositeExtract %5 %58 0
%196 = OpCompositeExtract %5 %58 1
%197 = OpIAdd %5 %194 %195
%198 = OpULessThan %88 %194 %196
%199 = OpSelect %5 %198 %197 %91
%200 = OpAccessChain %92 %52 %47 %199
OpStore %200 %188
%202 = OpIAdd %5 %199 %42
%201 = OpAccessChain %92 %52 %47 %202
OpStore %201 %189
%204 = OpIAdd %5 %199 %100
%203 = OpAccessChain %92 %52 %47 %204
OpStore %203 %190
%205 = OpBitwiseAnd %14 %124 %206
%207 = OpBitwiseAnd %14 %125 %206
%208 = OpBitwiseAnd %14 %126 %206
%209 = OpShiftLeftLogical %14 %104 %205
%210 = OpShiftLeftLogical %14 %105 %207
%211 = OpShiftLeftLogical %14 %106 %208
%212 = OpBitwiseOr %5 %130 %39
%213 = OpIMul %5 %81 %132
%215 = OpIAdd %5 %213 %214
%216 = OpCompositeExtract %5 %58 0
%217 = OpCompositeExtract %5 %58 1
%218 = OpIAdd %5 %215 %216
%219 = OpULessThan %88 %215 %217
%220 = OpSelect %5 %219 %218 %91
%221 = OpAccessChain %92 %52 %47 %220
OpStore %221 %209
%223 = OpIAdd %5 %220 %42
%222 = OpAccessChain %92 %52 %47 %223
OpStore %222 %210
%225 = OpIAdd %5 %220 %100
%224 = OpAccessChain %92 %52 %47 %225
OpStore %224 %211
%226 = OpShiftRightLogical %14 %104 %205
%227 = OpShiftRightLogical %14 %105 %207
%228 = OpShiftRightLogical %14 %106 %208
%229 = OpBitwiseOr %5 %130 %230
%231 = OpIMul %5 %81 %132
%233 = OpIAdd %5 %231 %232
%234 = OpCompositeExtract %5 %58 0
%235 = OpCompositeExtract %5 %58 1
%236 = OpIAdd %5 %233 %234
%237 = OpULessThan %88 %233 %235
%238 = OpSelect %5 %237 %236 %91
%239 = OpAccessChain %92 %52 %47 %238
OpStore %239 %226
%241 = OpIAdd %5 %238 %42
%240 = OpAccessChain %92 %52 %47 %241
OpStore %240 %227
%243 = OpIAdd %5 %238 %100
%242 = OpAccessChain %92 %52 %47 %243
OpStore %242 %228
%244 = OpShiftRightArithmetic %14 %104 %205
%245 = OpShiftRightArithmetic %14 %105 %207
%246 = OpShiftRightArithmetic %14 %106 %208
%247 = OpBitwiseOr %5 %130 %84
%248 = OpIMul %5 %81 %132
%250 = OpIAdd %5 %248 %249
%251 = OpCompositeExtract %5 %58 0
%252 = OpCompositeExtract %5 %58 1
%253 = OpIAdd %5 %250 %251
%254 = OpULessThan %88 %250 %252
%255 = OpSelect %5 %254 %253 %91
%256 = OpAccessChain %92 %52 %47 %255
OpStore %256 %244
%258 = OpIAdd %5 %255 %42
%257 = OpAccessChain %92 %52 %47 %258
OpStore %257 %245
%260 = OpIAdd %5 %255 %100
%259 = OpAccessChain %92 %52 %47 %260
OpStore %259 %246
%261 = OpBitwiseAnd %14 %124 %104
%262 = OpBitwiseAnd %14 %125 %105
%263 = OpBitwiseAnd %14 %126 %106
%264 = OpBitwiseOr %5 %130 %265
%266 = OpIMul %5 %81 %132
%268 = OpIAdd %5 %266 %267
%269 = OpCompositeExtract %5 %58 0
%270 = OpCompositeExtract %5 %58 1
%271 = OpIAdd %5 %268 %269
%272 = OpULessThan %88 %268 %270
%273 = OpSelect %5 %272 %271 %91
%274 = OpAccessChain %92 %52 %47 %273
OpStore %274 %261
%276 = OpIAdd %5 %273 %42
%275 = OpAccessChain %92 %52 %47 %276
OpStore %275 %262
%278 = OpIAdd %5 %273 %100
%277 = OpAccessChain %92 %52 %47 %278
OpStore %277 %263
%279 = OpIMul %5 %81 %132
%280 = OpIMul %5 %81 %44
%290 = OpFunctionCall %5 %284 %280 %291
%292 = OpCompositeExtract %5 %67 0
%293 = OpCompositeExtract %5 %67 1
%294 = OpIAdd %5 %290 %292
%295 = OpULessThan %88 %290 %293
%296 = OpSelect %5 %295 %294 %91
%297 = OpAccessChain %92 %60 %47 %296
%298 = OpLoad %14 %297
%300 = OpIAdd %5 %296 %42
%299 = OpAccessChain %92 %60 %47 %300
%301 = OpLoad %14 %299
%303 = OpCompositeConstruct %302 %298 %301
%304 = OpCompositeExtract %14 %303 0
%305 = OpCompositeExtract %14 %303 1
%306 = OpFunctionCall %5 %284 %81 %291
%307 = OpCompositeExtract %5 %49 0
%308 = OpCompositeExtract %5 %49 1
%309 = OpIAdd %5 %306 %307
%310 = OpULessThan %88 %306 %308
%311 = OpSelect %5 %310 %309 %91
%312 = OpAccessChain %92 %36 %47 %311
OpStore %312 %304
%314 = OpIAdd %5 %311 %42
%313 = OpAccessChain %92 %36 %47 %314
OpStore %313 %305
%316 = OpIAdd %5 %311 %100
%315 = OpAccessChain %92 %36 %47 %316
OpStore %315 %106
OpReturn
OpFunctionEnd
%178 = OpFunction %14 None %175
%176 = OpFunctionParameter %14
%177 = OpFunctionParameter %14
%179 = OpLabel
%183 = OpIEqual %88 %177 %184
OpSelectionMerge %182 Flatten
OpBranchConditional %183 %182 %181
%181 = OpLabel
%185 = OpUDiv %14 %176 %177
OpBranch %182
%182 = OpLabel
%186 = OpPhi %14 %180 %179 %185 %181
OpReturnValue %186
OpFunctionEnd
%284 = OpFunction %5 None %281
%282 = OpFunctionParameter %5
%283 = OpFunctionParameter %5
%285 = OpLabel
%286 = OpUDiv %5 %287 %283
%288 = OpBitwiseAnd %5 %282 %286
OpReturnValue %288
OpFunctionEnd
#endif
