#version 460
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(buffer_reference) buffer PhysicalPointerFloat4NonWriteArray;
layout(buffer_reference) buffer PhysicalPointerFloat4NonWriteCBVArray;
layout(buffer_reference) buffer PhysicalPointerFloat4CoherentArray;
layout(buffer_reference) buffer PhysicalPointerHalfArray;
layout(buffer_reference) buffer PhysicalPointerHalf2Array;
layout(buffer_reference) buffer PhysicalPointerHalf3;
layout(buffer_reference) buffer PhysicalPointerHalf4Array;
layout(buffer_reference) buffer PhysicalPointerUint2Array;

struct AddCarry
{
    uint _m0;
    uint _m1;
};

float16_t _82;
uint _133;

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer PhysicalPointerFloat4NonWriteArray
{
    vec4 value[];
};

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer PhysicalPointerFloat4NonWriteCBVArray
{
    vec4 value[4096];
};

layout(buffer_reference, buffer_reference_align = 16, std430) coherent buffer PhysicalPointerFloat4CoherentArray
{
    vec4 value[];
};

layout(buffer_reference, buffer_reference_align = 2, std430) buffer PhysicalPointerHalfArray
{
    float16_t value[];
};

layout(buffer_reference, buffer_reference_align = 4, std430) buffer PhysicalPointerHalf2Array
{
    f16vec2 value[];
};

layout(buffer_reference, buffer_reference_align = 2, std430) buffer PhysicalPointerHalf3
{
    f16vec3 value;
};

layout(buffer_reference, buffer_reference_align = 8, std430) buffer PhysicalPointerHalf4Array
{
    f16vec4 value[];
};

layout(buffer_reference, buffer_reference_align = 8, std430) buffer PhysicalPointerUint2Array
{
    uvec2 value[];
};

layout(push_constant, std430) uniform RootConstants
{
    uvec2 _m0;
    uvec2 _m1;
    uvec2 _m2;
    uvec2 _m3;
} registers;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    vec4 _37 = PhysicalPointerFloat4NonWriteArray(registers._m1).value[gl_GlobalInvocationID.x];
    vec4 _48 = PhysicalPointerFloat4NonWriteCBVArray(registers._m0).value[gl_GlobalInvocationID.x];
    PhysicalPointerFloat4CoherentArray(registers._m2).value[gl_GlobalInvocationID.x] = vec4(_48.x + _37.x, _48.y + _37.y, _48.z + _37.z, _48.w + _37.w);
    PhysicalPointerHalfArray(registers._m3).value[ByteAddressMask(gl_GlobalInvocationID.x, 2u)] = float16_t(1.0);
    PhysicalPointerHalf2Array(registers._m3).value[ByteAddressMask(gl_GlobalInvocationID.x, 4u)] = f16vec2(float16_t(1.0), float16_t(2.0));
    AddCarry _103;
    _103._m0 = uaddCarry(registers._m3.x, gl_GlobalInvocationID.x * 6u, _103._m1);
    PhysicalPointerHalf3(uvec2(_103._m0, registers._m3.y + _103._m1)).value = f16vec3(float16_t(1.0), float16_t(2.0), float16_t(3.0));
    PhysicalPointerHalf4Array(registers._m3).value[ByteAddressMask(gl_GlobalInvocationID.x, 8u)] = f16vec4(float16_t(1.0), float16_t(2.0), float16_t(3.0), float16_t(4.0));
    PhysicalPointerUint2Array(registers._m3).value[ByteAddressMask(gl_GlobalInvocationID.x, 8u)] = uvec2(4u, 5u);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 137
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability DenormPreserve
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %25
OpExecutionMode %3 LocalSize 1 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "RootConstants"
OpName %9 "registers"
OpName %32 "PhysicalPointerFloat4NonWriteArray"
OpMemberName %32 0 "value"
OpName %44 "PhysicalPointerFloat4NonWriteCBVArray"
OpMemberName %44 0 "value"
OpName %58 "PhysicalPointerFloat4CoherentArray"
OpMemberName %58 0 "value"
OpName %67 "ByteAddressMask"
OpName %65 "index"
OpName %66 "stride"
OpName %76 "PhysicalPointerHalfArray"
OpMemberName %76 0 "value"
OpName %88 "PhysicalPointerHalf2Array"
OpMemberName %88 0 "value"
OpName %98 "PhysicalPointerHalf3"
OpMemberName %98 0 "value"
OpName %102 "AddCarry"
OpName %118 "PhysicalPointerHalf4Array"
OpMemberName %118 0 "value"
OpName %127 "PhysicalPointerUint2Array"
OpMemberName %127 0 "value"
OpDecorate %7 Block
OpMemberDecorate %7 0 Offset 0
OpMemberDecorate %7 1 Offset 8
OpMemberDecorate %7 2 Offset 16
OpMemberDecorate %7 3 Offset 24
OpDecorate %25 BuiltIn GlobalInvocationId
OpDecorate %31 ArrayStride 16
OpMemberDecorate %32 0 Offset 0
OpDecorate %32 Block
OpMemberDecorate %32 0 NonWritable
OpDecorate %43 ArrayStride 16
OpMemberDecorate %44 0 Offset 0
OpDecorate %44 Block
OpMemberDecorate %44 0 NonWritable
OpDecorate %57 ArrayStride 16
OpMemberDecorate %58 0 Offset 0
OpDecorate %58 Block
OpMemberDecorate %58 0 Coherent
OpDecorate %75 ArrayStride 2
OpMemberDecorate %76 0 Offset 0
OpDecorate %76 Block
OpDecorate %87 ArrayStride 4
OpMemberDecorate %88 0 Offset 0
OpDecorate %88 Block
OpMemberDecorate %98 0 Offset 0
OpDecorate %98 Block
OpDecorate %117 ArrayStride 8
OpMemberDecorate %118 0 Offset 0
OpDecorate %118 Block
OpDecorate %126 ArrayStride 8
OpMemberDecorate %127 0 Offset 0
OpDecorate %127 Block
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 2
%7 = OpTypeStruct %6 %6 %6 %6
%8 = OpTypePointer PushConstant %7
%9 = OpVariable %8 PushConstant
%10 = OpTypePointer PushConstant %6
%12 = OpConstant %5 3
%15 = OpConstant %5 2
%18 = OpConstant %5 1
%21 = OpConstant %5 0
%23 = OpTypeVector %5 3
%24 = OpTypePointer Input %23
%25 = OpVariable %24 Input
%26 = OpTypePointer Input %5
%29 = OpTypeFloat 32
%30 = OpTypeVector %29 4
%31 = OpTypeRuntimeArray %30
%32 = OpTypeStruct %31
%33 = OpTypePointer PhysicalStorageBuffer %32
%35 = OpTypePointer PhysicalStorageBuffer %30
%42 = OpConstant %5 4096
%43 = OpTypeArray %30 %42
%44 = OpTypeStruct %43
%45 = OpTypePointer PhysicalStorageBuffer %44
%57 = OpTypeRuntimeArray %30
%58 = OpTypeStruct %57
%59 = OpTypePointer PhysicalStorageBuffer %58
%64 = OpTypeFunction %5 %5 %5
%70 = OpConstant %5 4294967295
%74 = OpTypeFloat 16
%75 = OpTypeRuntimeArray %74
%76 = OpTypeStruct %75
%77 = OpTypePointer PhysicalStorageBuffer %76
%79 = OpTypePointer PhysicalStorageBuffer %74
%81 = OpConstant %74 0x1p+0
%85 = OpConstant %5 4
%86 = OpTypeVector %74 2
%87 = OpTypeRuntimeArray %86
%88 = OpTypeStruct %87
%89 = OpTypePointer PhysicalStorageBuffer %88
%91 = OpTypePointer PhysicalStorageBuffer %86
%93 = OpConstant %74 0x1p+1
%96 = OpConstant %5 6
%97 = OpTypeVector %74 3
%98 = OpTypeStruct %97
%99 = OpTypePointer PhysicalStorageBuffer %98
%102 = OpTypeStruct %5 %5
%109 = OpTypePointer PhysicalStorageBuffer %97
%111 = OpConstant %74 0x1.8p+1
%115 = OpConstant %5 8
%116 = OpTypeVector %74 4
%117 = OpTypeRuntimeArray %116
%118 = OpTypeStruct %117
%119 = OpTypePointer PhysicalStorageBuffer %118
%121 = OpTypePointer PhysicalStorageBuffer %116
%123 = OpConstant %74 0x1p+2
%126 = OpTypeRuntimeArray %6
%127 = OpTypeStruct %126
%128 = OpTypePointer PhysicalStorageBuffer %127
%130 = OpTypePointer PhysicalStorageBuffer %6
%132 = OpConstant %5 5
%3 = OpFunction %1 None %2
%4 = OpLabel
%82 = OpUndef %74
%133 = OpUndef %5
OpBranch %135
%135 = OpLabel
%11 = OpAccessChain %10 %9 %12
%13 = OpLoad %6 %11
%14 = OpAccessChain %10 %9 %15
%16 = OpLoad %6 %14
%17 = OpAccessChain %10 %9 %18
%19 = OpLoad %6 %17
%20 = OpAccessChain %10 %9 %21
%22 = OpLoad %6 %20
%27 = OpAccessChain %26 %25 %21
%28 = OpLoad %5 %27
%34 = OpBitcast %33 %19
%36 = OpInBoundsAccessChain %35 %34 %21 %28
%37 = OpLoad %30 %36 Aligned 16
%38 = OpCompositeExtract %29 %37 0
%39 = OpCompositeExtract %29 %37 1
%40 = OpCompositeExtract %29 %37 2
%41 = OpCompositeExtract %29 %37 3
%46 = OpBitcast %45 %22
%47 = OpInBoundsAccessChain %35 %46 %21 %28
%48 = OpLoad %30 %47 Aligned 16
%49 = OpCompositeExtract %29 %48 0
%50 = OpCompositeExtract %29 %48 1
%51 = OpCompositeExtract %29 %48 2
%52 = OpCompositeExtract %29 %48 3
%53 = OpFAdd %29 %49 %38
%54 = OpFAdd %29 %50 %39
%55 = OpFAdd %29 %51 %40
%56 = OpFAdd %29 %52 %41
%60 = OpBitcast %59 %16
%61 = OpInBoundsAccessChain %35 %60 %21 %28
%62 = OpCompositeConstruct %30 %53 %54 %55 %56
OpStore %61 %62 Aligned 16
%63 = OpShiftLeftLogical %5 %28 %18
%73 = OpFunctionCall %5 %67 %28 %15
%78 = OpBitcast %77 %13
%80 = OpInBoundsAccessChain %79 %78 %21 %73
OpStore %80 %81 Aligned 2
%83 = OpShiftLeftLogical %5 %28 %15
%84 = OpFunctionCall %5 %67 %28 %85
%90 = OpBitcast %89 %13
%92 = OpInBoundsAccessChain %91 %90 %21 %84
%94 = OpCompositeConstruct %86 %81 %93
OpStore %92 %94 Aligned 4
%95 = OpIMul %5 %28 %96
%100 = OpCompositeExtract %5 %13 0
%101 = OpCompositeExtract %5 %13 1
%103 = OpIAddCarry %102 %100 %95
%104 = OpCompositeExtract %5 %103 0
%105 = OpCompositeExtract %5 %103 1
%106 = OpIAdd %5 %101 %105
%107 = OpCompositeConstruct %6 %104 %106
%108 = OpBitcast %99 %107
%110 = OpInBoundsAccessChain %109 %108 %21
%112 = OpCompositeConstruct %97 %81 %93 %111
OpStore %110 %112 Aligned 2
%113 = OpShiftLeftLogical %5 %28 %12
%114 = OpFunctionCall %5 %67 %28 %115
%120 = OpBitcast %119 %13
%122 = OpInBoundsAccessChain %121 %120 %21 %114
%124 = OpCompositeConstruct %116 %81 %93 %111 %123
OpStore %122 %124 Aligned 8
%125 = OpFunctionCall %5 %67 %28 %115
%129 = OpBitcast %128 %13
%131 = OpInBoundsAccessChain %130 %129 %21 %125
%134 = OpCompositeConstruct %6 %85 %132
OpStore %131 %134 Aligned 8
OpReturn
OpFunctionEnd
%67 = OpFunction %5 None %64
%65 = OpFunctionParameter %5
%66 = OpFunctionParameter %5
%68 = OpLabel
%69 = OpUDiv %5 %70 %66
%71 = OpBitwiseAnd %5 %65 %69
OpReturnValue %71
OpFunctionEnd
#endif
