#version 460
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer SSBO
{
    uint _m0[];
} _9;

void main()
{
    uint _19 = atomicMin(_9._m0[gl_GlobalInvocationID.x], 4294967293u);
    uint _24 = atomicMax(_9._m0[gl_GlobalInvocationID.x + 1u], _19);
    _9._m0[gl_GlobalInvocationID.x + 3u] = _9._m0[gl_GlobalInvocationID.x + 2u] + _24;
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 35
; Schema: 0
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %12
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %12 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 3
%11 = OpTypePointer Input %10
%12 = OpVariable %11 Input
%13 = OpTypePointer Input %5
%15 = OpConstant %5 0
%17 = OpTypePointer StorageBuffer %5
%20 = OpConstant %5 1
%21 = OpConstant %5 4294967293
%26 = OpConstant %5 2
%31 = OpConstant %5 3
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %33
%33 = OpLabel
%14 = OpAccessChain %13 %12 %15
%16 = OpLoad %5 %14
%18 = OpAccessChain %17 %9 %15 %16
%19 = OpAtomicSMin %5 %18 %20 %15 %21
%22 = OpIAdd %5 %16 %20
%23 = OpAccessChain %17 %9 %15 %22
%24 = OpAtomicSMax %5 %23 %20 %15 %19
%25 = OpIAdd %5 %16 %26
%27 = OpAccessChain %17 %9 %15 %25
%28 = OpLoad %5 %27
%29 = OpIAdd %5 %28 %24
%30 = OpIAdd %5 %16 %31
%32 = OpAccessChain %17 %9 %15 %30
OpStore %32 %29
OpReturn
OpFunctionEnd
#endif
