#version 460
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer SSBO
{
    uint _m0[];
} _9;

void main()
{
    uint _21 = atomicAdd(_9._m0[gl_GlobalInvocationID.x + 3u], 1u);
    uint _28 = atomicCompSwap(_9._m0[gl_GlobalInvocationID.x + 4u], _21, _21 + 2u);
    _9._m0[gl_GlobalInvocationID.x + 6u] = _9._m0[gl_GlobalInvocationID.x + 5u] ^ _28;
    if (uint(_9._m0.length()) == 0u)
    {
        _9._m0[0u] = _21;
    }
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 45
; Schema: 0
OpCapability Shader
OpCapability ImageQuery
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %12
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %12 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 3
%11 = OpTypePointer Input %10
%12 = OpVariable %11 Input
%13 = OpTypePointer Input %5
%15 = OpConstant %5 0
%18 = OpConstant %5 3
%19 = OpTypePointer StorageBuffer %5
%22 = OpConstant %5 1
%24 = OpConstant %5 2
%26 = OpConstant %5 4
%30 = OpConstant %5 5
%35 = OpConstant %5 6
%38 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %41
%41 = OpLabel
%14 = OpAccessChain %13 %12 %15
%16 = OpLoad %5 %14
%17 = OpIAdd %5 %16 %18
%20 = OpAccessChain %19 %9 %15 %17
%21 = OpAtomicIAdd %5 %20 %22 %15 %22
%23 = OpIAdd %5 %21 %24
%25 = OpIAdd %5 %16 %26
%27 = OpAccessChain %19 %9 %15 %25
%28 = OpAtomicCompareExchange %5 %27 %22 %15 %15 %23 %21
%29 = OpIAdd %5 %16 %30
%31 = OpAccessChain %19 %9 %15 %29
%32 = OpLoad %5 %31
%33 = OpBitwiseXor %5 %32 %28
%34 = OpIAdd %5 %16 %35
%36 = OpAccessChain %19 %9 %15 %34
OpStore %36 %33
%37 = OpArrayLength %5 %9 0
%39 = OpIEqual %38 %37 %15
OpSelectionMerge %43 None
OpBranchConditional %39 %42 %43
%42 = OpLabel
%40 = OpAccessChain %19 %9 %15 %15
OpStore %40 %21
OpBranch %43
%43 = OpLabel
OpReturn
OpFunctionEnd
#endif
