#version 460
#extension GL_ARB_sparse_texture2 : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct SparseTexel
{
    uint _m0;
    uvec4 _m1;
};

struct _32
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
};

layout(set = 0, binding = 0, r32ui) uniform uimageBuffer _8;

void main()
{
    uint _19 = imageAtomicAdd(_8, int(gl_GlobalInvocationID.x), 1u);
    uint _47;
    uvec4 _48;
    _47 = sparseImageLoadARB(_8, int(gl_GlobalInvocationID.x + 2u), _48);
    SparseTexel _25 = SparseTexel(_47, _48);
    uvec4 _27 = _25._m1;
    _32 _33 = _32(_27.x, _27.y, _27.z, _27.w, _25._m0);
    imageStore(_8, int(gl_GlobalInvocationID.x + 1u), uvec4(_33._m0));
    if (sparseTexelsResidentARB(int(_33._m4)))
    {
        imageStore(_8, int(gl_GlobalInvocationID.x + 3u), uvec4(_19));
    }
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 47
; Schema: 0
OpCapability Shader
OpCapability SparseResidency
OpCapability ImageBuffer
OpCapability StorageImageWriteWithoutFormat
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %12
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %24 "SparseTexel"
OpName %32 ""
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %12 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%10 = OpTypeVector %5 3
%11 = OpTypePointer Input %10
%12 = OpVariable %11 Input
%13 = OpTypePointer Input %5
%15 = OpConstant %5 0
%17 = OpTypePointer Image %5
%20 = OpConstant %5 1
%22 = OpConstant %5 2
%23 = OpTypeVector %5 4
%24 = OpTypeStruct %5 %23
%32 = OpTypeStruct %5 %5 %5 %5 %5
%36 = OpTypeBool
%41 = OpConstant %5 3
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %43
%43 = OpLabel
%9 = OpLoad %6 %8
%14 = OpAccessChain %13 %12 %15
%16 = OpLoad %5 %14
%18 = OpImageTexelPointer %17 %8 %16 %15
%19 = OpAtomicIAdd %5 %18 %20 %15 %20
%21 = OpIAdd %5 %16 %22
%25 = OpImageSparseRead %24 %9 %21
%26 = OpCompositeExtract %5 %25 0
%27 = OpCompositeExtract %23 %25 1
%28 = OpCompositeExtract %5 %27 0
%29 = OpCompositeExtract %5 %27 1
%30 = OpCompositeExtract %5 %27 2
%31 = OpCompositeExtract %5 %27 3
%33 = OpCompositeConstruct %32 %28 %29 %30 %31 %26
%34 = OpCompositeExtract %5 %33 0
%35 = OpCompositeExtract %5 %33 4
%37 = OpImageSparseTexelsResident %36 %35
%38 = OpIAdd %5 %16 %20
%39 = OpCompositeConstruct %23 %34 %34 %34 %34
OpImageWrite %9 %38 %39
OpSelectionMerge %45 None
OpBranchConditional %37 %44 %45
%44 = OpLabel
%40 = OpIAdd %5 %16 %41
%42 = OpCompositeConstruct %23 %19 %19 %19 %19
OpImageWrite %9 %40 %42
OpBranch %45
%45 = OpLabel
OpReturn
OpFunctionEnd
#endif
