#version 460
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, r32ui) uniform uimageBuffer _8;

void main()
{
    imageStore(_8, int((gl_GlobalInvocationID.x + 1u) % uint(imageSize(_8))), uvec4(imageLoad(_8, int(gl_GlobalInvocationID.x)).x + 1u));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 28
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability ImageQuery
OpCapability StorageImageWriteWithoutFormat
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %12
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %12 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%10 = OpTypeVector %5 3
%11 = OpTypePointer Input %10
%12 = OpVariable %11 Input
%13 = OpTypePointer Input %5
%15 = OpConstant %5 0
%18 = OpTypeVector %5 4
%22 = OpConstant %5 1
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %26
%26 = OpLabel
%9 = OpLoad %6 %8
%14 = OpAccessChain %13 %12 %15
%16 = OpLoad %5 %14
%17 = OpImageQuerySize %5 %9
%19 = OpImageRead %18 %9 %16
%20 = OpCompositeExtract %5 %19 0
%21 = OpIAdd %5 %20 %22
%23 = OpIAdd %5 %16 %22
%24 = OpUMod %5 %23 %17
%25 = OpCompositeConstruct %18 %21 %21 %21 %21
OpImageWrite %9 %24 %25
OpReturn
OpFunctionEnd
#endif
