#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require

layout(set = 0, binding = 0, std430) restrict readonly buffer TSSBO
{
    uint _m0[];
} T;

layout(set = 0, binding = 0, std430) restrict readonly buffer T_1
{
    uvec2 _m0[];
} T_2;

layout(set = 0, binding = 1, std430) restrict readonly buffer TsSSBO
{
    uint _m0[];
} Ts[2];

layout(set = 0, binding = 4, std430) restrict readonly buffer TBSSBO
{
    uint _m0[];
} TB;

layout(set = 0, binding = 0, std430) buffer USSBO
{
    uint _m0[];
} U;

layout(set = 0, binding = 0, std140) uniform CUBO
{
    vec4 _m0[1024];
} C;

layout(set = 0, binding = 1, std140) uniform CsUBO
{
    vec4 _m0[1024];
} Cs[2];

layout(set = 0, binding = 3) uniform samplerBuffer B;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _62 = atomicAdd(U._m0[0u], floatBitsToUint(C._m0[1u]).x);
    uint _70 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x));
    uint _77 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(floatBitsToUint(Cs[0u]._m0[1u]).x));
    uint _84 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(floatBitsToUint(Cs[0u]._m0[gl_LaunchIDEXT.x]).x));
    uint _88 = atomicAdd(U._m0[0u], T._m0[2u]);
    uint _92 = atomicAdd(U._m0[0u], TB._m0[0u]);
    uint _99 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(T_2._m0[gl_LaunchIDEXT.x].y));
    uint _103 = 1u * 2u;
    uint _110 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(T._m0[_103 + (((gl_LaunchIDEXT.x << 2u) & 4u) >> 2u)]));
    uint _117 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(Ts[0u]._m0[1u]));
    uint _132 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(TB._m0[ByteAddressMask(gl_LaunchIDEXT.x, 4u)]));
    uint _137 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(U._m0[2u]));
    uint _144 = atomicAdd(U._m0[1u], uint(subgroupBroadcastFirst(texelFetch(B, int(0u)).x)));
    uint _150 = atomicAdd(U._m0[0u], floatBitsToUint(C._m0[1u]).x);
    uint _157 = atomicAdd(U._m0[0u], subgroupAdd(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x));
    uint _164 = atomicAdd(U._m0[0u], subgroupOr(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x));
    uint _173 = atomicAdd(U._m0[0u], uint(subgroupAllEqual(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x)));
    uint _182 = atomicAdd(U._m0[0u], subgroupBallot(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x != 0u).x);
    uint _191 = atomicAdd(U._m0[0u], uint(subgroupAny(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x != 0u)));
    uint _200 = atomicAdd(U._m0[0u], uint(subgroupAll(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x != 0u)));
    uint _208 = atomicAdd(U._m0[1u], subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(C._m0[gl_LaunchIDEXT.x]).x)));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.4
; Generator: Unknown(30017); 21022
; Bound: 211
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledImageArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability StorageImageArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpCapability RayTracingKHR
OpCapability RuntimeDescriptorArray
OpCapability UniformBufferArrayNonUniformIndexing
OpCapability SampledImageArrayNonUniformIndexing
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability StorageImageArrayNonUniformIndexing
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_ray_tracing"
OpMemoryModel Logical GLSL450
OpEntryPoint RayGenerationKHR %3 "main" %9 %14 %20 %24 %28 %32 %38 %43 %49
OpName %3 "main"
OpName %7 "TSSBO"
OpName %9 "T"
OpName %12 "TSSBO"
OpName %14 "T"
OpName %16 "TsSSBO"
OpName %20 "Ts"
OpName %24 "B"
OpName %26 "TBSSBO"
OpName %28 "TB"
OpName %30 "USSBO"
OpName %32 "U"
OpName %36 "CUBO"
OpName %38 "C"
OpName %40 "CsUBO"
OpName %43 "Cs"
OpName %121 "ByteAddressMask"
OpName %119 "index"
OpName %120 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonWritable
OpDecorate %14 Restrict
OpDecorate %15 ArrayStride 4
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 1
OpDecorate %20 NonWritable
OpDecorate %20 Restrict
OpDecorate %24 DescriptorSet 0
OpDecorate %24 Binding 3
OpDecorate %25 ArrayStride 4
OpMemberDecorate %26 0 Offset 0
OpDecorate %26 Block
OpDecorate %28 DescriptorSet 0
OpDecorate %28 Binding 4
OpDecorate %28 NonWritable
OpDecorate %28 Restrict
OpDecorate %29 ArrayStride 4
OpMemberDecorate %30 0 Offset 0
OpDecorate %30 Block
OpDecorate %32 DescriptorSet 0
OpDecorate %32 Binding 0
OpDecorate %35 ArrayStride 16
OpMemberDecorate %36 0 Offset 0
OpDecorate %36 Block
OpDecorate %38 DescriptorSet 0
OpDecorate %38 Binding 0
OpDecorate %39 ArrayStride 16
OpMemberDecorate %40 0 Offset 0
OpDecorate %40 Block
OpDecorate %43 DescriptorSet 0
OpDecorate %43 Binding 1
OpDecorate %49 BuiltIn LaunchIdKHR
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 2
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeRuntimeArray %5
%16 = OpTypeStruct %15
%17 = OpConstant %5 2
%18 = OpTypeArray %16 %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeFloat 32
%22 = OpTypeImage %21 Buffer 0 0 0 1 Unknown
%23 = OpTypePointer UniformConstant %22
%24 = OpVariable %23 UniformConstant
%25 = OpTypeRuntimeArray %5
%26 = OpTypeStruct %25
%27 = OpTypePointer StorageBuffer %26
%28 = OpVariable %27 StorageBuffer
%29 = OpTypeRuntimeArray %5
%30 = OpTypeStruct %29
%31 = OpTypePointer StorageBuffer %30
%32 = OpVariable %31 StorageBuffer
%33 = OpConstant %5 1024
%34 = OpTypeVector %21 4
%35 = OpTypeArray %34 %33
%36 = OpTypeStruct %35
%37 = OpTypePointer Uniform %36
%38 = OpVariable %37 Uniform
%39 = OpTypeArray %34 %33
%40 = OpTypeStruct %39
%41 = OpTypeArray %40 %17
%42 = OpTypePointer Uniform %41
%43 = OpVariable %42 Uniform
%44 = OpTypePointer Uniform %40
%46 = OpConstant %5 0
%47 = OpTypeVector %5 3
%48 = OpTypePointer Input %47
%49 = OpVariable %48 Input
%50 = OpTypePointer Input %5
%53 = OpConstant %5 1
%54 = OpTypePointer Uniform %34
%57 = OpTypeVector %5 4
%60 = OpTypePointer StorageBuffer %5
%68 = OpConstant %5 3
%93 = OpTypePointer StorageBuffer %10
%102 = OpConstant %5 4
%111 = OpTypePointer StorageBuffer %16
%118 = OpTypeFunction %5 %5 %5
%124 = OpConstant %5 4294967295
%169 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %209
%209 = OpLabel
%45 = OpAccessChain %44 %43 %46
%51 = OpAccessChain %50 %49 %46
%52 = OpLoad %5 %51
%55 = OpAccessChain %54 %38 %46 %53
%56 = OpLoad %34 %55
%58 = OpBitcast %57 %56
%59 = OpCompositeExtract %5 %58 0
%61 = OpAccessChain %60 %32 %46 %46
%62 = OpAtomicIAdd %5 %61 %53 %46 %59
%63 = OpAccessChain %54 %38 %46 %52
%64 = OpLoad %34 %63
%65 = OpBitcast %57 %64
%66 = OpCompositeExtract %5 %65 0
%67 = OpGroupNonUniformBroadcastFirst %5 %68 %66
%69 = OpAccessChain %60 %32 %46 %53
%70 = OpAtomicIAdd %5 %69 %53 %46 %67
%71 = OpAccessChain %54 %45 %46 %53
%72 = OpLoad %34 %71
%73 = OpBitcast %57 %72
%74 = OpCompositeExtract %5 %73 0
%75 = OpGroupNonUniformBroadcastFirst %5 %68 %74
%76 = OpAccessChain %60 %32 %46 %53
%77 = OpAtomicIAdd %5 %76 %53 %46 %75
%78 = OpAccessChain %54 %45 %46 %52
%79 = OpLoad %34 %78
%80 = OpBitcast %57 %79
%81 = OpCompositeExtract %5 %80 0
%82 = OpGroupNonUniformBroadcastFirst %5 %68 %81
%83 = OpAccessChain %60 %32 %46 %53
%84 = OpAtomicIAdd %5 %83 %53 %46 %82
%85 = OpAccessChain %60 %9 %46 %17
%86 = OpLoad %5 %85
%87 = OpAccessChain %60 %32 %46 %46
%88 = OpAtomicIAdd %5 %87 %53 %46 %86
%89 = OpAccessChain %60 %28 %46 %46
%90 = OpLoad %5 %89
%91 = OpAccessChain %60 %32 %46 %46
%92 = OpAtomicIAdd %5 %91 %53 %46 %90
%94 = OpAccessChain %93 %14 %46 %52
%95 = OpLoad %10 %94
%96 = OpCompositeExtract %5 %95 1
%97 = OpGroupNonUniformBroadcastFirst %5 %68 %96
%98 = OpAccessChain %60 %32 %46 %53
%99 = OpAtomicIAdd %5 %98 %53 %46 %97
%100 = OpShiftLeftLogical %5 %52 %17
%101 = OpBitwiseAnd %5 %100 %102
%103 = OpIMul %5 %53 %17
%104 = OpShiftRightLogical %5 %101 %17
%105 = OpIAdd %5 %103 %104
%106 = OpAccessChain %60 %9 %46 %105
%107 = OpLoad %5 %106
%108 = OpGroupNonUniformBroadcastFirst %5 %68 %107
%109 = OpAccessChain %60 %32 %46 %53
%110 = OpAtomicIAdd %5 %109 %53 %46 %108
%112 = OpAccessChain %111 %20 %46
%113 = OpAccessChain %60 %112 %46 %53
%114 = OpLoad %5 %113
%115 = OpGroupNonUniformBroadcastFirst %5 %68 %114
%116 = OpAccessChain %60 %32 %46 %53
%117 = OpAtomicIAdd %5 %116 %53 %46 %115
%127 = OpFunctionCall %5 %121 %52 %102
%128 = OpAccessChain %60 %28 %46 %127
%129 = OpLoad %5 %128
%130 = OpGroupNonUniformBroadcastFirst %5 %68 %129
%131 = OpAccessChain %60 %32 %46 %53
%132 = OpAtomicIAdd %5 %131 %53 %46 %130
%133 = OpAccessChain %60 %32 %46 %17
%134 = OpLoad %5 %133
%135 = OpGroupNonUniformBroadcastFirst %5 %68 %134
%136 = OpAccessChain %60 %32 %46 %53
%137 = OpAtomicIAdd %5 %136 %53 %46 %135
%138 = OpLoad %22 %24
%139 = OpImageFetch %34 %138 %46
%140 = OpCompositeExtract %21 %139 0
%141 = OpGroupNonUniformBroadcastFirst %21 %68 %140
%142 = OpConvertFToU %5 %141
%143 = OpAccessChain %60 %32 %46 %53
%144 = OpAtomicIAdd %5 %143 %53 %46 %142
%145 = OpAccessChain %54 %38 %46 %53
%146 = OpLoad %34 %145
%147 = OpBitcast %57 %146
%148 = OpCompositeExtract %5 %147 0
%149 = OpAccessChain %60 %32 %46 %46
%150 = OpAtomicIAdd %5 %149 %53 %46 %148
%151 = OpAccessChain %54 %38 %46 %52
%152 = OpLoad %34 %151
%153 = OpBitcast %57 %152
%154 = OpCompositeExtract %5 %153 0
%155 = OpGroupNonUniformIAdd %5 %68 Reduce %154
%156 = OpAccessChain %60 %32 %46 %46
%157 = OpAtomicIAdd %5 %156 %53 %46 %155
%158 = OpAccessChain %54 %38 %46 %52
%159 = OpLoad %34 %158
%160 = OpBitcast %57 %159
%161 = OpCompositeExtract %5 %160 0
%162 = OpGroupNonUniformBitwiseOr %5 %68 Reduce %161
%163 = OpAccessChain %60 %32 %46 %46
%164 = OpAtomicIAdd %5 %163 %53 %46 %162
%165 = OpAccessChain %54 %38 %46 %52
%166 = OpLoad %34 %165
%167 = OpBitcast %57 %166
%168 = OpCompositeExtract %5 %167 0
%170 = OpGroupNonUniformAllEqual %169 %68 %168
%171 = OpSelect %5 %170 %53 %46
%172 = OpAccessChain %60 %32 %46 %46
%173 = OpAtomicIAdd %5 %172 %53 %46 %171
%174 = OpAccessChain %54 %38 %46 %52
%175 = OpLoad %34 %174
%176 = OpBitcast %57 %175
%177 = OpCompositeExtract %5 %176 0
%178 = OpINotEqual %169 %177 %46
%179 = OpGroupNonUniformBallot %57 %68 %178
%180 = OpCompositeExtract %5 %179 0
%181 = OpAccessChain %60 %32 %46 %46
%182 = OpAtomicIAdd %5 %181 %53 %46 %180
%183 = OpAccessChain %54 %38 %46 %52
%184 = OpLoad %34 %183
%185 = OpBitcast %57 %184
%186 = OpCompositeExtract %5 %185 0
%187 = OpINotEqual %169 %186 %46
%188 = OpGroupNonUniformAny %169 %68 %187
%189 = OpSelect %5 %188 %53 %46
%190 = OpAccessChain %60 %32 %46 %46
%191 = OpAtomicIAdd %5 %190 %53 %46 %189
%192 = OpAccessChain %54 %38 %46 %52
%193 = OpLoad %34 %192
%194 = OpBitcast %57 %193
%195 = OpCompositeExtract %5 %194 0
%196 = OpINotEqual %169 %195 %46
%197 = OpGroupNonUniformAll %169 %68 %196
%198 = OpSelect %5 %197 %53 %46
%199 = OpAccessChain %60 %32 %46 %46
%200 = OpAtomicIAdd %5 %199 %53 %46 %198
%201 = OpAccessChain %54 %38 %46 %52
%202 = OpLoad %34 %201
%203 = OpBitcast %57 %202
%204 = OpCompositeExtract %5 %203 0
%205 = OpGroupNonUniformIAdd %5 %68 ExclusiveScan %204
%206 = OpGroupNonUniformBroadcastFirst %5 %68 %205
%207 = OpAccessChain %60 %32 %46 %53
%208 = OpAtomicIAdd %5 %207 %53 %46 %206
OpReturn
OpFunctionEnd
%121 = OpFunction %5 None %118
%119 = OpFunctionParameter %5
%120 = OpFunctionParameter %5
%122 = OpLabel
%123 = OpUDiv %5 %124 %120
%125 = OpBitwiseAnd %5 %119 %123
OpReturnValue %125
OpFunctionEnd
#endif
