#version 460
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 0, std430) restrict readonly buffer _12_14
{
    uvec2 _m0[];
} _14;

layout(set = 0, binding = 1, std430) restrict readonly buffer _16_20
{
    uint _m0[];
} _20[2];

layout(set = 0, binding = 4, std430) restrict readonly buffer _26_28
{
    uint _m0[];
} _28;

layout(set = 0, binding = 0, std430) buffer _30_32
{
    uint _m0[];
} _32;

layout(set = 0, binding = 0, std140) uniform _36_38
{
    vec4 _m0[1024];
} _38;

layout(set = 0, binding = 1, std140) uniform _40_43
{
    vec4 _m0[1024];
} _43[2];

layout(set = 0, binding = 3) uniform samplerBuffer _24;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _66 = atomicAdd(_32._m0[0u], floatBitsToUint(_38._m0[1u]).x);
    uint _74 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x));
    uint _81 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_43[0u]._m0[1u]).x));
    uint _88 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_43[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _92 = atomicAdd(_32._m0[0u], _9._m0[2u]);
    uint _96 = atomicAdd(_32._m0[0u], _28._m0[0u]);
    uint _103 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(_14._m0[gl_GlobalInvocationID.x].y));
    uint _107 = 1u * 2u;
    uint _114 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(_9._m0[_107 + (((gl_GlobalInvocationID.x << 2u) & 4u) >> 2u)]));
    uint _121 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(_20[0u]._m0[1u]));
    uint _136 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(_28._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)]));
    uint _141 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(_32._m0[2u]));
    uint _147 = atomicAdd(_32._m0[1u], uint(subgroupBroadcastFirst(texelFetch(_24, int(0u)).x)));
    uint _149 = atomicAdd(_32._m0[0u], gl_WorkGroupID.x);
    uint _152 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _158 = atomicAdd(_32._m0[0u], floatBitsToUint(_38._m0[1u]).x);
    uint _165 = atomicAdd(_32._m0[0u], subgroupAdd(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x));
    uint _172 = atomicAdd(_32._m0[0u], subgroupOr(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x));
    uint _181 = atomicAdd(_32._m0[0u], uint(subgroupAllEqual(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x)));
    uint _190 = atomicAdd(_32._m0[0u], subgroupBallot(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x != 0u).x);
    uint _199 = atomicAdd(_32._m0[0u], uint(subgroupAny(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x != 0u)));
    uint _208 = atomicAdd(_32._m0[0u], uint(subgroupAll(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x != 0u)));
    uint _216 = atomicAdd(_32._m0[1u], subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_38._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 219
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %50 %54
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %16 "SSBO"
OpName %26 "SSBO"
OpName %30 "SSBO"
OpName %36 ""
OpName %40 ""
OpName %125 "ByteAddressMask"
OpName %123 "index"
OpName %124 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 ArrayStride 8
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonWritable
OpDecorate %14 Restrict
OpDecorate %15 ArrayStride 4
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 1
OpDecorate %20 NonWritable
OpDecorate %20 Restrict
OpDecorate %24 DescriptorSet 0
OpDecorate %24 Binding 3
OpDecorate %25 ArrayStride 4
OpMemberDecorate %26 0 Offset 0
OpDecorate %26 Block
OpDecorate %28 DescriptorSet 0
OpDecorate %28 Binding 4
OpDecorate %28 NonWritable
OpDecorate %28 Restrict
OpDecorate %29 ArrayStride 4
OpMemberDecorate %30 0 Offset 0
OpDecorate %30 Block
OpDecorate %32 DescriptorSet 0
OpDecorate %32 Binding 0
OpDecorate %35 ArrayStride 16
OpMemberDecorate %36 0 Offset 0
OpDecorate %36 Block
OpDecorate %38 DescriptorSet 0
OpDecorate %38 Binding 0
OpDecorate %39 ArrayStride 16
OpMemberDecorate %40 0 Offset 0
OpDecorate %40 Block
OpDecorate %43 DescriptorSet 0
OpDecorate %43 Binding 1
OpDecorate %50 BuiltIn GlobalInvocationId
OpDecorate %54 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 2
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeRuntimeArray %5
%16 = OpTypeStruct %15
%17 = OpConstant %5 2
%18 = OpTypeArray %16 %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeFloat 32
%22 = OpTypeImage %21 Buffer 0 0 0 1 Unknown
%23 = OpTypePointer UniformConstant %22
%24 = OpVariable %23 UniformConstant
%25 = OpTypeRuntimeArray %5
%26 = OpTypeStruct %25
%27 = OpTypePointer StorageBuffer %26
%28 = OpVariable %27 StorageBuffer
%29 = OpTypeRuntimeArray %5
%30 = OpTypeStruct %29
%31 = OpTypePointer StorageBuffer %30
%32 = OpVariable %31 StorageBuffer
%33 = OpConstant %5 1024
%34 = OpTypeVector %21 4
%35 = OpTypeArray %34 %33
%36 = OpTypeStruct %35
%37 = OpTypePointer Uniform %36
%38 = OpVariable %37 Uniform
%39 = OpTypeArray %34 %33
%40 = OpTypeStruct %39
%41 = OpTypeArray %40 %17
%42 = OpTypePointer Uniform %41
%43 = OpVariable %42 Uniform
%45 = OpTypePointer Uniform %40
%47 = OpConstant %5 0
%48 = OpTypeVector %5 3
%49 = OpTypePointer Input %48
%50 = OpVariable %49 Input
%51 = OpTypePointer Input %5
%54 = OpVariable %49 Input
%57 = OpConstant %5 1
%58 = OpTypePointer Uniform %34
%61 = OpTypeVector %5 4
%64 = OpTypePointer StorageBuffer %5
%72 = OpConstant %5 3
%97 = OpTypePointer StorageBuffer %10
%106 = OpConstant %5 4
%115 = OpTypePointer StorageBuffer %16
%122 = OpTypeFunction %5 %5 %5
%128 = OpConstant %5 4294967295
%177 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %217
%217 = OpLabel
%44 = OpLoad %22 %24
%46 = OpAccessChain %45 %43 %47
%52 = OpAccessChain %51 %50 %47
%53 = OpLoad %5 %52
%55 = OpAccessChain %51 %54 %47
%56 = OpLoad %5 %55
%59 = OpAccessChain %58 %38 %47 %57
%60 = OpLoad %34 %59
%62 = OpBitcast %61 %60
%63 = OpCompositeExtract %5 %62 0
%65 = OpAccessChain %64 %32 %47 %47
%66 = OpAtomicIAdd %5 %65 %57 %47 %63
%67 = OpAccessChain %58 %38 %47 %53
%68 = OpLoad %34 %67
%69 = OpBitcast %61 %68
%70 = OpCompositeExtract %5 %69 0
%71 = OpGroupNonUniformBroadcastFirst %5 %72 %70
%73 = OpAccessChain %64 %32 %47 %57
%74 = OpAtomicIAdd %5 %73 %57 %47 %71
%75 = OpAccessChain %58 %46 %47 %57
%76 = OpLoad %34 %75
%77 = OpBitcast %61 %76
%78 = OpCompositeExtract %5 %77 0
%79 = OpGroupNonUniformBroadcastFirst %5 %72 %78
%80 = OpAccessChain %64 %32 %47 %57
%81 = OpAtomicIAdd %5 %80 %57 %47 %79
%82 = OpAccessChain %58 %46 %47 %53
%83 = OpLoad %34 %82
%84 = OpBitcast %61 %83
%85 = OpCompositeExtract %5 %84 0
%86 = OpGroupNonUniformBroadcastFirst %5 %72 %85
%87 = OpAccessChain %64 %32 %47 %57
%88 = OpAtomicIAdd %5 %87 %57 %47 %86
%89 = OpAccessChain %64 %9 %47 %17
%90 = OpLoad %5 %89
%91 = OpAccessChain %64 %32 %47 %47
%92 = OpAtomicIAdd %5 %91 %57 %47 %90
%93 = OpAccessChain %64 %28 %47 %47
%94 = OpLoad %5 %93
%95 = OpAccessChain %64 %32 %47 %47
%96 = OpAtomicIAdd %5 %95 %57 %47 %94
%98 = OpAccessChain %97 %14 %47 %53
%99 = OpLoad %10 %98
%100 = OpCompositeExtract %5 %99 1
%101 = OpGroupNonUniformBroadcastFirst %5 %72 %100
%102 = OpAccessChain %64 %32 %47 %57
%103 = OpAtomicIAdd %5 %102 %57 %47 %101
%104 = OpShiftLeftLogical %5 %53 %17
%105 = OpBitwiseAnd %5 %104 %106
%107 = OpIMul %5 %57 %17
%108 = OpShiftRightLogical %5 %105 %17
%109 = OpIAdd %5 %107 %108
%110 = OpAccessChain %64 %9 %47 %109
%111 = OpLoad %5 %110
%112 = OpGroupNonUniformBroadcastFirst %5 %72 %111
%113 = OpAccessChain %64 %32 %47 %57
%114 = OpAtomicIAdd %5 %113 %57 %47 %112
%116 = OpAccessChain %115 %20 %47
%117 = OpAccessChain %64 %116 %47 %57
%118 = OpLoad %5 %117
%119 = OpGroupNonUniformBroadcastFirst %5 %72 %118
%120 = OpAccessChain %64 %32 %47 %57
%121 = OpAtomicIAdd %5 %120 %57 %47 %119
%131 = OpFunctionCall %5 %125 %53 %106
%132 = OpAccessChain %64 %28 %47 %131
%133 = OpLoad %5 %132
%134 = OpGroupNonUniformBroadcastFirst %5 %72 %133
%135 = OpAccessChain %64 %32 %47 %57
%136 = OpAtomicIAdd %5 %135 %57 %47 %134
%137 = OpAccessChain %64 %32 %47 %17
%138 = OpLoad %5 %137
%139 = OpGroupNonUniformBroadcastFirst %5 %72 %138
%140 = OpAccessChain %64 %32 %47 %57
%141 = OpAtomicIAdd %5 %140 %57 %47 %139
%142 = OpImageFetch %34 %44 %47
%143 = OpCompositeExtract %21 %142 0
%144 = OpGroupNonUniformBroadcastFirst %21 %72 %143
%145 = OpConvertFToU %5 %144
%146 = OpAccessChain %64 %32 %47 %57
%147 = OpAtomicIAdd %5 %146 %57 %47 %145
%148 = OpAccessChain %64 %32 %47 %47
%149 = OpAtomicIAdd %5 %148 %57 %47 %56
%150 = OpGroupNonUniformBroadcastFirst %5 %72 %53
%151 = OpAccessChain %64 %32 %47 %57
%152 = OpAtomicIAdd %5 %151 %57 %47 %150
%153 = OpAccessChain %58 %38 %47 %57
%154 = OpLoad %34 %153
%155 = OpBitcast %61 %154
%156 = OpCompositeExtract %5 %155 0
%157 = OpAccessChain %64 %32 %47 %47
%158 = OpAtomicIAdd %5 %157 %57 %47 %156
%159 = OpAccessChain %58 %38 %47 %53
%160 = OpLoad %34 %159
%161 = OpBitcast %61 %160
%162 = OpCompositeExtract %5 %161 0
%163 = OpGroupNonUniformIAdd %5 %72 Reduce %162
%164 = OpAccessChain %64 %32 %47 %47
%165 = OpAtomicIAdd %5 %164 %57 %47 %163
%166 = OpAccessChain %58 %38 %47 %53
%167 = OpLoad %34 %166
%168 = OpBitcast %61 %167
%169 = OpCompositeExtract %5 %168 0
%170 = OpGroupNonUniformBitwiseOr %5 %72 Reduce %169
%171 = OpAccessChain %64 %32 %47 %47
%172 = OpAtomicIAdd %5 %171 %57 %47 %170
%173 = OpAccessChain %58 %38 %47 %53
%174 = OpLoad %34 %173
%175 = OpBitcast %61 %174
%176 = OpCompositeExtract %5 %175 0
%178 = OpGroupNonUniformAllEqual %177 %72 %176
%179 = OpSelect %5 %178 %57 %47
%180 = OpAccessChain %64 %32 %47 %47
%181 = OpAtomicIAdd %5 %180 %57 %47 %179
%182 = OpAccessChain %58 %38 %47 %53
%183 = OpLoad %34 %182
%184 = OpBitcast %61 %183
%185 = OpCompositeExtract %5 %184 0
%186 = OpINotEqual %177 %185 %47
%187 = OpGroupNonUniformBallot %61 %72 %186
%188 = OpCompositeExtract %5 %187 0
%189 = OpAccessChain %64 %32 %47 %47
%190 = OpAtomicIAdd %5 %189 %57 %47 %188
%191 = OpAccessChain %58 %38 %47 %53
%192 = OpLoad %34 %191
%193 = OpBitcast %61 %192
%194 = OpCompositeExtract %5 %193 0
%195 = OpINotEqual %177 %194 %47
%196 = OpGroupNonUniformAny %177 %72 %195
%197 = OpSelect %5 %196 %57 %47
%198 = OpAccessChain %64 %32 %47 %47
%199 = OpAtomicIAdd %5 %198 %57 %47 %197
%200 = OpAccessChain %58 %38 %47 %53
%201 = OpLoad %34 %200
%202 = OpBitcast %61 %201
%203 = OpCompositeExtract %5 %202 0
%204 = OpINotEqual %177 %203 %47
%205 = OpGroupNonUniformAll %177 %72 %204
%206 = OpSelect %5 %205 %57 %47
%207 = OpAccessChain %64 %32 %47 %47
%208 = OpAtomicIAdd %5 %207 %57 %47 %206
%209 = OpAccessChain %58 %38 %47 %53
%210 = OpLoad %34 %209
%211 = OpBitcast %61 %210
%212 = OpCompositeExtract %5 %211 0
%213 = OpGroupNonUniformIAdd %5 %72 ExclusiveScan %212
%214 = OpGroupNonUniformBroadcastFirst %5 %72 %213
%215 = OpAccessChain %64 %32 %47 %57
%216 = OpAtomicIAdd %5 %215 %57 %47 %214
OpReturn
OpFunctionEnd
%125 = OpFunction %5 None %122
%123 = OpFunctionParameter %5
%124 = OpFunctionParameter %5
%126 = OpLabel
%127 = OpUDiv %5 %128 %124
%129 = OpBitwiseAnd %5 %123 %127
OpReturnValue %129
OpFunctionEnd
#endif
