#version 460
#if defined(GL_EXT_control_flow_attributes)
#extension GL_EXT_control_flow_attributes : require
#define SPIRV_CROSS_FLATTEN [[flatten]]
#define SPIRV_CROSS_BRANCH [[dont_flatten]]
#define SPIRV_CROSS_UNROLL [[unroll]]
#define SPIRV_CROSS_LOOP [[dont_unroll]]
#else
#define SPIRV_CROSS_FLATTEN
#define SPIRV_CROSS_BRANCH
#define SPIRV_CROSS_UNROLL
#define SPIRV_CROSS_LOOP
#endif
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform _13_15
{
    vec4 _m0[1];
} _15;

layout(set = 0, binding = 0, r32ui) uniform writeonly uimageBuffer _8;

uint SDiv(uint num, uint den)
{
    uint _42;
    SPIRV_CROSS_FLATTEN
    if (den == 0u)
    {
        _42 = 4294967295u;
    }
    else
    {
        _42 = uint(int(num) / int(den));
    }
    return _42;
}

uint SRem(uint num, uint den)
{
    uint _55;
    SPIRV_CROSS_FLATTEN
    if (den == 0u)
    {
        _55 = 4294967295u;
    }
    else
    {
        _55 = uint(int(num) - int(den) * (int(num) / int(den)));
    }
    return _55;
}

void main()
{
    uvec4 _28 = floatBitsToUint(_15._m0[0u]);
    uint _29 = _28.x;
    uint _44 = SDiv(65536u, _29);
    uint _57 = SRem(65536u, _29);
    if (!(_29 == 0u))
    {
        uint _59;
        _59 = 0u;
        for (;;)
        {
            imageStore(_8, int(_59 + gl_GlobalInvocationID.x), uvec4(_57 + _44));
            uint _60 = _59 + 1u;
            if (_60 == floatBitsToUint(_15._m0[0u]).x)
            {
                break;
            }
            else
            {
                _59 = _60;
            }
        }
    }
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 75
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %19
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %13 ""
OpName %33 "SDiv"
OpName %31 "num"
OpName %32 "den"
OpName %48 "SRem"
OpName %46 "num"
OpName %47 "den"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %8 NonReadable
OpDecorate %12 ArrayStride 16
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 0
OpDecorate %19 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpConstant %5 1
%10 = OpTypeFloat 32
%11 = OpTypeVector %10 4
%12 = OpTypeArray %11 %9
%13 = OpTypeStruct %12
%14 = OpTypePointer Uniform %13
%15 = OpVariable %14 Uniform
%17 = OpTypeVector %5 3
%18 = OpTypePointer Input %17
%19 = OpVariable %18 Input
%20 = OpTypePointer Input %5
%22 = OpConstant %5 0
%24 = OpTypePointer Uniform %11
%27 = OpTypeVector %5 4
%30 = OpTypeFunction %5 %5 %5
%35 = OpConstant %5 4294967295
%38 = OpTypeBool
%40 = OpConstantNull %5
%45 = OpConstant %5 65536
%53 = OpConstantNull %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %69
%69 = OpLabel
%16 = OpLoad %6 %8
%21 = OpAccessChain %20 %19 %22
%23 = OpLoad %5 %21
%25 = OpAccessChain %24 %15 %22 %22
%26 = OpLoad %11 %25
%28 = OpBitcast %27 %26
%29 = OpCompositeExtract %5 %28 0
%44 = OpFunctionCall %5 %33 %45 %29
%57 = OpFunctionCall %5 %48 %45 %29
%58 = OpIEqual %38 %29 %22
OpSelectionMerge %73 None
OpBranchConditional %58 %73 %70
%70 = OpLabel
OpBranch %71
%71 = OpLabel
%59 = OpPhi %5 %22 %70 %60 %71
%61 = OpIAdd %5 %57 %44
%62 = OpIAdd %5 %59 %23
%63 = OpCompositeConstruct %27 %61 %61 %61 %61
OpImageWrite %16 %62 %63
%60 = OpIAdd %5 %59 %9
%64 = OpAccessChain %24 %15 %22 %22
%65 = OpLoad %11 %64
%66 = OpBitcast %27 %65
%67 = OpCompositeExtract %5 %66 0
%68 = OpIEqual %38 %60 %67
OpLoopMerge %72 %71 None
OpBranchConditional %68 %72 %71
%72 = OpLabel
OpBranch %73
%73 = OpLabel
OpReturn
OpFunctionEnd
%33 = OpFunction %5 None %30
%31 = OpFunctionParameter %5
%32 = OpFunctionParameter %5
%34 = OpLabel
%39 = OpIEqual %38 %32 %40
OpSelectionMerge %37 Flatten
OpBranchConditional %39 %37 %36
%36 = OpLabel
%41 = OpSDiv %5 %31 %32
OpBranch %37
%37 = OpLabel
%42 = OpPhi %5 %35 %34 %41 %36
OpReturnValue %42
OpFunctionEnd
%48 = OpFunction %5 None %30
%46 = OpFunctionParameter %5
%47 = OpFunctionParameter %5
%49 = OpLabel
%52 = OpIEqual %38 %47 %53
OpSelectionMerge %51 Flatten
OpBranchConditional %52 %51 %50
%50 = OpLabel
%54 = OpSRem %5 %46 %47
OpBranch %51
%51 = OpLabel
%55 = OpPhi %5 %35 %49 %54 %50
OpReturnValue %55
OpFunctionEnd
#endif
