#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 0, std430) writeonly buffer _12_14
{
    uvec4 _m0[];
} _14;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _22 = gl_GlobalInvocationID.x << 4u;
    uint _33 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _41 = ByteAddressMask(gl_GlobalInvocationID.x + 1u, 16u);
    vec4 _53 = uintBitsToFloat(_10._m0[ByteAddressMask(gl_GlobalInvocationID.x + 2u, 16u)]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x, 16u)] = uvec4(uvec4(u16vec4(_10._m0[_33]) / u16vec4(1us, 2us, 3us, 4us)) + _10._m0[_33]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 16u, 16u)] = uvec4(uvec4(i16vec4(u16vec4(i16vec4(u16vec4(_10._m0[_41])) / i16vec4(u16vec4(1us, 2us, 3us, 4us))))) + _10._m0[_41]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 64u, 16u)] = uvec4(floatBitsToUint(vec4(f16vec4(_53) / f16vec4(float16_t(1.0), float16_t(2.0), float16_t(3.0), float16_t(4.0))) + _53));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 111
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Int16
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpName %27 "ByteAddressMask"
OpName %25 "index"
OpName %26 "stride"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 16
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%23 = OpConstant %5 4
%24 = OpTypeFunction %5 %5 %5
%30 = OpConstant %5 4294967295
%34 = OpConstant %5 16
%35 = OpTypePointer StorageBuffer %6
%40 = OpConstant %5 1
%45 = OpConstant %5 32
%47 = OpConstant %5 2
%51 = OpTypeFloat 32
%52 = OpTypeVector %51 4
%54 = OpTypeInt 16 0
%55 = OpTypeVector %54 4
%58 = OpTypeFloat 16
%59 = OpTypeVector %58 4
%62 = OpConstant %54 1
%63 = OpConstant %54 2
%64 = OpConstant %54 3
%65 = OpConstant %54 4
%66 = OpConstantComposite %55 %62 %63 %64 %65
%69 = OpConstant %58 0x1p+0
%70 = OpConstant %58 0x1p+1
%71 = OpConstant %58 0x1.8p+1
%72 = OpConstant %58 0x1p+2
%73 = OpConstantComposite %59 %69 %70 %71 %72
%88 = OpConstant %5 256
%98 = OpConstant %5 1024
%100 = OpConstant %5 64
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %109
%109 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%22 = OpShiftLeftLogical %5 %21 %23
%33 = OpFunctionCall %5 %27 %21 %34
%36 = OpAccessChain %35 %10 %20 %33
%37 = OpLoad %6 %36
%38 = OpIAdd %5 %22 %34
%39 = OpIAdd %5 %21 %40
%41 = OpFunctionCall %5 %27 %39 %34
%42 = OpAccessChain %35 %10 %20 %41
%43 = OpLoad %6 %42
%44 = OpIAdd %5 %22 %45
%46 = OpIAdd %5 %21 %47
%48 = OpFunctionCall %5 %27 %46 %34
%49 = OpAccessChain %35 %10 %20 %48
%50 = OpLoad %6 %49
%53 = OpBitcast %52 %50
%56 = OpUConvert %55 %37
%57 = OpUConvert %55 %43
%60 = OpFConvert %59 %53
%61 = OpUDiv %55 %56 %66
%67 = OpSDiv %55 %57 %66
%68 = OpFDiv %59 %60 %73
%74 = OpUConvert %6 %61
%75 = OpIAdd %6 %74 %37
%76 = OpSConvert %6 %67
%77 = OpIAdd %6 %76 %43
%78 = OpFConvert %52 %68
%79 = OpFAdd %52 %78 %53
%80 = OpFunctionCall %5 %27 %21 %34
%81 = OpCompositeExtract %5 %75 0
%82 = OpCompositeExtract %5 %75 1
%83 = OpCompositeExtract %5 %75 2
%84 = OpCompositeExtract %5 %75 3
%85 = OpCompositeConstruct %6 %81 %82 %83 %84
%86 = OpAccessChain %35 %14 %20 %80
OpStore %86 %85
%87 = OpIAdd %5 %22 %88
%89 = OpIAdd %5 %21 %34
%90 = OpFunctionCall %5 %27 %89 %34
%91 = OpCompositeExtract %5 %77 0
%92 = OpCompositeExtract %5 %77 1
%93 = OpCompositeExtract %5 %77 2
%94 = OpCompositeExtract %5 %77 3
%95 = OpCompositeConstruct %6 %91 %92 %93 %94
%96 = OpAccessChain %35 %14 %20 %90
OpStore %96 %95
%97 = OpIAdd %5 %22 %98
%99 = OpIAdd %5 %21 %100
%101 = OpFunctionCall %5 %27 %99 %34
%102 = OpBitcast %6 %79
%103 = OpCompositeExtract %5 %102 0
%104 = OpCompositeExtract %5 %102 1
%105 = OpCompositeExtract %5 %102 2
%106 = OpCompositeExtract %5 %102 3
%107 = OpCompositeConstruct %6 %103 %104 %105 %106
%108 = OpAccessChain %35 %14 %20 %101
OpStore %108 %107
OpReturn
OpFunctionEnd
%27 = OpFunction %5 None %24
%25 = OpFunctionParameter %5
%26 = OpFunctionParameter %5
%28 = OpLabel
%29 = OpUDiv %5 %30 %26
%31 = OpBitwiseAnd %5 %25 %29
OpReturnValue %31
OpFunctionEnd
#endif
