#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#if defined(GL_EXT_control_flow_attributes)
#extension GL_EXT_control_flow_attributes : require
#define SPIRV_CROSS_FLATTEN [[flatten]]
#define SPIRV_CROSS_BRANCH [[dont_flatten]]
#define SPIRV_CROSS_UNROLL [[unroll]]
#define SPIRV_CROSS_LOOP [[dont_unroll]]
#else
#define SPIRV_CROSS_FLATTEN
#define SPIRV_CROSS_BRANCH
#define SPIRV_CROSS_UNROLL
#define SPIRV_CROSS_LOOP
#endif
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

u16vec4 _76;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 0, std430) writeonly buffer _12_14
{
    uvec4 _m0[];
} _14;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

u16vec4 UDiv(u16vec4 num, u16vec4 den)
{
    uint16_t _75;
    SPIRV_CROSS_FLATTEN
    if (den.x == 0us)
    {
        _75 = 65535us;
    }
    else
    {
        _75 = num.x / den.x;
    }
    u16vec4 _77;
    _77.x = _75;
    uint16_t _85;
    SPIRV_CROSS_FLATTEN
    if (den.y == 0us)
    {
        _85 = 65535us;
    }
    else
    {
        _85 = num.y / den.y;
    }
    _77.y = _85;
    uint16_t _94;
    SPIRV_CROSS_FLATTEN
    if (den.z == 0us)
    {
        _94 = 65535us;
    }
    else
    {
        _94 = num.z / den.z;
    }
    _77.z = _94;
    uint16_t _103;
    SPIRV_CROSS_FLATTEN
    if (den.w == 0us)
    {
        _103 = 65535us;
    }
    else
    {
        _103 = num.w / den.w;
    }
    _77.w = _103;
    return _77;
}

void main()
{
    uint _22 = gl_GlobalInvocationID.x << 4u;
    uint _33 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _41 = ByteAddressMask(gl_GlobalInvocationID.x + 1u, 16u);
    vec4 _53 = uintBitsToFloat(_10._m0[ByteAddressMask(gl_GlobalInvocationID.x + 2u, 16u)]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x, 16u)] = uvec4(uvec4(UDiv(u16vec4(_10._m0[_33]), u16vec4(1us, 2us, 3us, 4us))) + _10._m0[_33]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 16u, 16u)] = uvec4(uvec4(i16vec4(u16vec4(i16vec4(u16vec4(_10._m0[_41])) / i16vec4(u16vec4(1us, 2us, 3us, 4us))))) + _10._m0[_41]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 64u, 16u)] = uvec4(floatBitsToUint(vec4(f16vec4(_53) / f16vec4(float16_t(1.0), float16_t(2.0), float16_t(3.0), float16_t(4.0))) + _53));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 156
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Int16
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpName %27 "ByteAddressMask"
OpName %25 "index"
OpName %26 "stride"
OpName %64 "UDiv"
OpName %62 "num"
OpName %63 "den"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 16
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%23 = OpConstant %5 4
%24 = OpTypeFunction %5 %5 %5
%30 = OpConstant %5 4294967295
%34 = OpConstant %5 16
%35 = OpTypePointer StorageBuffer %6
%40 = OpConstant %5 1
%45 = OpConstant %5 32
%47 = OpConstant %5 2
%51 = OpTypeFloat 32
%52 = OpTypeVector %51 4
%54 = OpTypeInt 16 0
%55 = OpTypeVector %54 4
%58 = OpTypeFloat 16
%59 = OpTypeVector %58 4
%61 = OpTypeFunction %55 %55 %55
%66 = OpConstant %54 65535
%71 = OpTypeBool
%73 = OpConstantNull %54
%76 = OpUndef %55
%83 = OpConstantNull %54
%92 = OpConstantNull %54
%101 = OpConstantNull %54
%107 = OpConstant %54 1
%108 = OpConstant %54 2
%109 = OpConstant %54 3
%110 = OpConstant %54 4
%111 = OpConstantComposite %55 %107 %108 %109 %110
%114 = OpConstant %58 0x1p+0
%115 = OpConstant %58 0x1p+1
%116 = OpConstant %58 0x1.8p+1
%117 = OpConstant %58 0x1p+2
%118 = OpConstantComposite %59 %114 %115 %116 %117
%133 = OpConstant %5 256
%143 = OpConstant %5 1024
%145 = OpConstant %5 64
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %154
%154 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%22 = OpShiftLeftLogical %5 %21 %23
%33 = OpFunctionCall %5 %27 %21 %34
%36 = OpAccessChain %35 %10 %20 %33
%37 = OpLoad %6 %36
%38 = OpIAdd %5 %22 %34
%39 = OpIAdd %5 %21 %40
%41 = OpFunctionCall %5 %27 %39 %34
%42 = OpAccessChain %35 %10 %20 %41
%43 = OpLoad %6 %42
%44 = OpIAdd %5 %22 %45
%46 = OpIAdd %5 %21 %47
%48 = OpFunctionCall %5 %27 %46 %34
%49 = OpAccessChain %35 %10 %20 %48
%50 = OpLoad %6 %49
%53 = OpBitcast %52 %50
%56 = OpUConvert %55 %37
%57 = OpUConvert %55 %43
%60 = OpFConvert %59 %53
%106 = OpFunctionCall %55 %64 %56 %111
%112 = OpSDiv %55 %57 %111
%113 = OpFDiv %59 %60 %118
%119 = OpUConvert %6 %106
%120 = OpIAdd %6 %119 %37
%121 = OpSConvert %6 %112
%122 = OpIAdd %6 %121 %43
%123 = OpFConvert %52 %113
%124 = OpFAdd %52 %123 %53
%125 = OpFunctionCall %5 %27 %21 %34
%126 = OpCompositeExtract %5 %120 0
%127 = OpCompositeExtract %5 %120 1
%128 = OpCompositeExtract %5 %120 2
%129 = OpCompositeExtract %5 %120 3
%130 = OpCompositeConstruct %6 %126 %127 %128 %129
%131 = OpAccessChain %35 %14 %20 %125
OpStore %131 %130
%132 = OpIAdd %5 %22 %133
%134 = OpIAdd %5 %21 %34
%135 = OpFunctionCall %5 %27 %134 %34
%136 = OpCompositeExtract %5 %122 0
%137 = OpCompositeExtract %5 %122 1
%138 = OpCompositeExtract %5 %122 2
%139 = OpCompositeExtract %5 %122 3
%140 = OpCompositeConstruct %6 %136 %137 %138 %139
%141 = OpAccessChain %35 %14 %20 %135
OpStore %141 %140
%142 = OpIAdd %5 %22 %143
%144 = OpIAdd %5 %21 %145
%146 = OpFunctionCall %5 %27 %144 %34
%147 = OpBitcast %6 %124
%148 = OpCompositeExtract %5 %147 0
%149 = OpCompositeExtract %5 %147 1
%150 = OpCompositeExtract %5 %147 2
%151 = OpCompositeExtract %5 %147 3
%152 = OpCompositeConstruct %6 %148 %149 %150 %151
%153 = OpAccessChain %35 %14 %20 %146
OpStore %153 %152
OpReturn
OpFunctionEnd
%27 = OpFunction %5 None %24
%25 = OpFunctionParameter %5
%26 = OpFunctionParameter %5
%28 = OpLabel
%29 = OpUDiv %5 %30 %26
%31 = OpBitwiseAnd %5 %25 %29
OpReturnValue %31
OpFunctionEnd
%64 = OpFunction %55 None %61
%62 = OpFunctionParameter %55
%63 = OpFunctionParameter %55
%65 = OpLabel
%69 = OpCompositeExtract %54 %62 0
%70 = OpCompositeExtract %54 %63 0
%72 = OpIEqual %71 %70 %73
OpSelectionMerge %68 Flatten
OpBranchConditional %72 %68 %67
%67 = OpLabel
%74 = OpUDiv %54 %69 %70
OpBranch %68
%68 = OpLabel
%75 = OpPhi %54 %66 %65 %74 %67
%77 = OpCompositeInsert %55 %75 %76 0
%80 = OpCompositeExtract %54 %62 1
%81 = OpCompositeExtract %54 %63 1
%82 = OpIEqual %71 %81 %83
OpSelectionMerge %79 Flatten
OpBranchConditional %82 %79 %78
%78 = OpLabel
%84 = OpUDiv %54 %80 %81
OpBranch %79
%79 = OpLabel
%85 = OpPhi %54 %66 %68 %84 %78
%86 = OpCompositeInsert %55 %85 %77 1
%89 = OpCompositeExtract %54 %62 2
%90 = OpCompositeExtract %54 %63 2
%91 = OpIEqual %71 %90 %92
OpSelectionMerge %88 Flatten
OpBranchConditional %91 %88 %87
%87 = OpLabel
%93 = OpUDiv %54 %89 %90
OpBranch %88
%88 = OpLabel
%94 = OpPhi %54 %66 %79 %93 %87
%95 = OpCompositeInsert %55 %94 %86 2
%98 = OpCompositeExtract %54 %62 3
%99 = OpCompositeExtract %54 %63 3
%100 = OpIEqual %71 %99 %101
OpSelectionMerge %97 Flatten
OpBranchConditional %100 %97 %96
%96 = OpLabel
%102 = OpUDiv %54 %98 %99
OpBranch %97
%97 = OpLabel
%103 = OpPhi %54 %66 %88 %102 %96
%104 = OpCompositeInsert %55 %103 %95 3
OpReturnValue %104
OpFunctionEnd
#endif
