#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec4 _m0[];
} _10;

layout(set = 0, binding = 0, std430) writeonly buffer _12_14
{
    uvec4 _m0[];
} _14;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _22 = gl_GlobalInvocationID.x << 4u;
    uint _33 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _41 = ByteAddressMask(gl_GlobalInvocationID.x + 1u, 16u);
    vec4 _53 = uintBitsToFloat(_10._m0[ByteAddressMask(gl_GlobalInvocationID.x + 2u, 16u)]);
    bvec4 _72 = notEqual(u16vec4(1us, 2us, 3us, 4us), u16vec4(0));
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x, 16u)] = uvec4(uvec4(mix(u16vec4(65535), u16vec4(_10._m0[_33]) / mix(u16vec4(65535), u16vec4(1us, 2us, 3us, 4us), _72), _72)) + _10._m0[_33]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 16u, 16u)] = uvec4(uvec4(i16vec4(u16vec4(i16vec4(u16vec4(_10._m0[_41])) / i16vec4(u16vec4(1us, 2us, 3us, 4us))))) + _10._m0[_41]);
    _14._m0[ByteAddressMask(gl_GlobalInvocationID.x + 64u, 16u)] = uvec4(floatBitsToUint(vec4(f16vec4(_53) / f16vec4(float16_t(1.0), float16_t(2.0), float16_t(3.0), float16_t(4.0))) + _53));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 120
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Int16
OpCapability DenormPreserve
OpExtension "SPV_KHR_float_controls"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpName %27 "ByteAddressMask"
OpName %25 "index"
OpName %26 "stride"
OpDecorate %7 ArrayStride 16
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 16
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 4
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%23 = OpConstant %5 4
%24 = OpTypeFunction %5 %5 %5
%30 = OpConstant %5 4294967295
%34 = OpConstant %5 16
%35 = OpTypePointer StorageBuffer %6
%40 = OpConstant %5 1
%45 = OpConstant %5 32
%47 = OpConstant %5 2
%51 = OpTypeFloat 32
%52 = OpTypeVector %51 4
%54 = OpTypeInt 16 0
%55 = OpTypeVector %54 4
%58 = OpTypeFloat 16
%59 = OpTypeVector %58 4
%61 = OpConstant %54 0
%62 = OpConstant %54 65535
%63 = OpTypeBool
%64 = OpTypeVector %63 4
%65 = OpConstantComposite %55 %61 %61 %61 %61
%66 = OpConstantComposite %55 %62 %62 %62 %62
%67 = OpConstant %54 1
%68 = OpConstant %54 2
%69 = OpConstant %54 3
%70 = OpConstant %54 4
%71 = OpConstantComposite %55 %67 %68 %69 %70
%78 = OpConstant %58 0x1p+0
%79 = OpConstant %58 0x1p+1
%80 = OpConstant %58 0x1.8p+1
%81 = OpConstant %58 0x1p+2
%82 = OpConstantComposite %59 %78 %79 %80 %81
%97 = OpConstant %5 256
%107 = OpConstant %5 1024
%109 = OpConstant %5 64
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %118
%118 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%22 = OpShiftLeftLogical %5 %21 %23
%33 = OpFunctionCall %5 %27 %21 %34
%36 = OpAccessChain %35 %10 %20 %33
%37 = OpLoad %6 %36
%38 = OpIAdd %5 %22 %34
%39 = OpIAdd %5 %21 %40
%41 = OpFunctionCall %5 %27 %39 %34
%42 = OpAccessChain %35 %10 %20 %41
%43 = OpLoad %6 %42
%44 = OpIAdd %5 %22 %45
%46 = OpIAdd %5 %21 %47
%48 = OpFunctionCall %5 %27 %46 %34
%49 = OpAccessChain %35 %10 %20 %48
%50 = OpLoad %6 %49
%53 = OpBitcast %52 %50
%56 = OpUConvert %55 %37
%57 = OpUConvert %55 %43
%60 = OpFConvert %59 %53
%72 = OpINotEqual %64 %71 %65
%73 = OpSelect %55 %72 %71 %66
%74 = OpUDiv %55 %56 %73
%75 = OpSelect %55 %72 %74 %66
%76 = OpSDiv %55 %57 %71
%77 = OpFDiv %59 %60 %82
%83 = OpUConvert %6 %75
%84 = OpIAdd %6 %83 %37
%85 = OpSConvert %6 %76
%86 = OpIAdd %6 %85 %43
%87 = OpFConvert %52 %77
%88 = OpFAdd %52 %87 %53
%89 = OpFunctionCall %5 %27 %21 %34
%90 = OpCompositeExtract %5 %84 0
%91 = OpCompositeExtract %5 %84 1
%92 = OpCompositeExtract %5 %84 2
%93 = OpCompositeExtract %5 %84 3
%94 = OpCompositeConstruct %6 %90 %91 %92 %93
%95 = OpAccessChain %35 %14 %20 %89
OpStore %95 %94
%96 = OpIAdd %5 %22 %97
%98 = OpIAdd %5 %21 %34
%99 = OpFunctionCall %5 %27 %98 %34
%100 = OpCompositeExtract %5 %86 0
%101 = OpCompositeExtract %5 %86 1
%102 = OpCompositeExtract %5 %86 2
%103 = OpCompositeExtract %5 %86 3
%104 = OpCompositeConstruct %6 %100 %101 %102 %103
%105 = OpAccessChain %35 %14 %20 %99
OpStore %105 %104
%106 = OpIAdd %5 %22 %107
%108 = OpIAdd %5 %21 %109
%110 = OpFunctionCall %5 %27 %108 %34
%111 = OpBitcast %6 %88
%112 = OpCompositeExtract %5 %111 0
%113 = OpCompositeExtract %5 %111 1
%114 = OpCompositeExtract %5 %111 2
%115 = OpCompositeExtract %5 %111 3
%116 = OpCompositeConstruct %6 %112 %113 %114 %115
%117 = OpAccessChain %35 %14 %20 %110
OpStore %117 %116
OpReturn
OpFunctionEnd
%27 = OpFunction %5 None %24
%25 = OpFunctionParameter %5
%26 = OpFunctionParameter %5
%28 = OpLabel
%29 = OpUDiv %5 %30 %26
%31 = OpBitwiseAnd %5 %25 %29
OpReturnValue %31
OpFunctionEnd
#endif
