#define NV_SHADER_EXTN_SLOT u127
#define NV_SHADER_EXTN_REGISTER_SPACE space0
#include "nvHLSLExtns.h"

RWByteAddressBuffer BAB;
RWTexture1D<uint2> RWTex1;
RWTexture2D<uint2> RWTex2;
RWTexture3D<uint2> RWTex3;

RWStructuredBuffer<uint2> UAV1;

[numthreads(32, 1, 1)]
void main(uint thr : SV_DispatchThreadID)
{
    uint64_t v64 = thr + 1ull;
	uint2 v = uint2(v64, v64 >> 32);
    uint64_t c64 = thr + 2ull;
    uint2 c = uint2(c64, c64 >> 32);

    UAV1[100] = NvInterlockedAddUint64(BAB, 16, v);
    UAV1[101] = NvInterlockedMinUint64(BAB, 16, v);
    UAV1[102] = NvInterlockedMaxUint64(BAB, 16, v);
    UAV1[103] = NvInterlockedAndUint64(BAB, 16, v);
    UAV1[104] = NvInterlockedOrUint64(BAB, 16, v);
    UAV1[105] = NvInterlockedXorUint64(BAB, 16, v);
    UAV1[106] = NvInterlockedExchangeUint64(BAB, 16, v);
    UAV1[110] = NvInterlockedCompareExchangeUint64(BAB, 16, c, v);

    UAV1[107] = NvInterlockedAddUint64(RWTex1, 5, v);
    UAV1[108] = NvInterlockedAddUint64(RWTex2, uint2(6,7), v);
    UAV1[109] = NvInterlockedAddUint64(RWTex3, uint3(8,9,10), v);
    UAV1[111] = NvInterlockedCompareExchangeUint64(RWTex1, 8, c, v);
}
