RWBuffer<uint> Data : register(u0);

[numthreads(64, 1, 1)]
void main(uint3 thread_id : SV_DispatchThreadID)
{
	uint index = thread_id.x + 3;
	uint original;
	uint compared;
	uint count;

	InterlockedAdd(Data[index], 1, original);
	InterlockedCompareExchange(Data[index + 1], original, original + 2, compared);
	uint loaded = Data[index + 2];
	Data[index + 3] = loaded ^ compared;
	Data.GetDimensions(count);
	if (count == 0)
		Data[0] = original;
}
