; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 172
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledImageArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability StorageImageArrayDynamicIndexing
OpCapability StorageImageWriteWithoutFormat
OpCapability RayTracingKHR
OpCapability RuntimeDescriptorArray
OpCapability UniformBufferArrayNonUniformIndexing
OpCapability SampledImageArrayNonUniformIndexing
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability StorageImageArrayNonUniformIndexing
OpCapability ShaderInvocationReorderEXT
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_EXT_shader_invocation_reorder"
OpExtension "SPV_KHR_ray_tracing"
OpMemoryModel Logical GLSL450
OpEntryPoint RayGenerationKHR %3 "main" %8 %12 %16 %20
OpName %3 "main"
OpName %8 "AS"
OpName %12 "IMG"
OpName %14 ""
OpName %18 ""
OpDecorate %8 DescriptorSet 40
OpDecorate %8 Binding 30
OpDecorate %12 DescriptorSet 20
OpDecorate %12 Binding 10
OpDecorate %12 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 1
%6 = OpTypeAccelerationStructureKHR
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeFloat 32
%10 = OpTypeImage %9 2D 0 0 0 2 Unknown
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeVector %9 4
%14 = OpTypeStruct %13
%15 = OpTypePointer RayPayloadKHR %14
%16 = OpVariable %15 RayPayloadKHR
%17 = OpTypeVector %9 2
%18 = OpTypeStruct %17
%19 = OpTypePointer HitObjectAttributeEXT %18
%20 = OpVariable %19 HitObjectAttributeEXT
%22 = OpTypeInt 32 0
%23 = OpConstant %22 0
%24 = OpConstant %9 1
%25 = OpConstant %9 0
%26 = OpConstant %9 2
%27 = OpConstant %9 3
%28 = OpConstant %9 4
%29 = OpTypeVector %9 3
%32 = OpTypeHitObjectEXT
%33 = OpTypePointer Function %32
%35 = OpTypeBool
%37 = OpTypePointer RayPayloadKHR %13
%86 = OpTypeMatrix %29 4
%134 = OpConstantNull %18
%144 = OpTypePointer HitObjectAttributeEXT %17
%156 = OpConstantComposite %13 %24 %25 %25 %24
%157 = OpConstantComposite %13 %25 %24 %25 %24
%164 = OpTypeVector %22 2
%3 = OpFunction %1 None %2
%4 = OpLabel
%34 = OpVariable %33 Function
%42 = OpUndef %29
%140 = OpUndef %13
OpBranch %167
%167 = OpLabel
%21 = OpLoad %6 %8
%30 = OpCompositeConstruct %29 %24 %26 %27
%31 = OpCompositeConstruct %29 %25 %25 %24
OpHitObjectTraceRayEXT %34 %21 %23 %23 %23 %23 %23 %30 %24 %31 %28 %16
%36 = OpHitObjectIsHitEXT %35 %34
OpSelectionMerge %170 None
OpBranchConditional %36 %169 %168
%169 = OpLabel
%38 = OpInBoundsAccessChain %37 %16 %23
%39 = OpLoad %13 %38
%40 = OpHitObjectGetRayTMinEXT %9 %34
%41 = OpCompositeInsert %29 %40 %42 0
%43 = OpVectorShuffle %29 %41 %42 0 0 0
%44 = OpHitObjectGetRayTMaxEXT %9 %34
%45 = OpCompositeInsert %29 %44 %43 1
%46 = OpHitObjectGetWorldRayOriginEXT %29 %34
%47 = OpCompositeExtract %9 %46 0
%48 = OpCompositeInsert %29 %47 %42 0
%49 = OpHitObjectGetWorldRayOriginEXT %29 %34
%50 = OpCompositeExtract %9 %49 1
%51 = OpCompositeInsert %29 %50 %48 1
%52 = OpHitObjectGetWorldRayOriginEXT %29 %34
%53 = OpCompositeExtract %9 %52 2
%54 = OpCompositeInsert %29 %53 %51 2
%55 = OpFAdd %29 %54 %45
%56 = OpHitObjectGetWorldRayDirectionEXT %29 %34
%57 = OpCompositeExtract %9 %56 0
%58 = OpCompositeInsert %29 %57 %42 0
%59 = OpHitObjectGetWorldRayDirectionEXT %29 %34
%60 = OpCompositeExtract %9 %59 1
%61 = OpCompositeInsert %29 %60 %58 1
%62 = OpHitObjectGetWorldRayDirectionEXT %29 %34
%63 = OpCompositeExtract %9 %62 2
%64 = OpCompositeInsert %29 %63 %61 2
%65 = OpFAdd %29 %55 %64
%66 = OpHitObjectGetObjectRayOriginEXT %29 %34
%67 = OpCompositeExtract %9 %66 0
%68 = OpCompositeInsert %29 %67 %42 0
%69 = OpHitObjectGetObjectRayOriginEXT %29 %34
%70 = OpCompositeExtract %9 %69 1
%71 = OpCompositeInsert %29 %70 %68 1
%72 = OpHitObjectGetObjectRayOriginEXT %29 %34
%73 = OpCompositeExtract %9 %72 2
%74 = OpCompositeInsert %29 %73 %71 2
%75 = OpFAdd %29 %65 %74
%76 = OpHitObjectGetObjectRayDirectionEXT %29 %34
%77 = OpCompositeExtract %9 %76 0
%78 = OpCompositeInsert %29 %77 %42 0
%79 = OpHitObjectGetObjectRayDirectionEXT %29 %34
%80 = OpCompositeExtract %9 %79 1
%81 = OpCompositeInsert %29 %80 %78 1
%82 = OpHitObjectGetObjectRayDirectionEXT %29 %34
%83 = OpCompositeExtract %9 %82 2
%84 = OpCompositeInsert %29 %83 %81 2
%85 = OpFAdd %29 %75 %84
%87 = OpHitObjectGetObjectToWorldEXT %86 %34
%88 = OpCompositeExtract %9 %87 0 0
%89 = OpCompositeInsert %29 %88 %42 0
%90 = OpHitObjectGetObjectToWorldEXT %86 %34
%91 = OpCompositeExtract %9 %90 1 0
%92 = OpCompositeInsert %29 %91 %89 1
%93 = OpHitObjectGetObjectToWorldEXT %86 %34
%94 = OpCompositeExtract %9 %93 2 0
%95 = OpCompositeInsert %29 %94 %92 2
%96 = OpFAdd %29 %85 %95
%97 = OpHitObjectGetObjectToWorldEXT %86 %34
%98 = OpCompositeExtract %9 %97 0 1
%99 = OpCompositeInsert %29 %98 %89 1
%100 = OpHitObjectGetObjectToWorldEXT %86 %34
%101 = OpCompositeExtract %9 %100 0 2
%102 = OpCompositeInsert %29 %101 %99 2
%103 = OpFAdd %29 %96 %102
%104 = OpHitObjectGetWorldToObjectEXT %86 %34
%105 = OpCompositeExtract %9 %104 0 0
%106 = OpCompositeInsert %29 %105 %42 0
%107 = OpHitObjectGetWorldToObjectEXT %86 %34
%108 = OpCompositeExtract %9 %107 1 0
%109 = OpCompositeInsert %29 %108 %106 1
%110 = OpHitObjectGetWorldToObjectEXT %86 %34
%111 = OpCompositeExtract %9 %110 2 0
%112 = OpCompositeInsert %29 %111 %109 2
%113 = OpFAdd %29 %103 %112
%114 = OpHitObjectGetWorldToObjectEXT %86 %34
%115 = OpCompositeExtract %9 %114 0 1
%116 = OpCompositeInsert %29 %115 %106 1
%117 = OpHitObjectGetWorldToObjectEXT %86 %34
%118 = OpCompositeExtract %9 %117 0 2
%119 = OpCompositeInsert %29 %118 %116 2
%120 = OpFAdd %29 %113 %119
%121 = OpHitObjectGetRayFlagsEXT %22 %34
%122 = OpHitObjectGetInstanceCustomIndexEXT %22 %34
%123 = OpIAdd %22 %122 %121
%124 = OpHitObjectGetInstanceIdEXT %22 %34
%125 = OpIAdd %22 %123 %124
%126 = OpHitObjectGetGeometryIndexEXT %22 %34
%127 = OpIAdd %22 %125 %126
%128 = OpHitObjectGetPrimitiveIndexEXT %22 %34
%129 = OpIAdd %22 %127 %128
%130 = OpHitObjectGetHitKindEXT %22 %34
%131 = OpIAdd %22 %129 %130
%132 = OpHitObjectGetShaderBindingTableRecordIndexEXT %22 %34
%133 = OpIAdd %22 %131 %132
OpStore %20 %134
OpHitObjectGetAttributesEXT %34 %20
%135 = OpCompositeExtract %9 %120 0
%136 = OpCompositeExtract %9 %120 1
%137 = OpCompositeExtract %9 %120 2
%138 = OpConvertUToF %9 %133
%139 = OpCompositeInsert %13 %135 %140 0
%141 = OpCompositeInsert %13 %136 %139 1
%142 = OpCompositeInsert %13 %137 %141 2
%143 = OpCompositeInsert %13 %138 %142 3
%145 = OpInBoundsAccessChain %144 %20 %23
%146 = OpLoad %17 %145
%147 = OpCompositeExtract %9 %146 0
%148 = OpCompositeExtract %9 %39 2
%149 = OpCompositeInsert %13 %147 %140 0
%150 = OpCompositeInsert %13 %147 %149 1
%151 = OpCompositeInsert %13 %148 %150 2
%152 = OpCompositeInsert %13 %24 %151 3
%153 = OpFAdd %13 %152 %143
OpBranch %170
%168 = OpLabel
%154 = OpHitObjectIsMissEXT %35 %34
%155 = OpSelect %13 %154 %156 %157
OpBranch %170
%170 = OpLabel
%158 = OpPhi %13 %153 %169 %155 %168
%159 = OpLoad %10 %12
%160 = OpCompositeExtract %9 %158 0
%161 = OpCompositeExtract %9 %158 1
%162 = OpCompositeExtract %9 %158 2
%163 = OpCompositeExtract %9 %158 3
%165 = OpCompositeConstruct %164 %23 %23
%166 = OpCompositeConstruct %13 %160 %161 %162 %163
OpImageWrite %159 %165 %166
OpReturn
OpFunctionEnd

