; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 141
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledImageArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability StorageImageArrayDynamicIndexing
OpCapability StorageImageWriteWithoutFormat
OpCapability RayQueryKHR
OpCapability RayTraversalPrimitiveCullingKHR
OpCapability RayTracingKHR
OpCapability RuntimeDescriptorArray
OpCapability UniformBufferArrayNonUniformIndexing
OpCapability SampledImageArrayNonUniformIndexing
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability StorageImageArrayNonUniformIndexing
OpCapability ShaderInvocationReorderEXT
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_EXT_shader_invocation_reorder"
OpExtension "SPV_KHR_ray_query"
OpExtension "SPV_KHR_ray_tracing"
OpMemoryModel Logical GLSL450
OpEntryPoint RayGenerationKHR %3 "main" %8 %12 %16 %17 %21 %25 %35 %96
OpName %3 "main"
OpName %8 "AS"
OpName %12 "IMG"
OpName %14 ""
OpName %19 ""
OpName %114 "frontier_phi_10.pred.7.ladder.11.ladder"
OpName %115 "frontier_phi_10.pred.7.ladder"
OpName %116 "frontier_phi_10.pred"
OpName %117 "frontier_phi_10.pred.7.ladder.11.ladder"
OpName %118 "frontier_phi_10.pred.7.ladder"
OpName %119 "frontier_phi_10.pred"
OpName %120 "frontier_phi_8.5.ladder"
OpDecorate %8 DescriptorSet 40
OpDecorate %8 Binding 30
OpDecorate %12 DescriptorSet 20
OpDecorate %12 Binding 10
OpDecorate %12 NonReadable
OpDecorate %25 BuiltIn LaunchIdKHR
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 1
%6 = OpTypeAccelerationStructureKHR
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeFloat 32
%10 = OpTypeImage %9 2D 0 0 0 2 Unknown
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeVector %9 3
%14 = OpTypeStruct %13
%15 = OpTypePointer RayPayloadKHR %14
%16 = OpVariable %15 RayPayloadKHR
%17 = OpVariable %15 RayPayloadKHR
%18 = OpTypeVector %9 2
%19 = OpTypeStruct %18
%20 = OpTypePointer HitObjectAttributeEXT %19
%21 = OpVariable %20 HitObjectAttributeEXT
%22 = OpTypeInt 32 0
%23 = OpTypeVector %22 3
%24 = OpTypePointer Input %23
%25 = OpVariable %24 Input
%26 = OpTypePointer Input %22
%28 = OpConstant %22 0
%31 = OpConstant %22 1
%33 = OpTypeRayQueryKHR
%34 = OpTypePointer Private %33
%35 = OpVariable %34 Private
%37 = OpConstant %22 132
%38 = OpConstant %22 255
%39 = OpConstant %9 1
%40 = OpConstant %9 5
%41 = OpConstant %9 2
%42 = OpConstant %9 6
%43 = OpConstant %9 3
%44 = OpConstant %9 7
%46 = OpConstant %9 4
%48 = OpConstant %9 8
%49 = OpTypeBool
%58 = OpConstant %22 2
%63 = OpTypePointer HitObjectAttributeEXT %18
%65 = OpTypeHitObjectEXT
%66 = OpTypePointer Function %65
%70 = OpConstant %22 268435455
%71 = OpConstant %22 65535
%74 = OpTypePointer RayPayloadKHR %13
%76 = OpConstantNull %13
%82 = OpConstant %9 0.100000001
%83 = OpConstant %9 0.200000003
%84 = OpConstant %9 0.300000012
%85 = OpConstantComposite %13 %82 %83 %84
%90 = OpTypeVector %22 2
%92 = OpTypeVector %9 4
%95 = OpTypePointer HitObjectAttributeEXT %1
%96 = OpVariable %95 HitObjectAttributeEXT
%3 = OpFunction %1 None %2
%4 = OpLabel
%67 = OpVariable %66 Function
%94 = OpVariable %66 Function
%52 = OpUndef %18
%73 = OpUndef %22
OpBranch %121
%121 = OpLabel
%27 = OpAccessChain %26 %25 %28
%29 = OpLoad %22 %27
%30 = OpAccessChain %26 %25 %31
%32 = OpLoad %22 %30
%36 = OpLoad %6 %8
%45 = OpCompositeConstruct %13 %39 %41 %43
%47 = OpCompositeConstruct %13 %40 %42 %44
OpRayQueryInitializeKHR %35 %36 %37 %38 %45 %46 %47 %48
%50 = OpRayQueryProceedKHR %49 %35
OpSelectionMerge %134 None
OpBranchConditional %50 %122 %134
%122 = OpLabel
OpBranch %123
%123 = OpLabel
%59 = OpPhi %18 %52 %122 %53 %132
%60 = OpPhi %22 %28 %122 %55 %132
%61 = OpRayQueryGetIntersectionTypeKHR %22 %35 %28
%62 = OpIEqual %49 %61 %28
OpLoopMerge %133 %132 None
OpBranch %124
%124 = OpLabel
OpSelectionMerge %131 None
OpBranchConditional %62 %130 %125
%130 = OpLabel
OpRayQueryConfirmIntersectionKHR %35
OpBranch %131
%125 = OpLabel
%79 = OpIEqual %49 %61 %31
OpSelectionMerge %129 None
OpBranchConditional %79 %126 %129
%126 = OpLabel
%104 = OpRayQueryGetIntersectionPrimitiveIndexKHR %22 %35 %28
%105 = OpUGreaterThan %49 %104 %58
OpSelectionMerge %128 None
OpBranchConditional %105 %128 %127
%127 = OpLabel
%106 = OpRayQueryGetRayTMinKHR %9 %35
OpRayQueryGenerateIntersectionKHR %35 %106
%107 = OpRayQueryGetIntersectionObjectRayOriginKHR %13 %35 %28
%108 = OpCompositeExtract %9 %107 0
%109 = OpCompositeInsert %18 %108 %52 0
%110 = OpRayQueryGetIntersectionObjectRayOriginKHR %13 %35 %28
%111 = OpCompositeExtract %9 %110 1
%101 = OpCompositeInsert %18 %111 %109 1
%112 = OpRayQueryGetIntersectionObjectRayDirectionKHR %13 %35 %28
%113 = OpCompositeExtract %9 %112 2
%102 = OpConvertFToU %22 %113
OpBranch %128
%128 = OpLabel
%114 = OpPhi %18 %59 %126 %101 %127
%117 = OpPhi %22 %60 %126 %102 %127
OpBranch %129
%129 = OpLabel
%115 = OpPhi %18 %59 %125 %114 %128
%118 = OpPhi %22 %60 %125 %117 %128
OpBranch %131
%131 = OpLabel
%116 = OpPhi %18 %59 %130 %115 %129
%119 = OpPhi %22 %60 %130 %118 %129
%53 = OpCopyObject %18 %116
%55 = OpCopyObject %22 %119
OpBranch %132
%132 = OpLabel
%103 = OpRayQueryProceedKHR %49 %35
OpBranchConditional %103 %123 %133
%133 = OpLabel
OpBranch %134
%134 = OpLabel
%51 = OpPhi %18 %52 %121 %53 %133
%54 = OpPhi %22 %28 %121 %55 %133
%56 = OpRayQueryGetIntersectionTypeKHR %22 %35 %31
%57 = OpIEqual %49 %56 %58
OpSelectionMerge %139 None
OpBranchConditional %57 %138 %135
%138 = OpLabel
%64 = OpInBoundsAccessChain %63 %21 %28
OpStore %64 %51
OpHitObjectRecordFromQueryEXT %67 %35 %28 %21 %54
%68 = OpHitObjectIsHitEXT %49 %67
%69 = OpSelect %22 %68 %70 %71
%72 = OpBitwiseAnd %22 %28 %69
OpHitObjectSetShaderBindingTableRecordIndexEXT %67 %72
OpReorderThreadWithHitObjectEXT %67 %73 %28
%75 = OpInBoundsAccessChain %74 %17 %28
OpStore %75 %76
OpHitObjectExecuteShaderEXT %67 %17
%77 = OpLoad %13 %75
OpBranch %139
%135 = OpLabel
%78 = OpIEqual %49 %56 %31
OpSelectionMerge %137 None
OpBranchConditional %78 %136 %137
%136 = OpLabel
OpHitObjectRecordFromQueryEXT %94 %35 %28 %96
%97 = OpHitObjectIsHitEXT %49 %94
%98 = OpSelect %22 %97 %70 %71
%99 = OpBitwiseAnd %22 %31 %98
OpHitObjectSetShaderBindingTableRecordIndexEXT %94 %99
OpReorderThreadWithHitObjectEXT %94 %73 %28
%100 = OpInBoundsAccessChain %74 %16 %28
OpStore %100 %76
OpHitObjectExecuteShaderEXT %94 %16
%81 = OpLoad %13 %100
OpBranch %137
%137 = OpLabel
%120 = OpPhi %13 %81 %136 %85 %135
OpBranch %139
%139 = OpLabel
%80 = OpPhi %13 %77 %138 %120 %137
%86 = OpCompositeExtract %9 %80 0
%87 = OpCompositeExtract %9 %80 1
%88 = OpCompositeExtract %9 %80 2
%89 = OpLoad %10 %12
%91 = OpCompositeConstruct %90 %29 %32
%93 = OpCompositeConstruct %92 %86 %87 %88 %39
OpImageWrite %89 %91 %93
OpReturn
OpFunctionEnd

