; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 133
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledImageArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability StorageImageArrayDynamicIndexing
OpCapability StorageImageWriteWithoutFormat
OpCapability RayQueryKHR
OpCapability RayTraversalPrimitiveCullingKHR
OpCapability RayTracingKHR
OpCapability RuntimeDescriptorArray
OpCapability UniformBufferArrayNonUniformIndexing
OpCapability SampledImageArrayNonUniformIndexing
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability StorageImageArrayNonUniformIndexing
OpCapability ShaderInvocationReorderEXT
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_EXT_shader_invocation_reorder"
OpExtension "SPV_KHR_ray_query"
OpExtension "SPV_KHR_ray_tracing"
OpMemoryModel Logical GLSL450
OpEntryPoint RayGenerationKHR %3 "main" %8 %12 %16 %17 %21 %25 %35 %91
OpName %3 "main"
OpName %8 "AS"
OpName %12 "IMG"
OpName %14 ""
OpName %19 ""
OpName %106 "frontier_phi_10.pred.7.ladder.11.ladder"
OpName %107 "frontier_phi_10.pred.7.ladder"
OpName %108 "frontier_phi_10.pred"
OpName %109 "frontier_phi_10.pred.7.ladder.11.ladder"
OpName %110 "frontier_phi_10.pred.7.ladder"
OpName %111 "frontier_phi_10.pred"
OpName %112 "frontier_phi_8.5.ladder"
OpDecorate %8 DescriptorSet 40
OpDecorate %8 Binding 30
OpDecorate %12 DescriptorSet 20
OpDecorate %12 Binding 10
OpDecorate %12 NonReadable
OpDecorate %25 BuiltIn LaunchIdKHR
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 1
%6 = OpTypeAccelerationStructureKHR
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeFloat 32
%10 = OpTypeImage %9 2D 0 0 0 2 Unknown
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeVector %9 3
%14 = OpTypeStruct %13
%15 = OpTypePointer RayPayloadKHR %14
%16 = OpVariable %15 RayPayloadKHR
%17 = OpVariable %15 RayPayloadKHR
%18 = OpTypeVector %9 2
%19 = OpTypeStruct %18
%20 = OpTypePointer HitObjectAttributeEXT %19
%21 = OpVariable %20 HitObjectAttributeEXT
%22 = OpTypeInt 32 0
%23 = OpTypeVector %22 3
%24 = OpTypePointer Input %23
%25 = OpVariable %24 Input
%26 = OpTypePointer Input %22
%28 = OpConstant %22 0
%31 = OpConstant %22 1
%33 = OpTypeRayQueryKHR
%34 = OpTypePointer Private %33
%35 = OpVariable %34 Private
%37 = OpConstant %22 132
%38 = OpConstant %22 255
%39 = OpConstant %9 1
%40 = OpConstant %9 5
%41 = OpConstant %9 2
%42 = OpConstant %9 6
%43 = OpConstant %9 3
%44 = OpConstant %9 7
%46 = OpConstant %9 4
%48 = OpConstant %9 8
%49 = OpTypeBool
%58 = OpConstant %22 2
%63 = OpTypePointer HitObjectAttributeEXT %18
%65 = OpTypeHitObjectEXT
%66 = OpTypePointer Function %65
%69 = OpTypePointer RayPayloadKHR %13
%71 = OpConstantNull %13
%77 = OpConstant %9 0.100000001
%78 = OpConstant %9 0.200000003
%79 = OpConstant %9 0.300000012
%80 = OpConstantComposite %13 %77 %78 %79
%85 = OpTypeVector %22 2
%87 = OpTypeVector %9 4
%90 = OpTypePointer HitObjectAttributeEXT %1
%91 = OpVariable %90 HitObjectAttributeEXT
%3 = OpFunction %1 None %2
%4 = OpLabel
%67 = OpVariable %66 Function
%89 = OpVariable %66 Function
%52 = OpUndef %18
%68 = OpUndef %22
OpBranch %113
%113 = OpLabel
%27 = OpAccessChain %26 %25 %28
%29 = OpLoad %22 %27
%30 = OpAccessChain %26 %25 %31
%32 = OpLoad %22 %30
%36 = OpLoad %6 %8
%45 = OpCompositeConstruct %13 %39 %41 %43
%47 = OpCompositeConstruct %13 %40 %42 %44
OpRayQueryInitializeKHR %35 %36 %37 %38 %45 %46 %47 %48
%50 = OpRayQueryProceedKHR %49 %35
OpSelectionMerge %126 None
OpBranchConditional %50 %114 %126
%114 = OpLabel
OpBranch %115
%115 = OpLabel
%59 = OpPhi %18 %52 %114 %53 %124
%60 = OpPhi %22 %28 %114 %55 %124
%61 = OpRayQueryGetIntersectionTypeKHR %22 %35 %28
%62 = OpIEqual %49 %61 %28
OpLoopMerge %125 %124 None
OpBranch %116
%116 = OpLabel
OpSelectionMerge %123 None
OpBranchConditional %62 %122 %117
%122 = OpLabel
OpRayQueryConfirmIntersectionKHR %35
OpBranch %123
%117 = OpLabel
%74 = OpIEqual %49 %61 %31
OpSelectionMerge %121 None
OpBranchConditional %74 %118 %121
%118 = OpLabel
%96 = OpRayQueryGetIntersectionPrimitiveIndexKHR %22 %35 %28
%97 = OpUGreaterThan %49 %96 %58
OpSelectionMerge %120 None
OpBranchConditional %97 %120 %119
%119 = OpLabel
%98 = OpRayQueryGetRayTMinKHR %9 %35
OpRayQueryGenerateIntersectionKHR %35 %98
%99 = OpRayQueryGetIntersectionObjectRayOriginKHR %13 %35 %28
%100 = OpCompositeExtract %9 %99 0
%101 = OpCompositeInsert %18 %100 %52 0
%102 = OpRayQueryGetIntersectionObjectRayOriginKHR %13 %35 %28
%103 = OpCompositeExtract %9 %102 1
%93 = OpCompositeInsert %18 %103 %101 1
%104 = OpRayQueryGetIntersectionObjectRayDirectionKHR %13 %35 %28
%105 = OpCompositeExtract %9 %104 2
%94 = OpConvertFToU %22 %105
OpBranch %120
%120 = OpLabel
%106 = OpPhi %18 %59 %118 %93 %119
%109 = OpPhi %22 %60 %118 %94 %119
OpBranch %121
%121 = OpLabel
%107 = OpPhi %18 %59 %117 %106 %120
%110 = OpPhi %22 %60 %117 %109 %120
OpBranch %123
%123 = OpLabel
%108 = OpPhi %18 %59 %122 %107 %121
%111 = OpPhi %22 %60 %122 %110 %121
%53 = OpCopyObject %18 %108
%55 = OpCopyObject %22 %111
OpBranch %124
%124 = OpLabel
%95 = OpRayQueryProceedKHR %49 %35
OpBranchConditional %95 %115 %125
%125 = OpLabel
OpBranch %126
%126 = OpLabel
%51 = OpPhi %18 %52 %113 %53 %125
%54 = OpPhi %22 %28 %113 %55 %125
%56 = OpRayQueryGetIntersectionTypeKHR %22 %35 %31
%57 = OpIEqual %49 %56 %58
OpSelectionMerge %131 None
OpBranchConditional %57 %130 %127
%130 = OpLabel
%64 = OpInBoundsAccessChain %63 %21 %28
OpStore %64 %51
OpHitObjectRecordFromQueryEXT %67 %35 %28 %21 %54
OpHitObjectSetShaderBindingTableRecordIndexEXT %67 %28
OpReorderThreadWithHitObjectEXT %67 %68 %28
%70 = OpInBoundsAccessChain %69 %17 %28
OpStore %70 %71
OpHitObjectExecuteShaderEXT %67 %17
%72 = OpLoad %13 %70
OpBranch %131
%127 = OpLabel
%73 = OpIEqual %49 %56 %31
OpSelectionMerge %129 None
OpBranchConditional %73 %128 %129
%128 = OpLabel
OpHitObjectRecordFromQueryEXT %89 %35 %28 %91
OpHitObjectSetShaderBindingTableRecordIndexEXT %89 %31
OpReorderThreadWithHitObjectEXT %89 %68 %28
%92 = OpInBoundsAccessChain %69 %16 %28
OpStore %92 %71
OpHitObjectExecuteShaderEXT %89 %16
%76 = OpLoad %13 %92
OpBranch %129
%129 = OpLabel
%112 = OpPhi %13 %76 %128 %80 %127
OpBranch %131
%131 = OpLabel
%75 = OpPhi %13 %72 %130 %112 %129
%81 = OpCompositeExtract %9 %75 0
%82 = OpCompositeExtract %9 %75 1
%83 = OpCompositeExtract %9 %75 2
%84 = OpLoad %10 %12
%86 = OpCompositeConstruct %85 %29 %32
%88 = OpCompositeConstruct %87 %81 %82 %83 %39
OpImageWrite %84 %86 %88
OpReturn
OpFunctionEnd

