#version 460
#extension GL_KHR_shader_subgroup_basic : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, r32ui) uniform writeonly uimageBuffer _8;

shared float _13[256];

void main()
{
    bool _26 = gl_SubgroupSize != 0u;
    uint _29 = _26 ? (256u / (_26 ? gl_SubgroupSize : 4294967295u)) : 4294967295u;
    bool _30 = _29 == 0u;
    bool _31;
    if (_30)
    {
        _31 = true;
    }
    else
    {
        _13[0u] = 0.0;
        _13[1u] = 1.0;
        _13[2u] = 2.0;
        _13[3u] = 3.0;
        _13[4u] = 4.0;
        _13[5u] = 5.0;
        _13[6u] = 6.0;
        _13[7u] = 7.0;
        _13[8u] = 8.0;
        _13[9u] = 9.0;
        _13[10u] = 10.0;
        _13[11u] = 11.0;
        _13[12u] = 12.0;
        _13[13u] = 13.0;
        _13[14u] = 14.0;
        _13[15u] = 15.0;
        bool frontier_phi_1_9_ladder;
        if (_29 > 4u)
        {
            _13[16u] = 16.0;
            _13[17u] = 17.0;
            _13[18u] = 18.0;
            _13[19u] = 19.0;
            bool frontier_phi_1_9_ladder_10_ladder;
            if (_29 > 5u)
            {
                _13[20u] = 20.0;
                _13[21u] = 21.0;
                _13[22u] = 22.0;
                _13[23u] = 23.0;
                bool frontier_phi_1_9_ladder_10_ladder_11_ladder;
                if (_29 > 6u)
                {
                    _13[24u] = 24.0;
                    _13[25u] = 25.0;
                    _13[26u] = 26.0;
                    _13[27u] = 27.0;
                    bool frontier_phi_1_9_ladder_10_ladder_11_ladder_12_ladder;
                    if (_29 > 7u)
                    {
                        _13[28u] = 28.0;
                        _13[29u] = 29.0;
                        _13[30u] = 30.0;
                        _13[31u] = 31.0;
                        frontier_phi_1_9_ladder_10_ladder_11_ladder_12_ladder = _30;
                    }
                    else
                    {
                        frontier_phi_1_9_ladder_10_ladder_11_ladder_12_ladder = _30;
                    }
                    frontier_phi_1_9_ladder_10_ladder_11_ladder = frontier_phi_1_9_ladder_10_ladder_11_ladder_12_ladder;
                }
                else
                {
                    frontier_phi_1_9_ladder_10_ladder_11_ladder = _30;
                }
                frontier_phi_1_9_ladder_10_ladder = frontier_phi_1_9_ladder_10_ladder_11_ladder;
            }
            else
            {
                frontier_phi_1_9_ladder_10_ladder = _30;
            }
            frontier_phi_1_9_ladder = frontier_phi_1_9_ladder_10_ladder;
        }
        else
        {
            frontier_phi_1_9_ladder = _30;
        }
        _31 = frontier_phi_1_9_ladder;
    }
    barrier();
    if (!_31)
    {
        uint _60;
        _60 = 0u;
        for (;;)
        {
            uint _78 = gl_GlobalInvocationID.x * 4u;
            imageStore(_8, int(_78), uvec4(floatBitsToUint(_13[0u + (_60 * 4u)])));
            imageStore(_8, int(_78 + 1u), uvec4(floatBitsToUint(_13[1u + (_60 * 4u)])));
            imageStore(_8, int(_78 + 2u), uvec4(floatBitsToUint(_13[2u + (_60 * 4u)])));
            imageStore(_8, int(_78 + 3u), uvec4(floatBitsToUint(_13[3u + (_60 * 4u)])));
            uint _61 = _60 + 1u;
            if (_61 < _29)
            {
                _60 = _61;
            }
            else
            {
                break;
            }
        }
    }
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 193
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability GroupNonUniform
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %17 %22
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %170 "frontier_phi_1.9.ladder.10.ladder.11.ladder.12.ladder"
OpName %171 "frontier_phi_1.9.ladder.10.ladder.11.ladder"
OpName %172 "frontier_phi_1.9.ladder.10.ladder"
OpName %173 "frontier_phi_1.9.ladder"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %8 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
OpDecorate %22 BuiltIn SubgroupSize
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpConstant %5 256
%10 = OpTypeFloat 32
%11 = OpTypeArray %10 %9
%12 = OpTypePointer Workgroup %11
%13 = OpVariable %12 Workgroup
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%22 = OpVariable %18 Input
%24 = OpConstant %5 4294967295
%25 = OpTypeBool
%32 = OpConstantTrue %25
%33 = OpConstant %5 2
%34 = OpConstant %5 264
%35 = OpTypePointer Workgroup %10
%37 = OpConstant %10 0
%39 = OpConstant %5 1
%40 = OpConstant %10 1
%42 = OpConstant %10 2
%44 = OpConstant %5 3
%45 = OpConstant %10 3
%48 = OpConstant %5 4
%49 = OpConstant %10 4
%51 = OpConstant %5 5
%52 = OpConstant %10 5
%54 = OpConstant %5 6
%55 = OpConstant %10 6
%57 = OpConstant %5 7
%58 = OpConstant %10 7
%83 = OpTypeVector %5 4
%93 = OpConstant %5 8
%94 = OpConstant %10 8
%96 = OpConstant %5 9
%97 = OpConstant %10 9
%99 = OpConstant %5 10
%100 = OpConstant %10 10
%102 = OpConstant %5 11
%103 = OpConstant %10 11
%106 = OpConstant %5 12
%107 = OpConstant %10 12
%109 = OpConstant %5 13
%110 = OpConstant %10 13
%112 = OpConstant %5 14
%113 = OpConstant %10 14
%115 = OpConstant %5 15
%116 = OpConstant %10 15
%119 = OpConstant %5 16
%120 = OpConstant %10 16
%122 = OpConstant %5 17
%123 = OpConstant %10 17
%125 = OpConstant %5 18
%126 = OpConstant %10 18
%128 = OpConstant %5 19
%129 = OpConstant %10 19
%132 = OpConstant %5 20
%133 = OpConstant %10 20
%135 = OpConstant %5 21
%136 = OpConstant %10 21
%138 = OpConstant %5 22
%139 = OpConstant %10 22
%141 = OpConstant %5 23
%142 = OpConstant %10 23
%145 = OpConstant %5 24
%146 = OpConstant %10 24
%148 = OpConstant %5 25
%149 = OpConstant %10 25
%151 = OpConstant %5 26
%152 = OpConstant %10 26
%154 = OpConstant %5 27
%155 = OpConstant %10 27
%158 = OpConstant %5 28
%159 = OpConstant %10 28
%161 = OpConstant %5 29
%162 = OpConstant %10 29
%164 = OpConstant %5 30
%165 = OpConstant %10 30
%167 = OpConstant %5 31
%168 = OpConstant %10 31
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %174
%174 = OpLabel
%14 = OpLoad %6 %8
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%23 = OpLoad %5 %22
%26 = OpINotEqual %25 %23 %20
%27 = OpSelect %5 %26 %23 %24
%28 = OpUDiv %5 %9 %27
%29 = OpSelect %5 %26 %28 %24
%30 = OpIEqual %25 %29 %20
OpSelectionMerge %187 None
OpBranchConditional %30 %187 %175
%175 = OpLabel
%36 = OpAccessChain %35 %13 %20
OpStore %36 %37
%38 = OpAccessChain %35 %13 %39
OpStore %38 %40
%41 = OpAccessChain %35 %13 %33
OpStore %41 %42
%43 = OpAccessChain %35 %13 %44
OpStore %43 %45
%46 = OpUGreaterThan %25 %29 %39
OpBranch %176
%176 = OpLabel
%47 = OpAccessChain %35 %13 %48
OpStore %47 %49
%50 = OpAccessChain %35 %13 %51
OpStore %50 %52
%53 = OpAccessChain %35 %13 %54
OpStore %53 %55
%56 = OpAccessChain %35 %13 %57
OpStore %56 %58
%59 = OpUGreaterThan %25 %29 %33
OpBranch %177
%177 = OpLabel
%92 = OpAccessChain %35 %13 %93
OpStore %92 %94
%95 = OpAccessChain %35 %13 %96
OpStore %95 %97
%98 = OpAccessChain %35 %13 %99
OpStore %98 %100
%101 = OpAccessChain %35 %13 %102
OpStore %101 %103
%104 = OpUGreaterThan %25 %29 %44
OpBranch %178
%178 = OpLabel
%105 = OpAccessChain %35 %13 %106
OpStore %105 %107
%108 = OpAccessChain %35 %13 %109
OpStore %108 %110
%111 = OpAccessChain %35 %13 %112
OpStore %111 %113
%114 = OpAccessChain %35 %13 %115
OpStore %114 %116
%117 = OpUGreaterThan %25 %29 %48
OpSelectionMerge %186 None
OpBranchConditional %117 %179 %186
%179 = OpLabel
%118 = OpAccessChain %35 %13 %119
OpStore %118 %120
%121 = OpAccessChain %35 %13 %122
OpStore %121 %123
%124 = OpAccessChain %35 %13 %125
OpStore %124 %126
%127 = OpAccessChain %35 %13 %128
OpStore %127 %129
%130 = OpUGreaterThan %25 %29 %51
OpSelectionMerge %185 None
OpBranchConditional %130 %180 %185
%180 = OpLabel
%131 = OpAccessChain %35 %13 %132
OpStore %131 %133
%134 = OpAccessChain %35 %13 %135
OpStore %134 %136
%137 = OpAccessChain %35 %13 %138
OpStore %137 %139
%140 = OpAccessChain %35 %13 %141
OpStore %140 %142
%143 = OpUGreaterThan %25 %29 %54
OpSelectionMerge %184 None
OpBranchConditional %143 %181 %184
%181 = OpLabel
%144 = OpAccessChain %35 %13 %145
OpStore %144 %146
%147 = OpAccessChain %35 %13 %148
OpStore %147 %149
%150 = OpAccessChain %35 %13 %151
OpStore %150 %152
%153 = OpAccessChain %35 %13 %154
OpStore %153 %155
%156 = OpUGreaterThan %25 %29 %57
OpSelectionMerge %183 None
OpBranchConditional %156 %182 %183
%182 = OpLabel
%157 = OpAccessChain %35 %13 %158
OpStore %157 %159
%160 = OpAccessChain %35 %13 %161
OpStore %160 %162
%163 = OpAccessChain %35 %13 %164
OpStore %163 %165
%166 = OpAccessChain %35 %13 %167
OpStore %166 %168
%169 = OpUGreaterThan %25 %29 %93
OpBranch %183
%183 = OpLabel
%170 = OpPhi %25 %30 %182 %30 %181
OpBranch %184
%184 = OpLabel
%171 = OpPhi %25 %30 %180 %170 %183
OpBranch %185
%185 = OpLabel
%172 = OpPhi %25 %30 %179 %171 %184
OpBranch %186
%186 = OpLabel
%173 = OpPhi %25 %30 %178 %172 %185
OpBranch %187
%187 = OpLabel
%31 = OpPhi %25 %32 %174 %173 %186
OpControlBarrier %33 %33 %34
OpSelectionMerge %191 None
OpBranchConditional %31 %191 %188
%188 = OpLabel
OpBranch %189
%189 = OpLabel
%60 = OpPhi %5 %20 %188 %61 %189
%62 = OpIMul %5 %60 %48
%63 = OpIAdd %5 %20 %62
%64 = OpAccessChain %35 %13 %63
%65 = OpLoad %10 %64
%66 = OpIMul %5 %60 %48
%67 = OpIAdd %5 %39 %66
%68 = OpAccessChain %35 %13 %67
%69 = OpLoad %10 %68
%70 = OpIMul %5 %60 %48
%71 = OpIAdd %5 %33 %70
%72 = OpAccessChain %35 %13 %71
%73 = OpLoad %10 %72
%74 = OpIMul %5 %60 %48
%75 = OpIAdd %5 %44 %74
%76 = OpAccessChain %35 %13 %75
%77 = OpLoad %10 %76
%78 = OpIMul %5 %21 %48
%79 = OpBitcast %5 %65
%80 = OpBitcast %5 %69
%81 = OpBitcast %5 %73
%82 = OpBitcast %5 %77
%84 = OpCompositeConstruct %83 %79 %79 %79 %79
OpImageWrite %14 %78 %84
%85 = OpCompositeConstruct %83 %80 %80 %80 %80
%86 = OpIAdd %5 %78 %39
OpImageWrite %14 %86 %85
%87 = OpCompositeConstruct %83 %81 %81 %81 %81
%88 = OpIAdd %5 %78 %33
OpImageWrite %14 %88 %87
%89 = OpCompositeConstruct %83 %82 %82 %82 %82
%90 = OpIAdd %5 %78 %44
OpImageWrite %14 %90 %89
%61 = OpIAdd %5 %60 %39
%91 = OpULessThan %25 %61 %29
OpLoopMerge %190 %189 None
OpBranchConditional %91 %189 %190
%190 = OpLabel
OpBranch %191
%191 = OpLabel
OpReturn
OpFunctionEnd
#endif
